### ISSUE TITLE
refreshIdToken doesn't use same scope

### ISSUE THREAD

**Issue by ahaid** [auth0/auth0-angular#101]
When I make a call to my API using a token that has been refreshed, the scopes I requested in the initial signin aren't being kept. This causes the decodedPayload to not have all the profile fields I asked for.

Here's my signin:

    $scope.login = function() {
        auth.signin({
            authParams: {
              scope: 'openid profile email offline_access',
              device: 'browser'
            }}, function(profile, token, access_token, state, refresh_token) {
          store.set('profile', profile);
          store.set('idToken', token);
          store.set('refreshToken', refresh_token)
          $location.path("/");
        }, function(error) {
          console.log("There was an error logging in", error);
        });
    }

Upon calling jwtHelper.decodeToken (client or server-side) with the idToken stored above, the decoded payload will have the entire user profile and email. However, if the original idToken expires and I refresh it, the following calls to my API server only have the minimal ID fields. All profile data and email are gone.

Here is my refresh code:

    jwtInterceptorProvider.tokenGetter = function(store, $http, jwtHelper, auth) {
          var idToken = store.get('idToken');
          var refreshToken = store.get('refreshToken');
          if (idToken != null){
              if (jwtHelper.isTokenExpired(idToken)) {
               return auth.refreshIdToken(refreshToken);
              }
          }
          return idToken;
        }

How can I instruct the refreshIdToken call to use the same scopes as the signin call?

**Comment by msandt3** [comment]
Hey @mgonto I'm getting a similar issue, even after bumping the version of auth0-angular to 4.0 (my auth0.js version shows 6.0.6). When I refresh my idToken and append it with the requests it responds with "User not found or no profile included with JWT . . . did you forget profile in your scope?". 

I've included my jwtInterceptor code below
```js
	var refreshingToken = null;

	jwtInterceptorProvider.tokenGetter = function(store, $http, auth, jwtHelper) {
    var token = store.get('token');
    var refreshToken = store.get('refreshToken');
    if (token) {
      if (!jwtHelper.isTokenExpired(token)) {
        return store.get('token');
      } else {
        if (refreshingToken === null) {
          refreshingToken =  auth.refreshIdToken(refreshToken).then(function(idToken) {
            store.set('token', idToken);
            return idToken;
          }).finally(function() {
              refreshingToken = null;
          });
        }
        return refreshingToken;
      }
    }
  }
```

as well as my location change algorithm

```js
	var refreshingToken = null;
  $rootScope.$on('$locationChangeStart', function() {
    if (!auth.isAuthenticated) {
      var token = store.get('token');
      var refreshToken = store.get('refreshToken');
      if (token) {
        if (!jwtHelper.isTokenExpired(token)) {
          auth.authenticate(store.get('profile'), token);
        } else {
          if (refreshToken) {
            if (refreshingToken === null) {
                refreshingToken =  auth.refreshIdToken(refreshToken).then(function(idToken) {
                  store.set('token', idToken);
                  auth.authenticate(store.get('profile'), idToken);
                }).finally(function() {
                    refreshingToken = null;
                });
            }
            return refreshingToken;
          } else {
            $location.path('/login');
          }
        }
      }
    }
  });
```

I've even gone so far as to force the refresh of the idToken on every time the jwtInterceptor is run, and it returns the same result. I pulled most of this from the guides [here](https://github.com/auth0/auth0-angular/blob/master/docs/refresh-token.md). Any guidance you could give me would be greatly appreciated.

**Comment by mgonto** [comment]
Hey @msandt3, 

The code looks right.

Could you provide a gist, jsfiddle, plunkr or github project with a reproduceable sample? That way it's easier to debug it?

Thanks!

**Comment by jimwheaton** [comment]
I'm having a similar issue. Requesting scope: profile for the initial token, but auth.refreshIdToken(refreshToken) returns a JWT without the profile info in it. I created an issue #147 before finding this post.

**Comment by mgonto** [comment]
Hey @jimwheaton ,

Thanks for the report!

Any chance you can provide a gist, jsfiddle plunkr or something to reproduce the error?

Thanks!

**Comment by msandt3** [comment]
Hey @mgonto I'll create a github project you can clone today. It's from a largely proprietary codebase so I'm going to abstract a lot of the business logic before I share. Stay tuned.

**Comment by msandt3** [comment]
@mgonto  the workaround @jimwheaton provided using the delegation endpoint ends up working. So I integrated that into my codebase. You can close this if you like.

**Comment by mgonto** [comment]
I'll close this one and leave the other one open for debugging and fixing. Thanks to both!
