### ISSUE TITLE
No error emitted when getAccessTokenSilently fails

### ISSUE THREAD

**Issue by jreilly-lukava** [auth0/auth0-angular#103]
### Describe the problem

When the access token can no longer be renewed and the authorization server responds with "Login Required", the error$ observable does not appear to emit the error.  I'm uncertain how to handle this situation in my application without building my own getAccessTokenSilently function.

### What was the expected behavior?

To receive an error message in the error$ observable which my application can then respond to.

- **Version of `auth0-angular` used: 1.3.1**
- **Which browsers have you tested in? Firefox**
- **Which version of Angular have you tested with? 11.0.5**

**Comment by frederikprijck** [comment]
Thanks for reporting. This currently doesnt get emitted as part of the `error$` observable. I do think it makes sense to do so.

However, you should be able to handle this yourself for now by handing the error explicitly when calling getAccessTokenSilently by using the `catchError` operator or the error callback:

```
this.authService.getAccessTokenSilently().pipe(catchError(err => /* Handle err */));
```
or
```
this.authService.getAccessTokenSilently().subscribe(null, err => /* Handle err */);
```

Keeping this open as I think this is a valuable addition to pass that error to the error observable.

**Comment by jreilly-lukava** [comment]
I'm glad to hear that you think it would be a valuable addition.  Maybe I'll take a crack at contributing a PR.  But if not I guess I'd have to implement my own HttpInterceptor as well.  Thanks for following up.

**Comment by frederikprijck** [comment]
Good point on the interceptor. However, the interceptor currently is not related to the AuthService, so I think this is somewhat a different subject. 

I guess we want to have the interceptor use the AuthService to ensure it also uses `getAccessTokenSilently` and populate the error observable accordingly (which should happen automatically if we apply the above mentioned fix).

Anyway, it looks like the current state of the SDK has no way for you to catch the error when triggered as part of the interceptor.

To help you on the short term, I guess you could use your own interceptor like this:

```
@Injectable()
export class CustomAuthHttpInterceptor extends AuthHttpInterceptor {
  constructor(
    private configFactory: AuthClientConfig,
    @Inject(Auth0ClientService) private auth0Client: Auth0Client
  ) {
    super(Auth0ClientService, auth0Client);
  }

  intercept(
    req: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {
    return super.intercept(req, next).pipe(catchError(err => /* Handle err */));
  }
}
```

However, I still think we should look at our interceptor to allow for being notified on the given error without the need for the above code.

Let me know if you want to work on a PR, if not I am happy to fix it :)

**Comment by jreilly-lukava** [comment]
Well, it was easy enough to slap the catchError into getAccessTokenSilently.  But then I tried to write a test for it and fell on my face :) I guess I'll work on other things and hopefully you'll have some time to fix it and then I can learn from your changes.  Keep up the great work!

**Comment by frederikprijck** [comment]
Hey @jreilly-lukava ,

I opened a PR https://github.com/auth0/auth0-angular/pull/104, could you have a look and verify this solves your concern?

Thanks,

**Comment by jreilly-lukava** [comment]
LGTM
