### ISSUE TITLE
Consider only emitting user$ and idTokenClaims$ if they changed

### ISSUE THREAD

**Issue by jreilly-lukava** [auth0/auth0-angular#105]
### Describe the suggestion

Consider only emitting user$ and idTokenClaims$ if they are different.  It seems pointless to me to fire them every time getTokenSilently is called, which could happen incredibly often.  Unless of course I'm missing something.

**Comment by frederikprijck** [comment]
In situations when using LocalStorage, calling `getUser` will pull the user from localStorage again, resulting in a new object so it is not possible to do a reference check. Same goes for getIdTokenClaims.

Even tho it's emitting alot, we are sure now that the application receives the latest user. The application itself should be able to determine if the user changes or not based on their own condition, as this can be different for every application.

However, I am interested to see if this can be improved, but I think it will need changes in the SPA-JS SDK that the Angular SDK is relying on. I will have a conversation internally.

**Comment by frederikprijck** [comment]
Adding for context: It looks like this can result in infinite requests: https://community.auth0.com/t/infinite-requests-when-piping-auth-user-in-angular-auth-o/57136/2

**Comment by saschwarz** [comment]
After upgrading to 1.3.2 my application also started running in infinite loops. FWIW the subscription is being triggered each time the interceptor is called. Thanks for posting that link!

**Comment by frederikprijck** [comment]
Hey @jreilly-lukava and @saschwarz,

Sorry for the extreme delay here. I opened a PR https://github.com/auth0/auth0-angular/pull/131, would you be able to validate whether or not this improves things for you ?

Thanks

**Comment by jreilly-lukava** [comment]
@frederikprijck In my particular use case, I was making 4 API calls on the load of a page and I was seeing the user$ emit 4 times.  As well as 4 more times every time I "refreshed" the data. With the above changes I'm seeing user emit only 2 times now.  I'm not certain if it's doing it twice because of something else in my code or not, but obviously this is an improvement and it's not emitting when I "refresh" the data either.  So this looks to resolve the "issue" I was having.

**Comment by frederikprijck** [comment]
@jreilly-lukava Ye it's still not ideal, but it should emit a lot less now. It should now, initially, emit twice but as of then only emit when the token was changed. Instead of constantly when u call `getTokenSilently`.
