### ISSUE TITLE
AuthService isAuthenticated$ emits true even when the idToken has expired. 

### ISSUE THREAD

**Issue by twisha** [auth0/auth0-angular#108]
### Describe the problem

isAuthenticated$ observable of AuthService emits true even when the idToken has expired. 
Just to note, user$ observable emits undefined, which is expected.

I have guarded HomeComponent route with AuthGuard available from auth0-angular lib. However even when idToken has expired the canActivate seems to pass (returns true).

```import { Component, OnInit } from '@angular/core';
import { AuthService } from '@auth0/auth0-angular';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  constructor(public auth: AuthService) { }

  ngOnInit(): void {
    this.auth.user$.subscribe(v => console.log(v));
    this.auth.isAuthenticated$.subscribe(v => console.log(v));
  }

}
```
![image](https://user-images.githubusercontent.com/2581238/105116053-f4e2d500-5a97-11eb-8f8e-c54c4eaf8caa.png)

### What was the expected behavior?

I'm expecting AuthGuard to fail (canActivate return false) and auth.isAuthenticated$ to emit false.

### Reproduction

- **Version of `auth0-angular` used:** 1.3.1
- **Which browsers have you tested in?** Chrome
- **Which version of Angular have you tested with?** Angular 11
- **Other modules/plugins/libraries that might be involved:** -

**Comment by frederikprijck** [comment]
Thanks for reporting this. I think I know what is going wrong and I will look into this.

**Comment by frederikprijck** [comment]
@twisha  I added a PR to fix this. If you would be able to verify this solves your use-case, just to be sure, that would be great.

**Comment by twisha** [comment]
Thank you @frederikprijck !!

**Comment by alexey-tikhonok** [comment]
Thank you @frederikprijck for your answer.
It would be really good to have a description to the behavior in your documentation to point out to our client.
I'll  only  add a couple of words about using localstorage - it is most  [insecure option](https://auth0.com/docs/security/data-security/token-storage#browser-local-storage-scenarios) insecure option to store token, especially when you use most secure type of authentication - MFA.
