### ISSUE TITLE
Returned token doesn't include correct audience

### ISSUE THREAD

**Issue by benrei** [auth0/auth0-angular#110]
### Describe the problem
Trying to set up in my `app.module.ts` :
```js
...
    AuthModule.forRoot({
      domain: "myDomain.eu.auth0.com",
      clientId: "myClientID",
      audience: "myAudience"
    }),
...
```
When I decode the returned token I get: `"aud": "myClientID"` not `"aud": "myAudience"`
So basically my token is useless for my api.

### Environment

- **Version of `auth0-angular` used:** 1.3.1
- **Which browsers have you tested in?** Chrome
- **Which version of Angular have you tested with?** 11
- **Other modules/plugins/libraries that might be involved:**

**Comment by traviscollins** [comment]
I'm having this exact problem. Wish someone left some notes here on workarounds/fixes.

**Comment by frederikprijck** [comment]
Hey @traviscollins , can you share the code you are using and the version of the SDK?

**Comment by traviscollins** [comment]
**Package and version**
@auth0/auth0-angular@1.11.1



**During module import**

```
Auth0Module.forRoot({
      domain: environment.auth0.domain,
      clientId: environment.auth0.clientID,  
      audience: environment.auth0.audience,
      scope: 'openid profile email everything',
    }),
```

**Later for login..**
```
this.auth0Service
      .loginWithRedirect({
        audience: environment.auth0.audience,
      })
      .subscribe();
```

Auth0 returns a JWT access token where the audience value is set to the clientID, not the API URL given as the `audience` value during the "Auth0Module.forRoot(...)" or the "auth0Service.loginWithRedirect(...)" calls. 

The API URL I'm giving it is configured in the Auth0 account. It is working as expected with other clients that do not use this package. I suspect it has something to do with the code flow .

**Comment by frederikprijck** [comment]
> I suspect it has something to do with the code flow .
I have tested this and works with this package, so I am unable to reproduce this.

Can you verify `environment.auth0.audience` does contain the value you expect?
Can you verify in the network tab, you will see a request happening to `/authorize` , what audience is being sent there?
Can you verify there are no Auth0 rules or actions involved here that could potentialy impact this ?

Thanks,

**Comment by traviscollins** [comment]
Verified the `evironment.auth0.audience` value in the debugger at runtime is the API URL.  See full authorize request in the screenshot below. The audience is a URL.

<img width="1333" alt="Screenshot 2023-06-28 at 11 36 36 AM" src="https://github.com/auth0/auth0-angular/assets/923065/4f5941c0-7127-479a-907a-9be46cf6aea8">



See the "aud" value returned in the access token below matches the client_id from above. 

<img width="1247" alt="Screenshot 2023-06-28 at 11 28 36 AM" src="https://github.com/auth0/auth0-angular/assets/923065/a8fa144d-c9e2-4f89-9c36-e1d327861c68">


We have a few rules and actions that update user metadata, but the word "audience" and "aud" do not appear in any of them.

**Comment by frederikprijck** [comment]
It does look like the audience is sent to auth0, so the issue should be outside of the SDK.

Just to be sure, Are you looking at the id token or access token?

I recommend todisable all rules and verify the issue persists.

**Comment by traviscollins** [comment]
> Just to be sure, Are you looking at the id token or access token?

This is the id token, as the access token returned from the code flow is not a JWT. It is apparently an opaque string.

**Comment by frederikprijck** [comment]
The id token will never have the audience set to anything but the client id. So that audience is expected.

Access token shouldnt be an opaque string if u pass the audience, so i would look into that to ensure it gives u a JWT, but as long as you pass the audience to the /authorize call, the issue sounds related to actions/ rules or anything server side.

**Comment by traviscollins** [comment]
I set the audience in the code again (was testing other options without it), and I see the access token has the expected audience. 

I guess in out other applications we were not using the code flow, so we got back the id token and the access token in a single response. For this application we have to do a separate call to the Auth0 API to get the access token. 

I'm through the woods now, but it would be helpful to have an explanation of why the id_token does not provide the audience as requested (rather than the client_id).

**Comment by frederikprijck** [comment]
Our SDK only uses code flow, so not sure what you were testing initially that lead to this issue, but both ways should still give u an access token with the correct audience, assuming you set it correctly.

The id token is only for the consuming application to tell it who you are, which is the angular app, identified by the client id. You should never pass it to API's, so it should only be consumed by the application with the client id (hence the client id audience).

Access tokens are to give access to API's, more specifically it gives u access to the api based on the audience. So you should only consume it in the api with the specific audience.

More info: https://auth0.com/docs/secure/tokens
