### ISSUE TITLE
Add support to update user metadata ( like auth0.js patchUserMetadata() )

### ISSUE THREAD

**Issue by felixfiskare** [auth0/auth0-angular#115]
### Describe the problem you'd like to have solved

I want my users to be able to update some information about themselves (their user_metadata) via an angular app ( for example: firstname and lastname). Currently I'm not aware of a possibility to do this with auth0-angular.

### Describe the ideal solution

auth0.js offers patchUserMetadata() to patch the user metadata. It would be grand if auth0-angular could offer a similar function.

## Alternatives and current work-arounds

My current workaround is to create a separate endpoint on my backend service which accepts the user_metadata and forwards it to auth0

**Comment by frederikprijck** [comment]
Hi @felixfiskare, 

The Angular SDK is a tin wrapper around our SPA JS SDK (https://github.com/auth0/auth0-spa-js).
Calls to update user information are not supported in SPA clients as mentioned here https://github.com/auth0/auth0-spa-js/issues/115#issuecomment-515663814 and here https://community.auth0.com/t/end-users-ability-to-update-profile/47022.
You can also find this question in the FAQ on the Auth0 Community: https://community.auth0.com/t/how-can-i-enable-users-to-change-their-email-address-from-a-spa-or-native-app/44064

As mentioned on those links, you should update that metadata through your backend the way you are already doing.

**Comment by felixfiskare** [comment]
Thank you for the quick response. I will use the backend then.
