### ISSUE TITLE
getAccessTokenSilently is not pickig up config changes via authClientConfig.set()

### ISSUE THREAD

**Issue by felixfiskare** [auth0/auth0-angular#117]
### Describe the problem

`getAccessTokenSilently` ignores auth0Config changes via `authClientConfig.set()`.
Consider this small code snippet:
Line 1-3 sets a changed auth0Config via `authClientConfig.set()`.
Line 4 requests a new token.

```
const auth0Config = this.authClientConfig.get();
auth0Config.scope += 'someNewScope';
this.authClientConfig.set(auth0Config);
return this.authService.getAccessTokenSilently()
```

### What was the expected behavior?
I would expect `getAccessTokenSilenty` to get a new token from auth0 using the changed scopes.
Instead it returns the cached token (no network calls shown in the browser network tab).

I used `getAccessTokenSilently({ignoreCache: true})` as a workaround.
Now a new token is requested, but with the old scopes.

Only `getAccessTokenSilently({ignoreCache: true, scope: auth0Config.scope})` makes a network call using the correct scopes.

I'm not sure, if the old scopes will be used again once I call `getAccessTokenSilently` without any arguments.

### Environment

- **Version of `auth0-angular` used:** 1.3.2
- **Which browsers have you tested in?** User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
- **Which version of Angular have you tested with?** 10.2

**Comment by frederikprijck** [comment]
Hey,

Thanks for reporting. Even though I can understand the confusion, it looks like it's working as expected.
The configuration is used to instantiate the underlying Auth0Client, part of our `Auth0-SPA-JS` SDK.

That underlying SDK works in the same fashion where it allows you to provide global options, passed to the constructor when creating an instance of Auth0Client as well as passing explicit configuration to ` getTokenSilently`. That same underlying SDK doesn't expect for you to be changing the global configuration after creating an instance of Auth0Client.

I understand that the API provided in our Angular SDK makes you feel like it is supported to change configuration.

I am going to keep this one open to see if there is anything we can do here to prevent this confusion, most probably a documentation change. That way we can explicitly inform people that this isn't supposed to be changed. Our SDK supports sending different scopes or parameters compared to the global config, but as you mentioned these need to be passed to the corresponding methods (loginWithRedirect, getAccessTokenSilently, ...).

**Comment by felixfiskare** [comment]
Hey,

thank you for your quick replay.
I discovered something else: I'm using the above code to get a new access_token with different scopes. I thought this new token would be cached and used for subsequent requests. Unfortunately it looks like the old token is still used by the http interceptor. I guess this is "working as expected" as well?

**Comment by frederikprijck** [comment]
Hey @felixfiskare,

Yes this is expected, we cache the tokens based on a few combinations, including: `scope`, `audience` and `client_id`.
The interceptor uses the scopes and audience based on the httpInterceptor config, as mentioned in https://github.com/auth0/auth0-angular#call-an-api.

So take the following case, where u have this interceptor config:

```
AuthModule.forRoot({
  domain: 'YOUR_AUTH0_DOMAIN',
  clientId: 'YOUR_AUTH0_CLIENT_ID',
  redirectUri: window.location.origin,

  // The AuthHttpInterceptor configuration
  httpInterceptor: {
    allowedList: [
      '/api/test',
      {
        uri: '/api/orders',
        tokenOptions: {
          audience: 'http://my-api/',
          scope: 'read:orders',
        },
      },
    ],
  },
});
```

Now it is important to understand that any calls to `/api/test` uses the scope and audience configured globally. Any call to `/api/orders` uses a token that includes different scope and audience based on the configuration. Both of these tokens will be cached and used accordingly. However, as mentioned, at run time, there is no way to change the global scopes so there is no way for u to dynamically start changing the scopes used for the token sent to any of the above endpoints.

Even more so, If you would fetch a new token manually using new scopes like so:

```
getAccessTokenSilently({ scope: '123', audience: 'xyz'})
```

This will work fine and a new token is used and cached (we now have 3 tokens in the cache). But this token is unrelated to the tokens used above for the interceptor. and it will not replace any of the previous tokens nor will it impact/change the scope or audiences for them.

**Comment by felixfiskare** [comment]
Just a quick idea: Can I update the httpInterceptor.allowedList at runtime and change the scopes there? Would this result in a new token in subsequent requests?
From
```
{
        uri: '/api/orders',
        tokenOptions: {
          audience: 'http://my-api/',
          scope: 'read:orders tenant:4',
        }
```
To

```
{
        uri: '/api/orders',
        tokenOptions: {
          audience: 'http://my-api/',
          scope: 'read:orders tenant:1',
        }
```

**Comment by frederikprijck** [comment]
That should work, given that the interceptor is configured to get the config on every request: https://github.com/auth0/auth0-angular/blob/master/projects/auth0-angular/src/lib/auth.interceptor.ts#L33

However, I am interested to understand what you are trying to achieve that needs this.

**Comment by felixfiskare** [comment]
My backend has the following concept of roles:
A user always acts as a member of a tenant and only has roles in context of this tenant. For example there is no `read:orders` scope, but a `tenantID:read:orders` scope.
If a new user signs up (and this user has not been invited to a tenant already), then the user has no tenant. He either needs to be invited to an existing tenant or create a tenant for himself. In most cases I just reload the whole app if the tenant changes. Unfortunately I have a scenario where this would create some confusion for the user:

1. A non authenticated  user accesses our site and fills out a form to create a "request"
2. The user is redirected to auth0 and creates a new account
3. The user gets redirected to our application, but is not a member of any tenant
4. Now we want to auto-create a "request" using the data the user has already entered in step 1: To achieve this we need to:
    1. Create a new tenant
    2. Request a new access token with scopes in context of the newly created tenant
    3. Use the new access token to create the request in context of the newly created tenant
5. Show the user a success page


If I would reload the page after creating the new tenant the user would see a blank page (after the redirect from auth0), a loading page, a blank page again, a loading page again and then finally a success page. Therefore I try to change the scopes dynamically without a reload of the whole page.

**Comment by frederikprijck** [comment]
Interesting, Thanks for elaborating.

I am not sure what the blank page is about and I am wondering whether or not this could be a loading page aswell, making it less awkward.
That said, for complex systems it is not uncommon to go through a set of redirects before being authenticated (e.g. office web apps have a few redirects before you end up back at the app). Not saying this is the best experience, but its definetly not uncommon.

Currently, I do not see a way to change the global scopes, but you should be able to update the scopes used by the interceptor.
You will have to keep in mind that, in case you ever need to call getAccessTokenSilently yourself, that this will use the globally configured scopes unless you explicitly pass them to the getAccessTokenSilently.

A solution I see here for you is wrapping our AuthService to ensure you have your own getAccessTokenSilently that you can call without worrying about scopes, and internally pass all the scopes to our service:

```
@Injectable()
export class MyAuthService extends AuthService {
  constructor(
    @Inject(Auth0ClientService) auth0Client: Auth0Client,
    configFactory: AuthClientConfig,
    location: Location,
    navigator: AbstractNavigator
  ) {
    super(auth0Client, configFactory, location, navigator)
  }

  getAccessTokenSilently(opts: GetTokenSilentlyOptions) {
    // Here you can fetch scopes and pass them to super.getAccessTokenSilently()
    return super.getAccessTokenSilently();
  }
}
```

Ensure to add the above service to the providers array of the module that imports our AuthModule:

```
{ provide: AuthService, useClass: MyAuthService }
```

**Comment by frederikprijck** [comment]
Closing this issue, as it does work as expected but should allow you to change it based on the last comment.

If not, please continue the conversation and we can re-open as needed.
