### ISSUE TITLE
Post-login hook (before redirect callback)

### ISSUE THREAD

**Issue by mikaeldiener** [auth0/auth0-angular#118]
### Describe the problem you'd like to have solved

For cases where tasks have to be performed post-login and pre-redirect callback. Maybe call an API to update user meta data, or check for additional user rights. I´ve considered Auth0 Auth Pipelines such as hooks and rules, however, some cases cannot be resolved with these concepts, and you might want to have the code reside in your app. See questions/discussions like the one in this issue #53. 

It would be nice to be able to "inject code" that is supposed to be performed post-login and return a boolean before redirect callback is carried out. This might be added to any of the following functions in auth.service.ts: (checkSessionOrCallback, handleRedirectCallback, or shouldHandleCallback).

**Comment by frederikprijck** [comment]
Hey,

Could you provide a bit more context on the actual use case you are trying to solve with such a hook? This would allow us to understand the need for such a functionality and whether or not this would be something we think can be valuable or not.

Keep in kind that, prior to the redirectCallback being executed, there is no concept of a user so there is no way for you to update user metadata yet.

Login and HandleRedirect is a transaction, I am not sure I understand why there should be anything executed in between.

Thanks.

**Comment by mikaeldiener** [comment]
Hi,

Thanks for the quick response! Similar to @sean-hurley in #53, my entire app is secure, and need to perform an API call before redirect to consider the user to be "fully" authenticated.

In earlier versions of this app, I used auth0-lock and added an event handler to the "authenticated" event, where I performed an API call where (based on email) I fetched some info from my database, through the Auth0 Management API updated the appropriate user metadata. Thereafter I refreshed the access token silently and then made the redirect. 

I much appreciate your auth0-spa-js wrapper lib, and would like to use its full potential.

**Comment by frederikprijck** [comment]
> my entire app is secure, and need to perform an API call before redirect to consider the user to be "fully" authenticated.

This sound like something that is possible using an Auth0 rule, have you tried looking into it? Can you elaborate why you mentioned earlier that it wouldn't be possible using a rule?

> I fetched some info from my database, through the Auth0 Management API updated the appropriate user metadata. Thereafter I refreshed the access token silently and then made the redirect.

Using a rule I think you can avoid asking for a second token here but ensure the correct information is available in the first retrieved token.

There is also Actions, which is in Beta (https://auth0.com/blog/introducing-auth0-actions/), but sounds something I would look into as well.

> I much appreciate your auth0-spa-js wrapper lib, and would like to use its full potential.

I can see that this is possible in our SPA-JS SDK. I will give this some extra thought from the Angular SDK side as well.

**Comment by mikaeldiener** [comment]
@frederikprijck You are absolutely right! Actually, I used Auth0 rules as a first alternative before the case described above which worked well in some cases. However, it didn't work during development (localhost), since the API resides locally. Furthermore, I would like to have as much "business logic" in my repository/app as I can.

> I can see that this is possible in our SPA-JS SDK. I will give this some extra thought from the Angular SDK side as well.

Much appreciated!

**Comment by mikaeldiener** [comment]
Excuse my precipitation! Is there any progress on this issue?

**Comment by frederikprijck** [comment]
Hi @mikaeldiener ,

I am still not entirely sure I understand your use-case.
You are saying you want to execute an API call **after** coming back to your application but **before** calling `handleRedirectCallback` internally?

I am still not sure I see what such a hook would give you. As I mentioned earlier, the SDK needs to execute `handleRedirectCallback ` **before it has any knowledge of a user.** The SDK or application has no idea who has authenticated before that call has finished.

> Thanks for the quick response! Similar to @sean-hurley in #53, my entire app is secure, and need to perform an API call before redirect to consider the user to be "fully" authenticated.

What you said here wouldnt work with the proposed hook. As you have no notion of a user before calling `handleRedirectCallback`.

If you need to do anything with the user, such as calling an API, it needs to happen **after** handleRedirectCallback was called.
To do that, u should be able to use any of the following observables as a trigger for that:

`isLoading$.pipe(filter(isLoading => !isLoading))`,  `isAuthenticated$.pipe(filter(isAuthenticated=> !!isAuthenticated))` or  `user$.pipe(filter(user=> !!user))`

For example:

```
this.authService.user$.pipe(
  filter(user=> !!user),
  take(1),
  mergeMap((user) => this.doYourCallThatNeedsTheUser(user)),
  mergeMap(() => this.authService.getAccessTokenSilently({ignoreCache: true}))
)
```

However, I still think it makes more sense to keep it in an Auth0 rule or action, as that would avoid the extra call to get a new token.

Just to clarify something I said earlier:

> I can see that this is possible in our SPA-JS SDK. I will give this some extra thought from the Angular SDK side as well.

Even tho the SPA-JS SDK, technically, allows for you to execute code after coming back to your application and before calling `handleRedirectCallback`, the same problem exists there. Those two calls are part of a single transaction and should not be interrupted. Only when both calls where successful will the SDK know who the user is and will you be able to do any extra API calls for the user in question.

**Comment by mikaeldiener** [comment]
Hi @frederikprijck,

Thank you for your detailed answer!

I´ve been reading through your library and maybe I wasn´t exactly sure when and how I would like to "insert" a hook. I´ve forked the repo and after playing around with the AuthService it was clear that just before setting the isLoading to false was when I wanted to inject my code. However, with that knowledge, I created a wrapper for the AuthService similar to the approach you present above. It works as expected.

I use a similar approach for persisting "my authentication flag" as the SPA-JS SDK. Which will prevent the wrapper to run (doYourCallThatNeedsTheUser) multiple times.

One question, I need my wrapper to be in sync with the AuthService and clear or renew "my authentication flag" (a cookie) when AuthService goes "unauthenticated", do you have a suggestion for how to include that in your solution presented above?

Once again, many thanks for the detailed answers and help!

**Comment by frederikprijck** [comment]
Hey @mikaeldiener ,

I guess it is a bit hard to help without seeing the actual service you are using.
The code I added here (https://github.com/auth0/auth0-angular/issues/118#issuecomment-781922125), isn't necessarily intended to be used in a wrapper around our AuthService.

I think the general idea is to ensure you build your observables on top of our SDK's observables.

> I need my wrapper to be in sync with the AuthService and clear or renew "my authentication flag" (a cookie) when AuthService goes "unauthenticated"

What do you mean by `when the AuthService goes "unauthenticated"`? 

In general, when you call the SDK's `getAccessTokenSilently` method, it will throw an error if the user does not have a valid session with Auth0 (in case you are not using Refresh Tokens) or if the Refresh Token is expired. You should catch these errors and react accordingly (see https://github.com/auth0/auth0-angular, section `Handling errors`.

**Comment by frederikprijck** [comment]
Closing this, but feel free to continue the conversation. We can always re-open if there would be any need for it.
