### ISSUE TITLE
Dynamic Configuration injection fails startup.

### ISSUE THREAD

**Issue by badgerowluke** [auth0/auth0-angular#119]
### Describe the problem

following the documentation on dynamically loading configuration causes error on startup.  "Configuration must be specified either through AuthModule.forRoot or through AuthClientConfig.set.

I'm sure there's something I'm just not seeing in the docs, but....

attempting to inject AuthService from @auth0/auth0-angular into an Injectable class causes the bootstrapped to fail

### What was the expected behavior?

the application to bootstrap and run

### Reproduction

1. copy the configInitializer function from the Dynamic Configuration section of the package description page [here](https://www.npmjs.com/package/@auth0/auth0-angular#dynamic-configuration)
```
export function configInitializer(
  http: HttpClient,
  config: AuthClientConfig
) {
  return () =>
  http
  .get('assets/config/config.json')
  .toPromise()
  .then((loadedConfig: AuthConfig) => {
    config.set(loadedConfig)
  });  
}
```
2. remove the static clientId and domain values from environment.ts
```
AuthModule.forRoot(),
```
3. add the APP_INITIALIZER, again from the documentation
```
    {
      provide: APP_INITIALIZER,
      useFactory: configInitializer, 
      deps: [HttpClient, AuthClientConfig],
      multi: true,
    },
```
4. `ng build && ng serve`
5. navigate to localhost:4200
6. open dev tools
7. view console error (chrome puts the error @ auth0-auth0-angular.js:18)

### Environment

- **Version of `auth0-angular` used:** 1.3.2
- **Which browsers have you tested in?** 14.0.3, chrome 88.0, FF Dev 86.0b9
- **Which version of Angular have you tested with?** 11
- **Other modules/plugins/libraries that might be involved:** NA

**Comment by frederikprijck** [comment]
Hey,

The problem here is that `configInitializer` is using `HttpClient`. Using `HttpClient` will trigger the Interceptors, including our interceptor. Our interceptor will try to decide if it should add a token to that specific request or not. However, as this is all being done before the config has been fetched (because the request in question here is the request to actually fetch the config), the SDK is throwing an error about missing configuration. 

See my comment here: https://github.com/auth0/auth0-angular/issues/82#issuecomment-724692494

In general, this is not something we can do much about other than ensuring the interceptor is skipped for this specific request.
However, we think that this is a responsibility that should exist outside of the SDK. Whenever our Interceptor is being used without any configuration, we want to throw an error. It's up to the user to ensure the interceptor isn't used prior to setting the configuration in case of Dynamic Configuration.

**Comment by badgerowluke** [comment]
So I've removed the HttpClient Dependency, and am using fetch in the platform bootstrap as below, I'm executing my APP_INITIALIZER  _before_  the AuthModule errors out now.  But it doesn't appear that the result has changed.
```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule, BootstrapConfig } from './app/app.module';

import { environment } from './environments/environment';
fetch('assets/config/config.json')
.then((response) => response.json())
.then(config => {

  if (environment.production) {
    enableProdMode();
  }
  
  platformBrowserDynamic([{provide: BootstrapConfig, useValue: config}])
  .bootstrapModule(AppModule)
    .catch(err => console.error(err));
  
})


```

```
export function initAuth(config: BootstrapConfig, authConfig: AuthClientConfig) {
  console.log(config)

  return () => authConfig.set(<AuthConfig>{clientId: config.clientId, domain:config.domain})
}
```

so I guess my real question is actually if I chuck the angular package and I just use the spa-js package (which is a dependency anyway) do I get a more delayed initialization timing that lets me pull my configuration from an external source?

**Comment by frederikprijck** [comment]
Have you been able to give a look at this comment?
https://github.com/auth0/auth0-angular/issues/70#issuecomment-715225756

This shows an example of how others have done it and that should be working fine. You could also use fetch instead in that service if you want to, but you can also stick to HttpClient in the way that user did it in such a way that it bypasses interceptors.

> so I guess my real question is actually if I chuck the angular package and I just use the spa-js package (which is a dependency anyway) do I get a more delayed initialization timing that lets me pull my configuration from an external source?

I am not sure what you are asking. What you are asking in terms of dynamic configuration using a json file should all be possible using the Angular package using the example mentioned in the link.

In your case, I think you want this:

```
export function configInitializer(
  handler: HttpBackend,
  config: AuthClientConfig
) {
  return () =>{
     const http = new HttpClient(handler);
     return http
       .get('assets/config/config.json')
       .toPromise()
       .then((loadedConfig: AuthConfig) => {
         config.set(loadedConfig)
       });  
    };
}
```

If you don't get it working, I am happy to look at a small example application and fix it for you if you want.

**Comment by badgerowluke** [comment]
yeah.  I was digging through that first thing this morning.  I'm trying to avoid spinning up another app off of the CLI.  I had been using auth0-js 9.8.2 prior to upgrading to angular 11 and migrating the codebase to GH.  If I flail with it for more than the rest of the day I'll post up a demo app.

**Comment by frederikprijck** [comment]
Hey @badgerowluke I also opened a PR to update our playground application to show how u can use a JSON file:  https://github.com/auth0/auth0-angular/pull/121

**Comment by badgerowluke** [comment]
spectacular @frederikprijck ! Thanks for the help.  I got mine running yesterday afternoon

**Comment by frederikprijck** [comment]
Great, glad you got it working!

**Comment by denys-aponiuk** [comment]
Hello @frederikprijck 
The same error started appearing when I injected AuthService into the service which is a dependency of an app_initializer factory where the setting dynamic configuration is happening. 
My question is can I inject AuthService in such a described way?
