### ISSUE TITLE
gulp uglifying breaks both minified and non-minified libs

### ISSUE THREAD

**Issue by frankhock** [auth0/auth0-angular#121]
bug depends on mangle option in uglify

here is a gist showing gulp task: https://gist.github.com/frankhock/5e1e75be7afae03d693b

**Comment by mgonto** [comment]
This is related to Lock's bug. 

Just linked the issues.

Thanks for the report.

**Comment by mgonto** [comment]
Please read the response from https://github.com/auth0/lock/issues/94#issuecomment-68895137

We're working on a solution

**Comment by mgonto** [comment]
it has been fixed with version `4.0.1` of `auth0-angular` :).
