### ISSUE TITLE
Provide a TypeScript definition file for auth0-angular

### ISSUE THREAD

**Issue by drub0y** [auth0/auth0-angular#123]
We are attempting to bring auth0-angular into a TypeScript based project and not finding a .d.ts file anywhere for it. I suppose we will have to create one ourselves, but it would be nice if one was officially published by Auth0 as part of the library itself.

If we end up creating one we will publish it to [the "official" DefinitelyTyped repository](https://github.com/borisyankov/DefinitelyTyped).

**Comment by mgonto** [comment]
@drub0y hey, we don't have a Typescript file yet for `auth0-angular`. If you end up creating one, please do let us know and we'll point to the file on the `DefinetlyTyped` repo from here saying thanks to you :).

I know there's a TypeScript definition for Lock already.

Thanks

**Comment by drub0y** [comment]
Yes, we found the Auth0-lock definition, but doesn't help auth0-angular. Bummer. :(

We'll take the time to do it ourselves I guess...

**Comment by mgonto** [comment]
@drub0y we'll try to work on this. I've taken a note but I can't promise any timeframe yet :( sorry!

**Comment by drub0y** [comment]
I understand. We'll probably need it before you can get to it, so we'll get started and you can hopefully take it from there. We likely won't end up exposing the whole API surface, but at least we can get something out there and it'll grow from there if OSS works the way it should, right? ;)

**Comment by mgonto** [comment]
hahahah sounds good :). We can support it once you get it started and we'll get other contributions as well as you're saying :). We've been getting a lot of them :). Of course, we'll add you as a contributor and maybe some swag ;) ahahaha

**Comment by homesar** [comment]
I've submitted PR DefinitelyTyped/DefinitelyTyped#7870 for this!

**Comment by homesar** [comment]
The PR was approved so you can close this issue now

**Comment by christiannwamba** [comment]
Yeah jus checked it out. Thanks @homesar and apologies for the delay
