### ISSUE TITLE
readme.md needs more detailed explanations 

### ISSUE THREAD

**Issue by adriatic** [auth0/auth0-angular#124]
I got completely confused looking at the SSO sample, failing to realize that this is not a complete code (otherwise, one would need at least two different applications, right?) Only after a chat with Rodrigo who told me `the idea is not to have a full example of various applications, but only to show the usage of “sso: true” in authProvider ` I decided that I am not a dummy :)

In short, it wouldn't hurt if this was clearly stated, particularly since the instructions include the explanations on how to run this sample - which as we already agreed makes no sense

**Comment by mgonto** [comment]
Hey @adriatic,

You're right, the SSO readme isn't entirely clear. I've just updated it to make it clear how you can test it out and how it works :).

https://github.com/auth0/auth0-angular/blob/master/examples/sso/README.md

Let me know if you think it's clearer now.

Thanks!

**Comment by adriatic** [comment]
That is a completely different story and it makes all the sense in the world. Thanks Martin for such speedy reaction. 

If all my wishes could be made real, I would really like to see one additional branch in the documentation for this whole set of examples that show how run them on IIS/ASP.NET hosted angular apps. I might be able to provide that information if it becomes viewed as important for Auth0

**Comment by mgonto** [comment]
> That is a completely different story and it makes all the sense in the world. Thanks Martin for such speedy reaction.

Thanks :D. We try to do this as much as we can.

> If all my wishes could be made real, I would really like to see one additional branch in the documentation for this whole set of examples that show how run them on IIS/ASP.NET hosted angular apps. I might be able to provide that information if it becomes viewed as important for Auth0

It shouldn't be that different to host this with IIS or ASP.Net. AngularJS as you know is just serving some static files, so you could easily serve them from the public directory from your ASP .Net app or from any public directory from IIS. Do you mean that or what exactly do you mean?

Thanks for the feeback :)

**Comment by adriatic** [comment]
It is not something I have difficulty doing (and am already doing it) – I was more looking at making your documentation a bit less node.js “heavy”. Use the example at https://auth0.com/docs/rules where I found

Create authorization rules based on complex logic (anything that can be written with node.js).

Does this imply that the rules are possible only when the app is nodejs hosted? I hope not, but I would like to see that states specifically with an angular sample – in your collection, in other words

**Comment by mgonto** [comment]
> It is not something I have difficulty doing (and am already doing it) – I was more looking at making your documentation a bit less node.js “heavy”. Use the example at https://auth0.com/docs/rules where I found
> 
> Create authorization rules based on complex logic (anything that can be written with node.js).
> 
> Does this imply that the rules are possible only when the app is nodejs hosted? I hope not, but I would like to see that states specifically with an angular sample – in your collection, in other words

Thanks for the feedback. I now understand what you mean. It's true a lot of our docs is NodeJS centric and that it should be platform agnostic. I'll add an issue to our docs and discuss it internally to make our docs even better :). 

Thanks again!

**Comment by adriatic** [comment]
**Final comment**: I invited Martin to my LinkedIn page to share my resume, which should confirm that my claim of having proper experience to help a lot in sharing ideas about Auth0 docs improvement has merit :)
