### ISSUE TITLE
Overall readme for this project bugs

### ISSUE THREAD

**Issue by adriatic** [auth0/auth0-angular#126]
1. Section at anchor <https://github.com/auth0/auth0-angular/blob/master/README.md#tutorials--examples>: has typo (Clcik here)
2. That same  link <https://github.com/auth0/auth0-angular/blob/master/docs/widget-popup.md> is bad.
3. Section at anchor <https://github.com/auth0/auth0-angular/blob/master/README.md#dependencies> has a typo:
![image](https://cloud.githubusercontent.com/assets/2712405/5692371/17f8bbe4-98c1-11e4-8d20-1ac6b435259f.png)

**Comment by christiannwamba** [comment]
Thanks @adriatic
