### ISSUE TITLE
Question on Auth0Lock widget creation 

### ISSUE THREAD

**Issue by adriatic** [auth0/auth0-angular#127]
The [widget sample](https://github.com/auth0/auth0-angular/tree/master/examples/widget) clearly uses the Lock widget - but it is not obvious how is that widget instantiated and what are its default values.

I checked [this document](https://github.com/auth0/lock/wiki/Auth0Lock-customization) and did not get much smarter as the [widget sample](https://github.com/auth0/auth0-angular/tree/master/examples/widget) does not instantiate the lock, so I cannot define its options

I am guessing that I got confused with two different lock widgets, but cannot find the data on the difference between them. So, it seems that more information would be desired.

**Comment by christiannwamba** [comment]
`Lock` is instantiated inside of the SDK so you don't have to worry about that. You can just configure with `authProvider` and use the API methods in your app.

**Comment by adriatic** [comment]
This issue was open for 17 months - since then I even forgot what Angular is :-)
