### ISSUE TITLE
Section of the readme.md needs more clarifications

### ISSUE THREAD

**Issue by adriatic** [auth0/auth0-angular#128]
It is [this section](https://github.com/auth0/auth0-angular/blob/master/README.md#preface-authentication-modes), the last two sentences:

```The third mode is just doing a CORS call to /ro to authenticate the user. This is only used for Database-Password connections. In this case, the website will not refresh either.```

that would benefit a lot from more explanations / references to more information. What is ` CORS call to /ro` and how does that authenticate the user??

**Please note** that I am offering you the benefit of knowing very little about your product (still), so I am trying to point to all rough spots for a novice

**Comment by IvanRave** [comment]
API Explorer | Authentication API
---

https://auth0.com/docs/auth-api

**Comment by Annyv2** [comment]
This was fixed
