### ISSUE TITLE
Enforced redirection to the homepage due to appState.target

### ISSUE THREAD

**Issue by faan11** [auth0/auth0-angular#129]
### Describe the problem you'd like to have solved
I'd like to remove the default behavior of redirection after callback.
Two are the reasons:
1- The application may need an intermediate page due to reset password ( https://auth0.com/docs/rules/redirect-users ), which means that at that time, the user is not logged.
2- I think the callback is enough to redirect the user in the right page. Why introduce another redirection?
I spent a lot of my precious time due to this issue because it wasn't written anywhere in the documentation ( and i think that i'm not the only one ). I didn't understand why it was redirecting the application back to my home page.

### Describe the ideal solution

In my opinion, the best solution is to leave this feature only if the developer specifies the app.target property. No redirection, if the property is not specified.  
I also recommend to write down this feature in the README.

**Comment by frederikprijck** [comment]
Hi @faan11 ,

Sorry for the frustration this might have caused.
For that same reason, we recently updated the FAQ to document this behavior: https://github.com/auth0/auth0-angular/blob/master/FAQ.md.

The main reason we are redirecting again is to ensure the `code` and `state` are cleared from the URL query params.

In this case, if u want to stay on the so-called `callback` path, you should be able to use a configuration where `redirectUri` and `appState.target` point to the same path:

```
AuthModule.forRoot({
  redirectUri: window.location.origin + '/callback'
}),
```

When u call `loginWithRedirect`, you need to ensure you pass the same path as `appState.target`:

```
this.auth.loginWithRedirect({
  appState: {
    target: '/callback'
  }
});
```

This should still trigger an actual redirect, but the user will stay on the same path.

Would this help in your situation?

**Comment by faan11** [comment]
Thank you for your solution, documentation and clear explanation.

Is this solution valid when the authentication is paused, which means that the page needs to call the /continue api?
The user callback will be something like: "https://example.com/foo?state=abc123" (  https://auth0.com/docs/rules/redirect-users ). Does the callback redirect to / in that situation?

**Comment by frederikprijck** [comment]
Hey @faan11,

Sorry about that, I misunderstood your requirement.
I did some digging and this isn't something this SDK supports yet.

We will be having some conversations internally to see how we can make a few changes that would allow you to do something like that as well as some guidance around how this can eventually be achieved.

**Comment by frederikprijck** [comment]
@faan11 After playing around with the SDK in an Angular app I am unable to reproduce what you are saying. I tried the following:

- I have a route setup, called: `test`
- I have a rule setup in Auth that has the following code:
```
function (user, context, callback) {
  context.redirect = {
    url: "http://localhost:4200/test"
  };
  return callback(null, user, context);
}
```
- I open my application and click login
- I end up at the Auth0 domain, prompting for credentials
- After entering credentials, I end up at `http://localhost:4200/test?state=123` and I stay there.

I haven't really configured anything special, you can also entirely ignore my comment here https://github.com/auth0/auth0-angular/issues/129#issuecomment-795965554.

Could you provide some steps, or idealy a reproduction on what you are doing so we can see how we can get that working?

Thanks

**Comment by faan11** [comment]
I also tested this in my project,  and it does not redirect to the appState.target field.

Thank you for your time
