### ISSUE TITLE
getToken returns an object

### ISSUE THREAD

**Issue by kpgarrod** [auth0/auth0-angular#130]
Hey Gonto,
 
   auth.getToken({
      api: 'firebase'
    })
used to (v3) return an id_token. It now returns an object with anid_token as an attribute. Is this intentional? I didn't see any mention in the release notes.

Best,

Keith

**Comment by mgonto** [comment]
Hey,

Yes, that's intentional. You just need to get the property `id_token` from the object returned.

It's in the Releases Notes for v4.0.0 (This was the breaking change to do a major version)

![Releases notes](http://d.pr/i/1lhRe+)

**Comment by kpgarrod** [comment]
Thanks. Sorry I missed that!

On 16 January 2015 at 15:55, Martin Gontovnikas <notifications@github.com>
wrote:

> Closed #130 <https://github.com/auth0/auth0-angular/issues/130>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/auth0/auth0-angular/issues/130#event-220077572>.
>



-- 
Keith Garrod

Tel: +27-83-3000-988
Fax: +27-86-5757781

**Comment by mgonto** [comment]
No problem :). 


Cheers! 


— Mobile mail. Excuse for brevity and typos.
