### ISSUE TITLE
Custom auth example gives 401 for valid user / pass combination

### ISSUE THREAD

**Issue by calvinfroedge** [auth0/auth0-angular#131]
Using Auth0 custom example with this config:

  authProvider.init({
    domain: 'calvin.auth0.com',
    clientID: 'AY5RGFKJwOgiDgbICt6c8EDPBhK3dTcd',
    loginUrl: '/login'
  });

Serving the custom-login example on port 3001 with serve.

I get a 401 error. When I use the tester (https://manage.auth0.com/tester) I get a success.

**Comment by calvinfroedge** [comment]
In case anyone else runs into this issue, while it gave a 401 and made me believe the username and password were not valid, it was actually a CORS issue. You can go into the app settings for your Auth0 app and add the URL you are testing from as a valid callback and CORS url.

**Comment by mgonto** [comment]
@calvinfroedge :) awesome :). I'm glad you fixed it by yourself.
