### ISSUE TITLE
Custom login vs widget login, password forgot / reset process

### ISSUE THREAD

**Issue by calvinfroedge** [auth0/auth0-angular#132]
Hi,

I've spent a few hours exploring Auth0 and for the most part have it incorporated into an app I'm working on. We were using a different authentication provider before, and had customized our login process to be integrated into the look / feel of our site. We think we'd like to keep that.

I already have the custom login and logout working, and was just coming around to the password reset. My understanding of the widget login is that Auth0 handles the password update email, wherein the user receives a link he clicks and is redirected to change their password.

When implementing the password reset ourselves, the only method I see in the Auth0 client is to reset a password. This takes a username and password as an argument, so my assumption for this is that it's for a user which is already authenticated.

Using the customized login, the normal flow is:

1) User enters email
2) User gets verification link which he clicks
3) User updates password
4) User is logged in to app

I can see that password update is covered here: https://github.com/auth0/auth0-angular/blob/master/examples/custom-login/scripts/auth0-angular.js#L391 and here: https://github.com/auth0/auth0-angular/blob/master/examples/custom-login/scripts/controllers.js#L42

...But how do I handle the flow for sending the verification link and providing a token he can use for the reset? My guess is that our server needs to handle the emailing and setting a token for the user, and that we need to make a few API calls. Can you please clearly outline this process for me? Thanks!

**Comment by calvinfroedge** [comment]
Apparently I did not RTFM. I just noticed this in the documentation:

```
auth.reset(options[, successCallback, errorCallback])
```
This will perform the "Forgot your password" flow. If you're using auth0.js it will send the email to confirm the password change. See the documentation here If you're using auth0-lock.js, it will open the widget in the reset password mode. It can receive in that case the same parameters as the signin method.

This method receives 2 extra parameters to handle the success and failure callbacks similar to signin.

https://github.com/auth0/auth0-angular/blob/master/README.md

So, it appears as if the intent is to have the user enter email and password, and requires confirmation.

**Comment by broyeztony** [comment]
Hello,

I have a more specific question. Feel free to move this post to the 
appropriate thread if needed.

My question is: Can we (and how) customize the change-password-widget-container component in the Hosted Pages > Password Reset template. ?

Thanks,

**Comment by saurabhgangarde** [comment]
Any answer or updates on questions above ?
