### ISSUE TITLE
Authentication using cypress

### ISSUE THREAD

**Issue by riscie** [auth0/auth0-angular#133]
### Describe the problem you'd like to have solved

I would like to use cypress (cspress.io) to authenticate against auth0-angular.

### Describe the ideal 

This blogpost exists which describes how to use cypress to authenticate against auth0 https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0/#Cypress. But the post is not using auth0-angular. We recently migrated over from auth0-spa-js to auth0-angular but now we need a way for our integration tests to login into the app. Can you provide information on how to adapt the code in the blog post for it to work again?

It seems the callback URL is diffrent then before (using a `code` payload instead of the token itself).

**Comment by frederikprijck** [comment]
Hey,

As this SDK uses SPA-JS under the hood, it shouldn't be very different as to how it was done using SPA-JS.
Same goes for our React SDK, could u see if this thread helps u https://github.com/auth0/auth0-react/issues/199 ? Especially the example here https://github.com/auth0/auth0-react/issues/199#issuecomment-779708979 ?

> It seems the callback URL is diffrent then before (using a code payload instead of the token itself).

SPA-JS shouldn't be using a `token` in the URL, that SDK does not support that. Are you sure you are talking about `auth0-spa-js` and not `auth0.js` ?

**Comment by riscie** [comment]
Hi @frederikprijck 
Thanks for your answer. You are right, we moved from auth0.js to auth0-angular, not from auth0-spa-js.
I was able to get it running using the approach mentioned here: https://github.com/auth0/auth0-spa-js/issues/210#issuecomment-727557021

As far as I could see, it's similar to what you linked.

Thank you.

By the way: I think the blog post linked in my initial post should  be updated. It took me some time to understand that auth0-angular was using auth-spa-js under the hood. And then some more time to dig trough issues on auth0-spa-js to find a solution. It would surely help others because the blog post is still very higly ranked on google searches targeting how to test auth0 apps with cypress.

**Comment by frederikprijck** [comment]
Glad you got it working.

The blog post you linked uses Auth0-js. Even tho not recommended for SPA applications, it is still a library that is widely used for other things so I am not sure it's wrong, just not accurate for your use-case. 

Here is an article of one of our architects regarding using SPA JS: https://sandrino.dev/blog/writing-cypress-e2e-tests-with-auth0

**Comment by riscie** [comment]
I see your point, but the title "End-to-End Testing with Cypress and Auth0" suggests that the reader will learn how to get cypress working against auth0. 
Most of your users may not know that there exist 3 diffrent auth0 libraries, and that one of those three has another one as a dependency. And that the article is only valid for the third of those three.
I am really not trying to be snarky here, I just want to give the view of where I came from, before I did a lot of research and digging trough github issues. 

Maybe just add a lead-in where you give an overview over your libraries (auth0.js, auth0-spa-js, auth0-angular, ...?) and then make it clear to the reader that everything that follows is only valid for auth0.js. You could also link to the sandrino.dev article of course.

**Comment by frederikprijck** [comment]
I will pass the information to the appropriate team, thanks :)

**Comment by riscie** [comment]
Also thanks to you for the help.
