### ISSUE TITLE
Extend ng-add to automate registering the  AuthModule.forRoot

### ISSUE THREAD

**Issue by santoshyadavdev** [auth0/auth0-angular#134]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Currently ng-add only installs the library and we need to add  AuthModule.forRoot manually, we can automate that too with ng-ad.

### Describe the ideal solution

We provide promote so user can provide below values while running ng-add 
   domain: 'YOUR_AUTH0_DOMAIN',
   clientId: 'YOUR_AUTH0_CLIENT_ID',

once provided, ng-add will below code
    AuthModule.forRoot({
      domain: 'YOUR_AUTH0_DOMAIN',
      clientId: 'YOUR_AUTH0_CLIENT_ID',
    }),

## Alternatives and current work-arounds

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

### Additional context

I am interested in doing this change, let me know, would be happy to open the PR.

**Comment by frederikprijck** [comment]
Thanks for the request, I believe this can be a good addition but I think we also need to remember that a lot of people use dynamic configuration and will not have any of those values available and neither should they go in the `forRoot`.

To guarantee a good DX for both of the users (those with and without dynamic configuration), I think we should at least ensure they are asked whether or not they want to use dynamic configuration.

However, this opens up the question if ng-add should also add dynamic configuration support? This might get a bit more complicated, but worth considering.

What do you think @santoshyadavdev ?

**Comment by santoshyadavdev** [comment]
Yeah, makes sense. If we can get feedback on how they are getting the values, I think probably they might be using APP_INTIALIZERS but if we get some actual use case, we can do that.

**Comment by frederikprijck** [comment]
We have a recommendation on how to do this, I believe we can use the same approach as we recommend, see `Dynamic Configuration` at https://github.com/auth0/auth0-angular

**Comment by santoshyadavdev** [comment]
Awesome, I will start working on it 😊

**Comment by frederikprijck** [comment]
Closing this, happy to reopen if anyone wants to pick up this work.
