### ISSUE TITLE
Infinite redirect with SSO in AD

### ISSUE THREAD

**Issue by adrianchia** [auth0/auth0-angular#134]
auth0-angular sso example keep redirect when application is using AD connection only with kerberos mode on.
```javascript
authProvider.init({
    domain: AUTH0_DOMAIN,
    clientID: AUTH0_CLIENT_ID,
    loginUrl: '/login',
    sso: true
  });

  authProvider.on('loginSuccess', function($location, profilePromise, idToken, store){
    console.log("Login Success");
    
    profilePromise.then(function(profile){
      store.set('profile', profile);
      store.set('token', idToken);
    });
    $location.path('/');
  });
```

**Comment by adrianchia** [comment]
This happens when Auth0-Lock is used instead of Auth0.js.

**Comment by tehfedaykin** [comment]
I'm having this issue as well not using Auth0-Lock.

**Comment by christiannwamba** [comment]
Hi @adrianchia 

Any updates on this issue? Are you still experiencing the redirects with the latest version of the SDK?

**Comment by christiannwamba** [comment]
Hi

As there is no feedback on issue, I will close it out but please re-open if need be. Thanks
