### ISSUE TITLE
Bad link in https://github.com/auth0/auth0-angular/tree/master/examples readme.md file

### ISSUE THREAD

**Issue by adriatic** [auth0/auth0-angular#136]
![bad link](https://cloud.githubusercontent.com/assets/2712405/5989106/fca21b1c-a949-11e4-84a0-c7e09b0d9ff8.png)

I believe it should be https://github.com/auth0/auth0-angular/tree/master/examples/widget-with-api

**Comment by iannyanes** [comment]
Dup of #172 I suggest this ticket to be closed @ntotten
