### ISSUE TITLE
allowedUrls does not seem to behave as explained in the readme

### ISSUE THREAD

**Issue by dsebastien** [auth0/auth0-angular#137]
### Describe the problem

The readme examples for the allowedList configuration give the idea that it's possible to pass a partial path with a wildcard like `/api/*`, but in practice this doesn't seem to work. Apparently, the interceptor uses `startsWith` with everything prior to the wildcard character to check if the token should be added to the request: https://github.com/auth0/auth0-angular/blob/27adc166d5f6aeec9813042b9720368686198f53/projects/auth0-angular/src/lib/auth.interceptor.ts#L107

So the examples below don't work in practice at the moment:

```
allowedList: [
      ...

      // Attach access tokens to any calls that start with '/api/'
      '/api/*',

      // Match anything starting with /api/accounts, but also specify the audience and scope the attached
      // access token must have
      {
        uri: '/api/accounts/*',
        tokenOptions: {
          audience: 'http://my-api/',
          scope: 'read:accounts',
        },
      },
```

### What was the expected behavior?

> Tell us about the behavior you expected to see

I expected the examples to match reality ;-)

It makes sense to be strict enough with the URL matching to avoid sending bearer tokens all over the internet though ;-)

**Comment by frederikprijck** [comment]
I guess this is more of a docs issue as it is a bug in the SDK.
I believe the behavior makes sense, if you start with specifying `api/*` followed by `api/accounts`, it makes sense that the configuration for `api/*` will also be used for `api/accounts`. This is the same way most routers work, it uses the first one that matches, and `api/accounts` matches `api/*`.

In the above example, the following should work as expected:
```
allowedList: [
      // Match anything starting with /api/accounts, but also specify the audience and scope the attached
      // access token must have
      {
        uri: '/api/accounts/*',
        tokenOptions: {
          audience: 'http://my-api/',
          scope: 'read:accounts',
        },
      }, 
      // Attach access tokens to any calls that start with '/api/'
      '/api/*',
      
```
Let me know if this doesn't help.

I will get our docs updated, thanks for reporting!

**Comment by dsebastien** [comment]
Agreed, it's not a bug per se, just a doc issue. By reading the docs, I was under the impression that the following `allowedList` would attach the token in the following cases:

```
allowedList: [ "/api/*" ]
```

Request URLs:
* http://localhost:8080/api/v1/foo
* http://127.0.0.1:8080/api/v1/bar
* https://app.whatever/api/v1/foobar

But in practice, it seems that the only way to match all the above is to use an allowedList list such as:

```
allowedList: [
  "http://localhost:8080/api/v1/*",
  "http://127.0.0.1:8080/api/v1/*",
  "https://app.whatever/api/v1/*",
],
```

Thus use the full URL. A bit of testing seemed to confirm that too. Am I missing something?
From what I understood, if a `*` is used in an entry of the allowedList, then the request URL must start with the rest of the allowed list pattern: https://github.com/auth0/auth0-angular/blob/27adc166d5f6aeec9813042b9720368686198f53/projects/auth0-angular/src/lib/auth.interceptor.ts#L107, correct?

**Comment by frederikprijck** [comment]
It looks like this works as expected. As mentioned in both the readme and the [API docs](https://auth0.github.io/auth0-angular/interfaces/httpinterceptorrouteconfig.html), using wildcards results in a _start with_ check: https://auth0.github.io/auth0-angular/interfaces/httpinterceptorrouteconfig.html#uri

> `/api` - exactly match the route `/api` - `/api/*` - match any route that starts with `/api/`

The request URLs listed do not start with `/api/`, instead, they start with `http://localhost:8080/api/`, `http://127.0.0.1:8080/api/` and  `https://app.whatever/api/`. 

A configuration like `/api/*` should probably only be used when your APP and API run on the same domain and port, or if you are using a proxy. In all other cases, you are not calling `httpClient.get()` using `/api/v1/foo` neither, but by specifying `http://localhost:8080/api/v1/foo` when making those calls. The interceptor config should reflect the URLs used there (while allowing for suffix wildcards).

Note that we do not have support for wildcards as prefix: A path like `*/api/*` could match the request URLs but, as said, that's not supported.
