### ISSUE TITLE
Configuration option to automatically preserve query parameters in loginWithRedirect

### ISSUE THREAD

**Issue by tkutcher** [auth0/auth0-angular#143]
### Describe the problem you'd like to have solved

I would like to have a configuration option where calling `loginWithRedirect` in `AuthService` will preserve the query parameters in the current URL instead of just calling `redirectUri` (which is defaulted to the root).

Currently I do the following which works well, but it took me a while to figure out this is what I needed to do to correctly preserve them:

```ts
    this.base.loginWithRedirect({
      appState: {
        target: window.location.search
      }
    });
```

### Describe the ideal solution

The auth configuration object that gets configured from `forRoot()` has a `preserveInitialQueryString` boolean option, maybe even defaulted to true. If true then as the very last step, the original query parameters before the `loginWithRedirect()` call are appended to whatever the target was (usually defaulting to `/`).

## Alternatives and current work-arounds

Currently have to manually include the `target: window.location.search` in my state. Thinking this could be implemented by modifying the options before forwarding to the `auth0Client`

Or instead of implementing this as a feature I think a documentation example or a FAQ would be worthwhile.

Thanks!

**Comment by frederikprijck** [comment]
Hi,

I don't think we have an option to preserve the query parameters as we do not track the original URL when calling `loginWithRedirect`, all the SDK takes into account is the configured `redirect_uri` and the `appState.target`. So we have nothing to use to preserve those query parameters.

AppState is used to restore any state in between the redirect transaction from your application to Auth0. That `appState` has one special property, being `target`, which we us to restore a URL, or even querystring parameters, after being redirected back from Auth0 to your application.

I believe we can definitely improve documentation here to make it more clear.

Thanks,

**Comment by tkutcher** [comment]
Sounds good - thanks for the reply! I was more or less proposing the library itself manipulating the outgoing `appState.target` on the `loginWithRedirect` call. But doesn't feel like the cleanest solution. I think the documentation updates will be very helpful - thanks!
