### ISSUE TITLE
Error during ng test NullInjectorError: No provider for InjectionToken auth0.client

### ISSUE THREAD

**Issue by jessewilliams1** [auth0/auth0-angular#144]
### Describe the problem

I have a "User Service" that in turn uses AuthService in order to fetch the user's profile and generate login / logout buttons.

Local run and production build of my Angular 11 App work just fine but ng test is failing with:

```
NullInjectorError: No provider for InjectionToken auth0.client!
```

### What was the expected behavior?

The test should pass.
Adding AuthService as a provider in the .spec.ts file does nothing.

### Reproduction

1. Create a new Service that uses AuthService
2. run ng test on the application.
3. See the failure

### Environment

Angular 11
"@auth0/auth0-angular": "^1.4.0",

**Comment by frederikprijck** [comment]
Hey,

It looks like you havent imported AuthModule.forRoot({}) in your TestBed module.
You need to ensure you do so, or if not at least ensure you provide both the `AuthConfigService` and `Auth0ClientService`, like we are doing here: https://github.com/auth0/auth0-angular/blob/master/projects/auth0-angular/src/lib/auth.module.ts#L17

This is needed because those things are dependencies for the AuthService.

Let me know if that doesn't work.

**Comment by jessewilliams1** [comment]
@frederikprijck worked like a charm, thank you for the quick reply :-)

There are a couple of questions on the Auth0 community asking about the same thing

**Comment by EdoardoRoba** [comment]
Hi guys,

I am facing the same issue.

This is my LoginComponent that I am testing:
`import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { AuthService } from '@auth0/auth0-angular';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
  standalone: true,
  imports: [MatButtonModule, MatCardModule],
})
export class LoginComponent {
  constructor(public auth: AuthService) { }

  loginWithRedirect() {
    this.auth.loginWithRedirect();
  }
}
`

As soon as I test it:
`import { ComponentFixture, TestBed } from '@angular/core/testing';

import { LoginComponent } from './login.component';
import { AuthModule, AuthService } from '@auth0/auth0-angular';
import { environment } from 'src/environments/environment';
import { ApiService } from 'src/app/services/api.service';


describe('LoginComponent', () => {
  let component: LoginComponent;
  let fixture: ComponentFixture<LoginComponent>;
  let authService: AuthService;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [LoginComponent],
      providers: [
        AuthService,
        ApiService
      ]
    });
    fixture = TestBed.createComponent(LoginComponent);
    authService = TestBed.inject(AuthService);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    const fixture = TestBed.createComponent(LoginComponent);
    const component = fixture.componentInstance;
    expect(component).toBeTruthy();
  });
});
`

I receive the following error: No provider for InjectionToken auth0.client!

Can you help me with this please?

Thank you

**Comment by frederikprijck** [comment]
Same as the OP, you are missing some of our dependencies.

Don't manually provide authService as that doesnt include some of its dependencies, but ensure to provide all of our SDKs artifacts as mentioned above, either by importing our module, or through provideAuth0.
