### ISSUE TITLE
Should Redirect to loginURL when Token Expired and requiredLogin

### ISSUE THREAD

**Issue by cancan101** [auth0/auth0-angular#146]
This line here: https://github.com/auth0/auth0-angular/blob/01a23ef62aaa0f1506c33a0c88c2a6a26227fd40/src/auth0-angular.js#L315

just checks `auth.isAuthenticated` which is True even when the token is expired. That means that once a token expired, the user can navigate to routes that `requiresLogin`.

**Comment by lewma** [comment]
I agree, this is why my $locationChangeStart looks like:

        var token = store.get('token');
        if( token )
        {
            if( !jwtHelper.isTokenExpired( token ) )
            {
                auth.authenticate( store.get( 'profile' ), token ).then(function(data)
                {
                    console.log('authentication passed');


                },function(err)
                {
                    console.log('authentication failed');
                    $state.go('login');
                });
            }
            else
            {
                console.log('Token has expired');
                $state.go('login');
            }
        }
        else
        {
            console.log('Could not find token');
            $state.go('login');
        }

**Comment by lbweb** [comment]
I agree - however I used this code below for the run function:

Points:
1. If there is a route that is private - auth.hookEvents will take care of redirecting the user to a login page. 
2. Therefore, on each route change do two things: a. check the token for expiry and if it has expired, log the user out. b. if the user has a token that is not expired, re-authenticate them back in. 

```
.run(function($rootScope, auth, store, jwtHelper, $location) {
 
   auth.hookEvents(); //Check User is Authenticated before letting them thorugh to secure routes 

  // This events gets triggered on refresh or URL change
  $rootScope.$on('$locationChangeStart', function() {

  	var token = store.get('token');  //get token 

  	if(token){ //if token exists and is expired
	    if (jwtHelper.isTokenExpired(token)) {
				
				//sign the user out 
				 auth.signout();
				  store.remove('profile');
				  store.remove('token');
				  $location.path('/login');
		}
		else { //if token exists but is not expired - sign the user back in. 
			auth.authenticate(store.get('profile'), token);
		}
	} 

  	});

});
```

**Comment by mgonto** [comment]
Fixed all docs on this.

Thanks for letting us know :).
