### ISSUE TITLE
Cannot specify scope parameters when calling auth.refreshIdToken()

### ISSUE THREAD

**Issue by jimwheaton** [auth0/auth0-angular#147]
It is not possible to specify scope parameters when calling auth.refreshIdToken(refreshToken).  The workaround is to issue a POST request directly to the /delegation endpoint and specify the scope parameters in the POST body. It would be nicer to have the option to specify the scope parameters in the auth.refreshIdToken() call.

**Comment by jimwheaton** [comment]
Example of issue:

1. Obtain initial id_token and refreshToken with specific scope:
 auth.signin({
                popup: true,
                standalone: true,
                closable: false,
                authParams: {
                    scope: 'openid profile offline_access'
                }
            }, loginSuccess, loginError);


2. After token expires, attempt to use refresh token to get another id_token (this is in a $http interceptor):
if (jwtHelper.isTokenExpired(idToken)) {
                return auth.refreshIdToken(refreshToken).then(function (idToken) {
                    store.set('token', idToken);
                    return idToken;
                });
            }

There is no where to specify the scope parameters and the resultant id_token does not have the scope of the original id_token (specifically the 'profile' scope param)

Two workarounds:
1. call the /delegation endpoint directly and pass scope params in the POST body
2. use this code instead of the above:

if (jwtHelper.isTokenExpired(idToken)) {
                return auth.getToken({
                    refresh_token: refreshToken,
                    scope: 'openid profile offline_access'
                    api: 'auth0'
                }).then(function (resultIdToken) {
                    store.set('token', resultIdToken);
                    return resultIdToken;
                    });
            }

**Comment by mgonto** [comment]
I'll take a look at it probably next week.

Thanks for the report

**Comment by christiannwamba** [comment]
Hi,

The service wraps Lock and Auth0.js therefore can only work with APIs provided by the libraries. Auth0.js which Auth0-Angular relies on to perform refresh token does not give room to pass in scope when making a refresh token request.

A better option is what you are already doing in option 2 which is to request for token using the `getToken()` method.

Thank you.
