### ISSUE TITLE
How can you mock the data for unit tests?

### ISSUE THREAD

**Issue by Phatzor** [auth0/auth0-angular#151]
Hi,

According to your documentation a way to hook up the auth events is like

```
angular.module('myCoolApp', ['auth0'])
  .config(function(authProvider) {

    // routing configuration and other stuff
    // ...

    authProvider.init({
      domain: 'mydomain.auth0.com',
      clientID: 'myClientID',
      loginUrl: '/login'
    });
  })
  .run(function(auth) {
    auth.hookEvents();
  });
```

How would you then mock a user who is logged in (so I can unit test my client-side code which is behind login)?

**Comment by mgonto** [comment]
Just call the `authenticate` method with some mock data :): https://github.com/auth0/auth0-angular/blob/master/docs/storing-information.md#3-authenticating-the-user-on-page-refresh

Cheers!

**Comment by motin** [comment]
Related: https://github.com/neam/auth0-mock-api
