### ISSUE TITLE
Custom login example, with bower dependancies

### ISSUE THREAD

**Issue by RYFN** [auth0/auth0-angular#152]
The example here - https://github.com/auth0/auth0-angular/tree/master/examples/custom-login pulls in //cdn.auth0.com/w2/auth0-4.js as a dependancy.

Installing auth0-angular from bower pulls down auth0.js v6.3.0. If you replace auth0 in the example above with v6.3.0, a popup window is shown briefly when `auth.signin` is called. This is undesired behaviour. Is the bower dependancy in https://github.com/auth0/auth0-angular/blob/master/bower.json incorrect, or does the example need updating?

**Comment by mgonto** [comment]
Hey,

I've just updated the plugin to `auth0-6` and it's working perfectly for me https://github.com/auth0/auth0-angular/blob/master/examples/custom-login/index.html#L6.

That's all the change I had to do to get it working.

Could you try getting it again?

Thanks!

**Comment by RYFN** [comment]
Hey, if you `bower install auth0-angular` into an empty folder, and copy the contents of the `bower_components/auth0-angular/examples/custom-login` to the root of you project, you can replace your dependancies with bower dependancies -

    <script src="/bower_components/angular/angular.js" type="text/javascript"></script>
    <script src="/bower_components/auth0.js/build/auth0.js"></script>
    <script src="/bower_components/auth0-angular/build/auth0-angular.js"></script>

    <script src="//cdn.rawgit.com/auth0/angular-storage/master/dist/angular-storage.js" type="text/javascript"> </script>
    <script src="//cdn.rawgit.com/auth0/angular-jwt/master/dist/angular-jwt.js" type="text/javascript"> </script>
    <script src="//code.angularjs.org/1.2.16/angular-route.js" type="text/javascript"> </script>
    <script src="//code.angularjs.org/1.2.16/angular-cookies.js" type="text/javascript"> </script>
    <script src="./scripts/myApp.js" type="text/javascript"> </script>


This is where I'm seeing the issue - the auth0 lock window pops up briefly while I try and authenticate, then closes itself again. Unfortunately it closes too quickly for me to grab a screenshot of!

**Comment by mgonto** [comment]
Hey,

Could you check what version of anuglar, auth0.js and auth0-angular are installed?

Or could you upload a plunkr or jsfiddle with the bug?

Thanks!

—
var signature = { 
  name: "Martin Gontovnikas",  
  title: "Software Engineer",  
  twitter: "twitter/mgonto",
  github: "github/mgonto",
  linkedin: "linkedin/mgonto"
};

On 5 de mayo de 2015 at 13:04:31, RYFN (notifications@github.com) wrote:

Hey, if you bower install auth0-angular into an empty folder, and copy the contents of the bower_components/auth0-angular/examples/custom-login to the root of you project, you can replace your dependancies with bower dependancies -

<script src="/bower_components/angular/angular.js" type="text/javascript"></script>
<script src="/bower_components/auth0.js/build/auth0.js"></script>
<script src="/bower_components/auth0-angular/build/auth0-angular.js"></script>

<script src="//cdn.rawgit.com/auth0/angular-storage/master/dist/angular-storage.js" type="text/javascript"> </script>
<script src="//cdn.rawgit.com/auth0/angular-jwt/master/dist/angular-jwt.js" type="text/javascript"> </script>
<script src="//code.angularjs.org/1.2.16/angular-route.js" type="text/javascript"> </script>
<script src="//code.angularjs.org/1.2.16/angular-cookies.js" type="text/javascript"> </script>
<script src="./scripts/myApp.js" type="text/javascript"> </script>

This is where I'm seeing the issue - the auth0 lock window pops up briefly while I try and authenticate, then closes itself again. Unfortunately it closes too quickly for me to grab a screenshot of!

**Comment by RYFN** [comment]
This has pulled down the following -

angular 1.2.28
auth0 6.3.1 (although in the bower.json it says "experimental bower support")
auth0-angular 4.0.4

plunkered here - http://plnkr.co/edit/nYtj7W5C7BIwDQKOLKSO?p=preview 

I copied in the locally installed angular, auth0 and auth0-angular into the example. It seems to be behaving the same way, in both chrome and safari.
