### ISSUE TITLE
Can auth0-angular be used with IdentityServer v3 and OpenID Connect 

### ISSUE THREAD

**Issue by kasunkv** [auth0/auth0-angular#154]
I am testing out an angular.js app that connects to IdentityServer v3 for Authentication. Can i configure auth0-angular to work with IdentityServer v3 and OpenID Connect to authenticate the user?

**Comment by ntotten** [comment]
Do you mean using Auth0-Angular and Auth0 connected to IdentityServer or are you wanting to connect auth0-angular directly to IdentityServer?

**Comment by kasunkv** [comment]
Connecting auth0-angular directly to IdentityServer v3. I have identityServer v3 running on my development PC and from what i figured the currently auth0-angular connects to the Auth0 Identity Infrastructure. Can i configure it to connect to my development Identity Server v3 for authentication?

**Comment by ntotten** [comment]
The sample is designed to work with Auth0.
