### ISSUE TITLE
Allow popup mode to work with auth.signin without requiring callbacks

### ISSUE THREAD

**Issue by colinmutter** [auth0/auth0-angular#155]
Would it be possible to support the popup mode when there are *no* callbacks?  I understand the intent, but if you're using the events (e.g. `authProvider.on('loginSuccess', function() { ... }`) to handle successes and failures, etc. centrally, you shouldn't need the callbacks, right?

**Comment by christiannwamba** [comment]
Yeah the events are called even with pop up mode enabled but it will still throw if you miss the callback in pop up mode
