### ISSUE TITLE
Gulp wiredep build issue with bower dependencies

### ISSUE THREAD

**Issue by jeffgorder** [auth0/auth0-angular#156]
Because both auth0.js and auth0-lock are dependencies of the bower.json package, they will both be injected when you use wiredep (https://github.com/taptapship/wiredep) and gulp. That means that you automatically get lock so can't do a custom login or sign up page. 

It seems like it would be best to include auth0.js as a dependency and then if the developer wants lock, they can include it.

**Comment by christiannwamba** [comment]
You can do custom login with both provided:

```javascript
$scope.login = function () {
      auth.signin({
        popup:true
      }, function(profile, token, accessToken, state, refreshToken) {
        // Success callback
        console.log(profile);
      }, function(error) {
        console.log("There was an error logging in", error);
      }, 'Auth0'); //Supply the 4th argument to choose a preferred library
    };
```

Thanks
