### ISSUE TITLE
Auth0 signin using facebook, profile picture high-res

### ISSUE THREAD

**Issue by teuteuguy** [auth0/auth0-angular#160]
Hey,
I'm struggling to get the full resolution profile picture from a user signing into Auth0 via facebook.
Is there documentation somewhere on this ?
Thanks

**Comment by mgonto** [comment]
Hey,

Let me see if I can find somebody to help you out :).

@rolodato @cristiandouce can you guys help him out?

Thanks!

**Comment by rolodato** [comment]
One way of doing this is manually building the URL for the profile picture from the Facebook user ID (taken from here: http://stackoverflow.com/questions/8574759/getting-full-size-profile-picture)

```js
var url = 'https://graph.facebook.com/' + profile.identities[0].user_id + '/picture?width=9999'
```

For example, this redirects to my profile picture: https://graph.facebook.com/10152523927426961/picture?width=9999

Would you mind creating this same question at https://ask.auth0.com? That way it's easier to find for others who might run into the same issue. Thanks!
