### ISSUE TITLE
Provide a method to listen for accesstoken refresh.

### ISSUE THREAD

**Issue by anschm** [auth0/auth0-angular#163]
It should be possible to have a method to listen if the accesstoken is refresh and get the new accesstoken.

**Comment by frederikprijck** [comment]
Hey, 

Could you please elaborate on the use-case and provide some more context? What is the reason you want to be made aware of this?

Even though that functionality isn't explicitly available today, you could always use something like this:

```ts
isRefreshed$ = this.authService.accessToken$.pipe(
  scan(
      (
        acc: { current: string | null; previous: string | null },
        current: string | null
      ) => {
        return {
          previous: acc.current,
          current,
        };
      },
      { current: null, previous: null }
    ),
    filter(({ previous, current }) => previous !== current)
);
```

Not sure if this helps in your case, but a bit of more information could be helpful here.

**Comment by anschm** [comment]
I have an auth state implemented with ngxs in my angular application to hold the user information and the accesstoken. I need the access token to get the permissions. I have to check the permission in the frontend to hide buttons and so on. So in this case it would be nice to get informed if the accesstoken was refreshed. The code you provided is not working. There is no accessToken$ property available at the auhtService.

**Comment by frederikprijck** [comment]
An Access Token should never be parsed in the client, see https://auth0.com/docs/tokens

> In your applications, treat access tokens as opaque strings since they are meant for APIs. Your application should not attempt to decode them or expect to receive tokens in a particular format.

Sorry about the code I provided not working, I missed it was private for the exact reason mentioned above. You can be informed about the event by using comparable code with `authService.user$`, but I would discourage as the way you are trying to using Access Tokens is not for what they are intended.

If you need permissions in the client, you might want to have a different approach such as using the ID Token (and ensure it contains everything you need through an [Auth0 Rule](https://auth0.com/docs/rules) or your own API that calls our API to get the user's permissions, but not try and decode the Access Token as an access token is only supposed to be decoded by an API.
