### ISSUE TITLE
Normal user is able to make his jwt token never expires.

### ISSUE THREAD

**Issue by ethanlmovio** [auth0/auth0-angular#164]
In tutorial, it gave a example of keeping user logged in for refreshment `https://github.com/auth0/auth0-angular/blob/master/docs/storing-information.md#3-authenticating-the-user-on-page-refresh`.

I found there could be a problem to check whether the stored token is expired with the jwtHelper.isTokenExpired in this example. As we need to store the token on users' machines, it is easy for them to decode the token and change the `exp` value in the token. Then the `jwtHelper.isTokenExpired(token)` just always returns `true`. I am just wondering is there any better way than encrypting token locally to avoid the user changing the expiration time of the token?

**Comment by Zertz** [comment]
@ethanlmovio JWT's are signed with a secret key so if you change the payload server-side verification will fail. Here's a good explanation: https://scotch.io/tutorials/the-anatomy-of-a-json-web-token

**Comment by rolodato** [comment]
@Zertz's answer is correct, you can change the token's expiration date locally but that will fail on any API call since the signature will become invalid.

**Comment by ethanlmovio** [comment]
Correct. The user is able to stay in the UI, but the data will not be returned from the backend. Thanks you guys.
