### ISSUE TITLE
ngRoute required despite only using ui-router ?

### ISSUE THREAD

**Issue by motin** [auth0/auth0-angular#168]
Ran into this with the latest minified versions of auth0 libs prescribed in the angularjs guide:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module angular-frontend due to:
Error: [$injector:unpr] Unknown provider: $routeProvider
```

Auth0 includes:

```
<!-- We use client cookies to save the user credentials -->
<script src="//code.angularjs.org/1.2.16/angular-cookies.min.js"></script>

<!-- Auth0 Lock script and AngularJS module -->
<script src="//cdn.auth0.com/js/lock-7.5.min.js"></script>
<!-- angular-jwt and angular-storage -->
<script type="text/javascript" src="//cdn.rawgit.com/auth0/angular-storage/master/dist/angular-storage.js"></script>
<script type="text/javascript" src="//cdn.rawgit.com/auth0/angular-jwt/master/dist/angular-jwt.js"></script>

<script src="//cdn.auth0.com/w2/auth0-angular-4.js"> </script>
```

It turns out I need to add 'ngRoute' to app dependencies and include `<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-route.js"></script>`

I only use ui-router and do not want to include angular-route - what can I do?

**Comment by motin** [comment]
Haven't checked auth0's source code yet, but something like this maybe? https://github.com/userapp-io/userapp-angular/blob/9edac02f05ed96620efba68f3b3fb755b67b00a7/angularjs.userapp.js#L60-L67

**Comment by christiannwamba** [comment]
You are making a reference to `$routeProvider` in your app. Use `$stateProvider` rather for `ui-state`
