### ISSUE TITLE
Unlinking Accounts

### ISSUE THREAD

**Issue by limafelipe** [auth0/auth0-angular#169]
Have a api to [Unlinking Accounts](https://auth0.com/docs/link-accounts)?

**Comment by ashishdasnurkar** [comment]
@limafelipe linking/unlinking accounts apis are server-side only. To call them from client-side will require exposing API V2 token on client-side which is a major security risk.

**Comment by christiannwamba** [comment]
Added https://github.com/auth0/auth0-angular/pull/265/commits/343a379c0748d6fa142a26328715c761db0f847f
