### ISSUE TITLE
Invalid code examples in the API documentation

### ISSUE THREAD

**Issue by anschm** [auth0/auth0-angular#171]
This code example from the documentation is not working:

ngOnInit() {
  this.authService.error$.pipe(
    filter(e => e.error === 'login_required'),
    mergeMap(() => this.authService.loginWithRedirect())
  ).subscribe();
}

Can you please correct the documentation and provide an example how this should work. Thanks.

**Comment by frederikprijck** [comment]
Thanks for reporting this. This is indeed an issue, this should work:
```
import { GenericError } from '@auth0/auth0-spa-js';
...
ngOnInit() {
  this.authService.error$.pipe(
    filter((e) => e instanceof GenericError && e.error === 'login_required'),
    mergeMap(() => this.authService.loginWithRedirect())
  ).subscribe();
}
```

I will update our docs.

**Comment by anschm** [comment]
Thank you for your answer, but I checked this. Its not working. Where is GenericError coming from?

**Comment by frederikprijck** [comment]
I updated the comment above, but you can import it from `@auth0/auth0-spa-js`.
