### ISSUE TITLE
Missing Script:Start

### ISSUE THREAD

**Issue by dfdumaresq** [auth0/auth0-angular#173]
Hi, I'm getting issues trying to install. Below is the npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.3.6
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose stack Error: missing script: start
5 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:148:19)
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:58:5
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
5 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
5 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
5 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:300:12
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
5 verbose stack     at fs.js:334:14
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:42:10
6 verbose cwd /Users/ddumaresq/Projects/ApplyBC/AngularJS/auth0-angular/examples
7 error Darwin 14.5.0
8 error argv "node" "/usr/local/bin/npm" "start"
9 error node v0.12.7
10 error npm  v3.3.6
11 error missing script: start
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

If I follow your instructions for npm install auth0-angular, I get this console error:
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "auth0-angular"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.6
npm ERR! code ENOSELF

npm ERR! Refusing to install auth0-angular as a dependency of itself

when I run npm install, I get this console error:

> bufferutil@1.2.1 install /Users/ddumaresq/Projects/ApplyBC/AngularJS/auth0-angular/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
npm WARN prefer global jshint@2.5.11 should be installed with -g

> utf-8-validate@1.2.1 install /Users/ddumaresq/Projects/ApplyBC/AngularJS/auth0-angular/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
npm WARN EPEERINVALID grunt-karma@0.8.3 requires a peer of karma@~0.12.0 but none was installed.
npm WARN EPEERINVALID karma-chai@0.1.0 requires a peer of karma@>=0.10.9 but none was installed.
npm WARN EPEERINVALID karma-mocha@0.1.10 requires a peer of karma@>=0.12.8 but none was installed.
npm WARN EPEERINVALID karma-phantomjs-launcher@0.1.4 requires a peer of karma@>=0.9 but none was installed.
npm WARN EPEERINVALID karma-sinon@1.0.4 requires a peer of karma@>=0.10 but none was installed.
npm WARN EPACKAGEJSON auth0-angular@4.0.5 No license field.

**Comment by christiannwamba** [comment]
`npm ERR! Refusing to install auth0-angular as a dependency of itself` occurs when you are installing to a projects whose `package.json` name is `auth0-angular`
