### ISSUE TITLE
'login_required' error occurs if allowAnonymous: true

### ISSUE THREAD

**Issue by anschm** [auth0/auth0-angular#174]
If you use the AuthHttpInterceptor and have the following configuration to enrich the http call with the access token an error 'login_required' is thrown if the user is not logged in. Depending on the documentation this configuration should work for not logged in user and logged in user. I think its an bug. This error should not be thrown because its a valid use case to call the 'api/products' API without an access token. If you subscribe on the error observable provided by the AuthService to handle this error and call the API to login the login page appears. But maybe the user the user does not want to log in.

    httpInterceptor: {
      allowedList: [
        {
          uri: 'api/products*',
          allowAnonymous: true
        }
      ]
    }

**Comment by frederikprijck** [comment]
Hey,

I gave this a try and it seems to work fine, my assumption is that the `uri` is not correct and our interceptor isn't using that configuration.
Keep in mind that if u use `uri`, you should use the full URL:

```
httpInterceptor: {
  allowedList: [
    {
      uri: 'https://domain.com/api/products*',
      allowAnonymous: true
    }
  ]
}
```

If you don't want to specify the domain, you can use:

```
httpInterceptor: {
  allowedList: [
    {
      uriMatcher: (uri) => uri.indexOf('api/products') > -1,
      allowAnonymous: true
    }
  ]
}
```

Could you try if any of those two snippets fix it for you?

**Comment by anschm** [comment]
I check both snippets. It is not working. The rest of my configuration is working. In both variants a 'login_required' error is thrown. If I handle this error to call login the login page appears. In addition to use the full URL in the configuration is not a good option because angular enrichs the URL with the domain by using the httpClient. The full domain in a configuration should not used because of having different runtimes like production, development, e2e and so on. Thats why angular use the proxy mechanics.

**Comment by frederikprijck** [comment]
> In addition to use the full URL in the configuration is not a good option because angular enrichs the URL with the domain by using the httpClient. The full domain in a configuration should not used because of having different runtimes like production, development, e2e and so on. Thats why angular use the proxy mechanics.

Proxy is for local development, not for environments such as dev/prod.
You can use the exact same way for configuring the HttpInterceptor as you are configuring the domain with HttpClient, that shouldn't really matter.

Just because you need a full domain, doesn't mean it has to be hardcoded. Just like HttpClient expects a full domain to be configured, so does our interceptor. How you configure both of them and whether or not that is hard coded or configurable through the environments, is totally up to you.

> I check both snippets. It is not working.

I am unable to reproduce this as on my end `allowAnonymous` is working and not showing an error. 
Are you sure you are configuring allowAnonymous for the correct URL?

I am happy to look into it but I will need more context, as it is not the case that `allowAnonymous` isn't working by itself, there has to be more in play here.

**Comment by anschm** [comment]
I can reproduce this in my application and I can give you a look into my code if you want. Maybe we can do a zoom meeting or what else.

What I do in my application is exactly whats written in your documentation.
I have a ngxs state to handle authentication. Inside this state I listen on errors like:

  private bindListenErrors(ctx: StateContext<AuthStateModel>): void {
    this.authService.error$.pipe(
      filter(e => e instanceof GenericError)
    ).subscribe(
      (e: GenericError) => {
        if (e.error === 'login_required') {
          ctx.dispatch(new AuthActions.Login()); --> Calls AuthService with login silent
        }
      }
    );
  }

Also I am using your AuthInterceptor with the follwoing configuration:

auth: {
    issuer: '....'
    domain: ....,
    audience: ....
    clientId: ....
    scope: 'offline_access',
    redirectUri: `${window.location.origin}`,
    useRefreshTokens: true,
    httpInterceptor: {
      allowedList: [
        'api/profiles*',
        'api/videos*',
        'api/reports*',
        {
          uriMatcher: (uri) => uri.indexOf('api/competitions') > -1,
          allowAnonymous: true
        }
      ]
    }
  }

Whats happens now is, if a user routes to any page which calls the http client with 'api/competitions ....' the error listener I wrote above recieves a 'login_required' error and calls to login. After that the Auth0 login page appears. But the API should work for both kind of user (logged in and not logged in). I figured out that if I remove the error listening the AuthHttpInterceptor works for both kind of users. But in then I can not handle the error and call a login for the user.

**Comment by frederikprijck** [comment]
Thanks, I understand what is happening now. As you mentioned an error being thrown, I assumed you had an error in the console. However, you are referring to an error being emitted by the error$ observable.

I will look into how we can resolve this.

**Comment by anschm** [comment]
Thanks for fixing this issues. Is it possible to get a release of this. I would like to use this and fix it in my software.

**Comment by frederikprijck** [comment]
We will release this as soon as possible, there are a few other things that are going to be part of that same release but we should almost be good to go.
