### ISSUE TITLE
Twitter authenticates but pop up says there was an error processing the long

### ISSUE THREAD

**Issue by bechampion** [auth0/auth0-angular#175]
Hi all.

![screen shot 2015-11-01 at 14 00 41](https://cloud.githubusercontent.com/assets/4983875/10869239/31750564-80a1-11e5-88d2-e08613512e31.png)

The log files on the auth0 management portal show a succesful login , but the pop up says something went wrong?

Thanks!

**Comment by bechampion** [comment]
did i post this in the wrong place?

**Comment by andreisaac** [comment]
same here...

**Comment by Annyv2** [comment]
Hi! 

I was able to login successfully with twitter using Angular's seed project. Can you provide the steps you are following? Did you configure your Twitter consumer key and secret in your Auth0 Dashboard?

**Comment by christiannwamba** [comment]
Hi @bechampion 

Did you provide a callback URL from your application dashboard? Is this specific to Twitter or all other providers including Email & Password?
