### ISSUE TITLE
Failure to load on new tab. Problem goes away when refreshed.

### ISSUE THREAD

**Issue by schwer** [auth0/auth0-angular#182]
I'm seeing an unusual behavior when using "auth0-angular" module with Lock 7.11.1. I see the issue when executing "auth.signin" in angular. The following error is thrown from https://github.com/auth0/lock/blob/77f27e65a5258bdd8b954d4a8d1aa805c048c523/lib/options-manager/index.js#L448: Uncaught TypeError: Cannot read property 'length' of undefined. The symptom of this error is that the auth0 login form shows up incomplete (lacking email/password boxes and a button).

It only occurs when visiting the page for the first time (prior to a refresh). My guess is there's a race-condition bug because a refresh fixes it. I can workaround the issue by wrapping the "signin" call with a setTimeout(..., 50) to force its execution after the arrival of theoretically required resources.

**Comment by Annyv2** [comment]
Hi! Do you still receive this issue using Lock 9?

**Comment by schwer** [comment]
I haven't upgraded lock to that version. I'll give it a try.

**Comment by christiannwamba** [comment]
Hi @schwer 

Any update on this issue. Did the update fix it for you?
