### ISSUE TITLE
Custom Login not working

### ISSUE THREAD

**Issue by karthikeyanVK** [auth0/auth0-angular#184]
Hi All,

 I tried to use auth0 and i need to create a custom login that is needed for a app that follows my current UI standards. I have the following code in my app.js and login controller, when i click on sign-in button then there is popup that appears which has the domain url. Please help. 

authProvider.init({
      domain: 'http://xxx.net/token',
      clientID: 'self',
      loginState: 'sign-in'
    });

/***** Login controller *******/
 auth.signin({

        username: user.emailId,
        password: user.password,
        connection: 'Username-Password-Authentication'

      }, function(profile, idToken, accessToken, state, refreshToken) {

        var signInInfo = {
          profile:profile,
          idToken:idToken,
          accessToken:accessToken,
          state:state,
          refreshToken:refreshToken
        };

        store.set('signInInfo', signInInfo);
        deferred.resolve(true);
        $state.go('productTypes');
      }, function(err) {
        deferred.reject(false);
        console.log("Error :(", err);
      });

I have been redirected to a popup https://http//xxx.net/token/sso_dbconnection_popup/self

**Comment by ChristianHaro** [comment]
Yes i am having the same issue is not working at thsi time i hae downloaded the same exact code and tried but the same issue arrise

**Comment by stodolos** [comment]
I had the same issue, and then I realized I was including the lock JavaScript file, when you want the lock script OR the standard auth0 script, not both.  Hopefully that's it.

**Comment by ChristianHaro** [comment]
i am not including both i am only including the standard 

//cdn.auth0.com/w2/auth0-6.7.js

**Comment by Annyv2** [comment]
Hi! if you use sso:false then there's no popup. You can find more infomation about it [here](https://auth0.com/docs/custom-signup).  This is the code I used 
``` 
//Init in app.js
  authProvider.init({
    domain: AUTH0_DOMAIN, 
    clientID: AUTH0_CLIENT_ID, 
    loginUrl: '/login'
  });

//Login controller
  $scope.login = function() {
    auth.signin({
	sso:false,
	username: user.email,
    password: user.password,
	connection: 'Username-Password-Authentication'}, function(profile, idToken, accessToken, state, refreshToken) {


    store.set('profile', profile)
    store.set('token', idToken);
	
  }, function(err) {
    console.log("Error :(", err);
  })
  }
```

**Comment by RYFN** [comment]
If the example custom login could be updated with this parameter, that'd be helpful too.

**Comment by christiannwamba** [comment]
Hi! Where you able to find your way around this issue? Just some important note:

- Callbacks work only when `popup` is set to `true`
- When using redirect mode, you can listen to the `loginSucess` or `loginFailure` event to serve as callbacks.
- SSO works with only redirect

I will be closing this but if not satisfied, feel free to re-open
