### ISSUE TITLE
Need Auth0 rememberLastLogin parameter info for plain link option

### ISSUE THREAD

**Issue by mitiaptest** [auth0/auth0-angular#190]
I am using Auth0 and I have integrated it with Plain link so Auth0 Lock UI is rendering from that link so for this I have to set rememberLastLogin to false.

Anyone Having idea how to pass this parameter with link.

Thanks, Mit

**Comment by Annyv2** [comment]
Hi, Mit

On your auth.signin or lock.show function you can use this, would this work for you? (example is using auth.signin mode) 

```
function ($scope, $http, auth, store, $location) {
  $scope.login = function () {
    auth.signin({
	rememberLastLogin: false
	}, function (profile, token) {
          ...
```
