### ISSUE TITLE
Docs in MD not in HTML so they can be read on github instead of having to clone and open in browser.

### ISSUE THREAD

**Issue by jamesmandrews** [auth0/auth0-angular#200]
I don't understand why your docs for the repo are in HTML their is no ability to just read them from github, instead I have to unnecessarily clone the repo just to read them.

**Comment by frederikprijck** [comment]
This repository is using TypeDoc, so it is using a combination of markdown files and inline code comments to generate HTML documentation, which is deployed to https://auth0.github.io/auth0-angular/, this is referred to from the readme: https://github.com/auth0/auth0-angular#documentation

This generated documentation gets committed to the `docs` folder, which is deployed as is to GitHub pages.

There is no need to clone the repository if all you want is look at the generated HTML documentation.
