### ISSUE TITLE
Uncaught Error, "Cannot find module 'undefined'" and "Module xx not available"

### ISSUE THREAD

**Issue by jheuing** [auth0/auth0-angular#201]
This is a simple yeoman kickstarted angular app with just auth0 implemented, nothing more basically. The problem can be reproduced with this copy (npm install && bower install && gulp serve:dist): https://github.com/jheuing/angular-auth0-bug

The problem: 
Running "gulp serve" works perfectly to develop the application, which I did. Then I wanted to test building it, so I can see if auth0 also works in a desktop environment with electron, and then the problem showed up.

"gulp build" and "gulp serve:dist" produce a static version as it should, and the vendor.js includes the javascripts (I checked). But I get errors in the browser:

---

vendor-65c41279b7.js:115 Uncaught Error: Cannot find module 'undefined'
vendor-65c41279b7.js:31 Uncaught Error: [$injector:modulerr] Failed to instantiate module angular due to:
Error: [$injector:modulerr] Failed to instantiate module angular-storage due to:
Error: [$injector:nomod] Module 'angular-storage' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

---

This is related to angular-storage it seems, so I investigated that further. I started off with a clean setup and installed a0-angular-storage, got no problems. I started fresh again and installed only auth0, and I got the first error (module undefined). Now as soon as I install any other plugin, I get the second problem (module not found) also. 

It would be awesome if someone has any insights on this, as I have no clue.

Thanks loads!

**Comment by jheuing** [comment]
Sees not to be a local issue, as a friend of mine can reproduce the same thing - and also has no clue.

**Comment by gnandretta** [comment]
Adding the following dependencies to bower.json before _auth0-angular_ should fix the issue:
```
"auth0-lock": "^8.2.1",
"auth0.js": "~6.4.1",
```

**Comment by jheuing** [comment]
Thanks Gabriel, works great! :-)
