### ISSUE TITLE
Any idea on when there will be a release for angular 2?

### ISSUE THREAD

**Issue by imatefx** [auth0/auth0-angular#202]

**Comment by set321go** [comment]
Looks like they have another one on the go in a separate repo https://github.com/auth0/auth0-angular2 I was looking for the same thing, no idea what state it is.

**Comment by imatefx** [comment]
i don't think it is a library , it is just an example repo which focus mainly on angular-jwt2.
It will be useful to get refreshToken and updateUserMetadata functions as a library for angular 2

**Comment by mgonto** [comment]
Exactly, no need for a library anymore, now it's an example using `angular-jwt2` which we also built. Hope that's enough!

**Comment by mgonto** [comment]
We can add those methods to the example as well /cc @chenkie
