### ISSUE TITLE
Auth Guard redirects to login when token expired and does not try to refresh token

### ISSUE THREAD

**Issue by mbexp** [auth0/auth0-angular#203]
### Describe the problem

We have configured our application with short token lifetimes, both for the ID token and the access token (15 minutes).  We use token refresh and RTR.  The problem is that when either token expires and a user attempts to navigate to a different route within the application, the Auth Guard redirects the user to the login page.  It does this because, in the redirectIfUnauthenticated() of the AuthGuard, `isAuthenticated` is false.  The Auth Guard does not distinguish between a user that is logged out and a user that was successfully logged in but that needs a token refresh. 

Here is a comment made by Frederik P. in another issue:  https://github.com/auth0/auth0-angular/issues/75#issuecomment-716867810.  "Having an expired Access Token for the given API doesn't mean the user is not authenticated with the IDP anymore."  Unfortunately, it would seem that the Auth Guard is not following that statement given that `isAuthenticated` is false once the access token expires. 

### What was the expected behavior?

I expect a valid user to be able to continue navigating around the application even after their initial tokens have expired.  The user should not be aware that their tokens need to be refreshed.  They should be re-authenticated silently if that is needed.

One possible solution is for the Auth Guard to attempt token refresh by calling getAccessTokenSilently() if `isAuthenticated` is false, to determine whether the user is truly unauthenticated.  My team has created an Auth Guard wrapper that does just that and it solves the issue.  However, this doesn't address the root of the problem, which is that the user's authentication state within the application relies on access token validity, which, if I understand correctly, should only apply to API resource access. 

Perhaps a better solution would be to attempt token refresh earlier so that `isAuthenticated$` never emits false when tokens can be successfully refreshed.  When I dig into the auth0-spa-js code where `isAuthenticated` is determined, I see that the Auth0Client.getUser() calls the CacheManager.get() which tries to get the user off of the decoded ID token in local storage.  If the access token is expired, even if there is a refresh token in local storage, the user is returned as undefined.  Ultimately, that results in `isAuthenticated$` emitting false.  Maybe getUser() could handle the refresh token differently?

### Reproduction

1.  In the Auth0 dashboard, under your application settings, set your ID token lifetime to something short like 90 seconds.    Under your API settings, set your access token lifetime to the same amount.  You can also play around with the access token lifetime being shorter or longer than the ID token, but the result is the same, the bug still occurs.
2. In your auth client configs, set `useRefreshTokens: true` and `cacheLocation: 'localstorage'`.
3. Start the app.
4. Log in.
5. Wait for either token to expire.
6. Attempt to navigate to a different route within the app.

Actual behavior:  The user is redirected to login.  (This issue can be reproduced consistently.)

### Environment

- **Version of `auth0-angular` used:**  1.4.0
- **Which browsers have you tested in?** Chrome
- **Which version of Angular have you tested with?** Angular 9.1.3
- **Other modules/plugins/libraries that might be involved:** auth0-spa-js 1.14.0

**Comment by frederikprijck** [comment]
Thanks, I can see what's going wrong and we will have a discussion about whether or not this is expected from Auth0-SPA-JS side. Based on that we can see if we should patch the Angular SDK or SPA-JS.

**Comment by frederikprijck** [comment]
Hey @mbexp,

I opened a PR: https://github.com/auth0/auth0-angular/pull/209
Any change you could have a look and verify this solves the issue you are seeing?

**Comment by mbexp** [comment]
Thanks @frederikprijck, I've just verified that this does solve our issue.  Thanks for the quick work on this!
