### ISSUE TITLE
Hook?

### ISSUE THREAD

**Issue by mpaul31** [auth0/auth0-angular#204]
getSSOData is automatically called when sso is set to true and forces a redirect which flickers the page. is there a way to hook into this so it does NOT call this method if the app already contains a token?

**Comment by christiannwamba** [comment]
Hi! What the SDK basically does if there is an SSO data is to re-authenticate with details gotten from SSO data. 

So if you have a token or a profile, what could make sense to do is authenticate the user on `$locationChangeStart` event which sets the `auth.isAuthentcated` to true and there by skips the SSO flow. Thanks.
