### ISSUE TITLE
[Angular SPA] No silent login when accessing unprotected page (no guard defined on the route)

### ISSUE THREAD

**Issue by latannon** [auth0/auth0-angular#206]
### Describe the problem

I'm not sure this is a bug or unexpected behavior (or maybe lack of understanding Auth0 / oauth2) but let's me explain it. 
I'm developping an application with public access page (no login required) and with authenticated access page.

- When I open the app and logged in, everything is fine (isAuthenticated is true and user profile data is populated), on public and non public access page : Fine.
- If I refresh or close browser (or app tab), and open it again at home page (public access page), auth0 can't get my authentication data (login button is shown and no user data retrieved). 
- I need to explicitly click on login button or try to access protected page to get silent login works (no need to enter my credential).

**This occured with social connect or login/password authentication method.**

### What was the expected behavior?

Check my scenario : 

#### First scenario (public access)

- User has logged in do thing and close the browser
- User come back to public page (no authguard)
- Auth0 detects that there is an "previous authentication session"
- Do silent authentication process
- User is recongnized and can continue his stuff

#### Second scenario (public access)

- User has never logged in
- User access public page (no authguard)
- Auth0 detects that there is no "previous authentication session"
- No silent authentication process done and no login is prompted
- User has access to public page with no authenticated user (anonymous)

Isn't possible to silently get the authenticated user automatically without prompting login page on public page ?

### Reproduction

I reproduce this with the **auth0-angular-sample**

1. Clone https://github.com/auth0-blog/auth0-angular-sample
2. install package
3. set auth config
4. run app (you see login blue button)
5. get logged in (you logout red button)
6. Refresh the page (you see again login blue button)

### Environment

I am not sure this is really env dependent behavior. I face the issue with 

Angular CLI: 11.2.2
Node: 12.18.4
OS: win32 x64

Angular: undefined
...
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.2
@angular-devkit/core         11.2.2
@angular-devkit/schematics   11.2.2
@schematics/angular          11.2.2
@schematics/update           0.1102.2

auth0-angular : 1.4.1

But also the sample code which is a minimal sample code for auth0-angular lib.

Thank for your returns.

Cheers.

**Comment by frederikprijck** [comment]
Hey @latannon,

Which browser are you using? I just tried the mentioned reproduction steps with https://github.com/auth0-blog/auth0-angular-sample and it works as expected, see: https://www.loom.com/share/d4d2bcfd3e9c4d569f11871880150140

In case you are using any browser or browser setting that blocks third-party cookies, not being authenticated on page refresh is a known issue, see: https://github.com/auth0/auth0-angular/blob/master/FAQ.md#1-user-is-not-logged-in-after-page-refresh

**Comment by latannon** [comment]
Hi @frederikprijck,

Thank you very much for replying that soon !

Indeed, I see my Cookies options seems not to be fully compatible with Auth0 : 

An outdated Chrome Cookies options capture in English
![image](https://user-images.githubusercontent.com/248874/132043700-917bc29d-6f0c-43f5-b457-1830a6f1ae9b.png)
Allowing all cookies make it works.

Here my version (Yeah...Frenchie...) : 
![image](https://user-images.githubusercontent.com/248874/132043892-02df55d9-b8c5-4512-99d8-31a42a04ef60.png)
Selecting yellow options works now. It makes sense ! 

May this tips can be added somewhere like FAQ or Auth0 documentation (if it is not already the case)?
It is very helpful can be time saving.

Thank you again 👍
