### ISSUE TITLE
Filter chain halted as :authenticate rendered or redirected Completed 401 Unauthorized in 1ms (ActiveRecord: 0.1ms)

### ISSUE THREAD

**Issue by michaelstokes** [auth0/auth0-angular#210]
Hi, 

After following the guide to implement authentication with rails and angularjs, I seem  to be getting the following:

Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.1ms)

I've implemented following the guide. I guess its due to the the header but I've implemented the part which handles this.

This is occuring before a create action, the user is able to login and that works on the angular side. 

Thank you :)

**Comment by christiannwamba** [comment]
Hi

Which guide are you speaking of? Make sure you have the Authorization header in the request you are sending to the server.

**Comment by michaelstokes** [comment]
Hey thanks, 

This was the problem https://ask.auth0.com/t/angularjs-rails-authenticate-401-unauthorized-in-1ms/2244/7 being due to the latest ruby-jwt update affecting the 

`config.token_secret_signature_key `

line in the config at the time. 

This now works for me.
