### ISSUE TITLE
Request email from twitter

### ISSUE THREAD

**Issue by kitab15** [auth0/auth0-angular#213]
I want to retrieve user's email address from twitter.

The Connections > Social > Twitter (Auth0 app) says: 
_"Twitter_ does not currently provides user's email address"_
but now, with [extra permissions](http://stackoverflow.com/questions/22627083/can-we-get-email-id-from-twitter-oauth-api) it's possible using this [twitter's test endpoint](https://api.twitter.com/1.1/account/verify_credentials.json)

I tried using:
`authParams: {
    scope: 'openid email',
 }`

and it works fine for linkedin, facebook and github but not for twitter, even, with the extra permissions.

I think, it could be an auth0-angular's limitation. 
I'll appreciate any help.

**Comment by Annyv2** [comment]
Hi! 

You can obtain twitter's email by making a rule in Auth0.com. On your Auth0 Dashboard go to Rules - Get email address from Twitter, and there configure your twitter consumer key and secret by adding those values to the configuration global object in the settings section. Notice that your application needs to be whitelisted previously so you can access emails. After you do that, on your Angular application you can access {{auth.profile.email}}

![rules](https://cloud.githubusercontent.com/assets/5016479/13749770/0a20bd26-e9d5-11e5-8108-f90a2b54fbe5.JPG)

**Comment by kitab15** [comment]
Thanks! This works great!

**Comment by DESHU44** [comment]
I have configured like below code but still not able to get email id from facebook.

lock = new Auth0Lock(myConfig.clientID, myConfig.domain, {
    authParams: { scope: 'openid email'}
  });
