### ISSUE TITLE
Provide a way to retrieve the ID Token using a custom (non-default) audience

### ISSUE THREAD

**Issue by schnucks-pveeramach** [auth0/auth0-angular#214]
### Problem

> If access token is retrieved using a non default audience, the `idTokenClaims$` observable emits an event with a null value because it internally appears to be always looking for id token using the default audience:
```
// This returns a null value when access token is retrieved as shown on the next line
this.authService.idTokenClaims$.pipe((take(1)))
  .subscribe((idToken) => {
    console.log('id token:', JSON.stringify(idToken));
  });

this.authService.getAccessTokenSilently({
      audience: 'non default audience',
      ignoreCache: true
    });
```

### Ideal solution

> The AuthService either exposes a way to retrieve the ID token for a given audience or the observable emits id tokens for any audience with some way to identify what audience it is for.

**Comment by schnucks-pveeramach** [comment]
Now that 1.6.1 is available, the below snippet worked, because the injection token is exposed:
```
this.authService.getAccessTokenSilently({
      audience: 'non default audience',
      ignoreCache: true
    }).pipe(take(1))
      .subscribe((token) => {
        this.auth0Client.getIdTokenClaims({
          audience: 'non default audience'
        }).then((idToken) => console.log(idToken));
      });
```
where `auth0Client` is injected into the component using:
`@Inject(Auth0ClientService) private auth0Client: Auth0Client`

Maybe this is not a good approach or the intended use of the injection token but documenting the observation nevertheless.

**Comment by frederikprijck** [comment]
Thanks for the update. I believe this is not an explicitly supported feature, but a side-effect of exposing the auth0Client, which I believe is a good idea for these kind of situations where you might need behavior of the underlying SDk that doesn't exist in the Angular SDK natively.
