### ISSUE TITLE
hookevents() not working

### ISSUE THREAD

**Issue by jmls** [auth0/auth0-angular#217]
It seems to me as if my hookevents() is not working. I have

```
  auth.hookEvents();
```

and 

```
        $stateProvider
            .state('foo', {
                url: '/foo',
                templateUrl: foo.html',
                controller: 'FooController',
                controllerAs: 'vm',

                data: {
                    requiresLogin: true
                }
            });
```

as a route

however, if I go to /foo, then the page shows

I *am* trying to run auth.init() in the run function (because I need to get the init data from http) , so I don't know if this makes a difference.

If I navigate to /login, then the login screen works as expected

Any idea on what I may be missing / doing wrong ?

**Comment by Annyv2** [comment]
Hi! Are you using loginState in your authProvider.init? loginUrl is for ngRoute, while loginState is for ui-router
