### ISSUE TITLE
signout() race condition

### ISSUE THREAD

**Issue by laholmes** [auth0/auth0-angular#222]
Calls to signout() do not reliably clear localStorage. 

The method is synchronous but it looks like there is a race condition in the handler this method invokes. This then breaks my standard implementation of route restriction which uses angular stateChange detection and a route restriction flag on ui-router states. Inside the stateChange handler, we check for presence of a token and redirect if necessary, if the signout() call failed to clear the token, a user who has logged out can still access restricted views.

The workaround I'm using now is to clear localStorage on logout using angular $window service, rather than calling signout()

**Comment by christiannwamba** [comment]
This provider does not provide `localStorage` implementation internally but has a support service `angular-storage`. What you can do is listen to `logout` event and clear the token from the storage.
