### ISSUE TITLE
isAuthenticated and requiresLogin examples for page refresh

### ISSUE THREAD

**Issue by bwinchester** [auth0/auth0-angular#226]
Wanted to put this out there for anyone having issues with auth0-angular on page refresh and being re-routed to the authProvider.options.loginUrl . In all of the examples, in my experience with auth0-angular v4.05 (whats in docs and CDN), they always have a `$rootScope.$on('$locationChangeStart', function() {` in the '''angular.app.run''' method. 

My app always seems to get rerouted to the loginUrl for app sections marked with 'requiresLogin: true', even when the token is available and is set according to the documentation instructions/examples.

The 4.0.5 release checks auth.isAuthenticated and auth.refreshTokenPromise [4.0.5 build line 293](https://github.com/auth0/auth0-angular/blob/v4.0.5/build/auth0-angular.js#L293) before your '$locationChangeStart' code executes to populate token on refresh, as the [docs instruct](https://auth0.com/docs/quickstart/spa/angularjs/nodejs#7-keep-the-user-logged-in-after-a-page-refresh).

simply remove the '$locationChangeStart' listener and execute the example code inside the example listener.

This might be due to some angular breaking change with code execution order on locationChangeStart that worked pre-May 2015.

**Comment by frontweb** [comment]
I'm having the same issue. The token stored in local storage is validated through an AJAX call to mysubdomain.auth0.com. How are you delaying the redirection to the login page until this AJAX call completes?

**Comment by christiannwamba** [comment]
Hi

I am unable to reproduce this issue. If you are still having the issue, kindly re-open and we will work on it together. Thanks

**Comment by bwinchester** [comment]
I was just trying to comment and let people know that the Auth0 Angular examples are out-dated and to remove the locationchangestart listener from the example if their authRequired pages are redirecting to login/default pages, even when valid token is stored in browser.

**Comment by christiannwamba** [comment]
Cool. Thanks for the feedback.

**Comment by allenan** [comment]
I was having the same issue (page refresh redirected to the login page). I was able to solve this by removing the `$rootScope.$on('$locationChangeStart'` recommended by the docs and just putting the rest of the contents in the `run` method like this:

```javascript
.run(['$rootScope', 'auth', 'store', 'jwtHelper', '$''location', function($rootScope, auth, store, jwtHelper, $location) {
  //remove this listener
  //$rootScope.$on('$locationChangeStart', function() {
    var token = store.get('token');
    if (token) {
      if (!jwtHelper.isTokenExpired(token)) {
        if (!auth.isAuthenticated) {
          auth.authenticate(store.get('profile'), token);
        }
      } else {
        auth.refreshIdToken(token);
      }
    }
  //});
}])
```
