### ISSUE TITLE
authParams arbitrary params are only send on social connection or re-login using last logged as button

### ISSUE THREAD

**Issue by JackLeo** [auth0/auth0-angular#228]
Not sure if it is intended behaviour.

https://auth0.com/docs/libraries/lock/sending-authentication-parameters states that it is possible to add arbitrary variables to authParams.

When using ```auth.signin``` with these options:

    var loginOptions = {
        closable: false,
        gravatar: false,
        primaryColor: '#bada55',
        icon: '/images/logo.png',
        socialBigButtons: true,
        disableSignupAction: true,
        authParams: {
            scope: 'openid email',
            my_arbitrary_param: 'fooo'
        }
    };

my_arbitrary_param will be passed using SalesForce login or any login when pressing "you had last logged in as" button. Using fresh email/password login this is not being passed to auth0 rules.

**Comment by christiannwamba** [comment]
Hi

You cannot pass arbitrary data according to the doc. `access_token`, `scope`, `protocol`, `device`, `request_id`, `connection_scopes`, `nonce` and `state` are the supported params.
