### ISSUE TITLE
Issues in incognito

### ISSUE THREAD

**Issue by mishotek** [auth0/auth0-angular#232]
### Describe the problem

> When you are logged in and refresh the page in the regular browser, authService.isAuthenticated$ emits true as an initial value, but in incognito it emits false.

### What was the expected behavior?

> Even in incognito, if the user is logged in and  the page gets refreshed, authService.isAuthenticated$ should emit true as an initial value

### Reproduction
1. Log in
2. Subscribe to authService.isAuthenticated$ to log value
3. Refresh the page in incognito and regular browser, you will see the difference in the initial value

### Environment

> Please provide the following:

- **Version of `auth0-angular` used:** I was working on version  1.1.0 also tested 1.7.0 and still go that issue
- **Which browsers have you tested in?** Google Chrome
- **Which version of Angular have you tested with?** Angular 10
- **Other modules/plugins/libraries that might be involved:**

**Comment by frederikprijck** [comment]
This is known behavior and explained in our FAQ: https://github.com/auth0/auth0-angular/blob/master/FAQ.md#1-user-is-not-logged-in-after-page-refresh.

In general, if you want this to work in browsers that have 3rd party cookies blocked, you need to either use Rotating Refresh Tokens or Custom Domains, see the above FAQ for info.
