### ISSUE TITLE
URL white listing not working 

### ISSUE THREAD

**Issue by skerovs** [auth0/auth0-angular#235]
### Problem description:

I am trying to white list a URL of my API to not include an access token. However, no matter what configuration I try it always attaches the token and then I get "Login Required" message. 

### Expected Behaviour:
I would like to not add the access token to the request on certain URLs. 

### Reproduction:
I am setting up this as per documentation in the Interceptor options. 
Try 1.
```
httpInterceptor: {
    allowedList: [
      `${apiUri}/*`,
      '/api/*',
      {
        uri: '/api/blog/*',
        allowAnonymous: true,
      },
    ],
  },
```
Try 2.
```
  httpInterceptor: {
    allowedList: [
      `${apiUri}/*`,
      '/api/*'
     , {
          uriMatcher: (uri) => uri.indexOf('/api/blog') > -1,
          httpMethod: HttpMethod.Get
       }
    ],
  },
```

### Environment
Version used 1.7.0
Browser: Chrome
Angular 12

**Comment by frederikprijck** [comment]
Hey,

I dont know your exact situation, for that I will need some more information. However, I have a feeling the reason it isnt working is because `${apiUri}/*,` is catching all routes, resulting in the token being added.

Could you try without that part ?

If that doesn't work, please provide more context, preferably a reproduction for us to look into!

Thanks

**Comment by skerovs** [comment]
The problem is that I want to exclude only one route that lives on the api route. In the scenario that the ${apiUri}/*, would be the cause wouldn't that mean I have to specify exact routes for everything except that one route? In terms of repro steps it there is not much it is literally just the Interceptor settings as above the rest is as per the example in the read me. I can make a small app with the same setup but will not be able to provide the actual api. Would you have a suggestion of how exact repro would you like? 
Nonetheless, will try it out and let you know the result. 

BTW: I really like your library. I wanted to give you thumbs up.

**Comment by frederikprijck** [comment]
> The problem is that I want to exclude only one route that lives on the api route. 


You can solve this using one entry by using the `uriMatcher`, which gives you alot more flexibility.

**Comment by skerovs** [comment]
Hello, I have tried to use the `uriMatcher` but sadly no luck. Once you add `api/*` or `${apiUri}/*` it will attach the token on every route even if I use the `uriMatcher` to exclude one of the paths that is living on the `api`. 
In order to make it work, I have moved all my paths one level deeper and the ones I want without token live one level up. 
What I have now: 

```
httpInterceptor: {
    allowedList: [
      `${apiUri}/api/v1/*`
    ],
```
which will attach token to **localhost:3333/api/v1/blog** but not to **localhost:3333/api/blog**

I feel like this is really a hack but will work for now.

In terms of repro, I am not sure what to do. What I can think of is to make various configurations, which did not work for me and put them into a git repo.

**Comment by frederikprijck** [comment]
What I mean is remove most, if not all entries but use a single`uriMatcher`. That way you get full control over the matching, you can create regexes, use string comparising, startWith, endWith or whatever you want. You can even built your own complex matching algorithm.

It's expected that once u use `api/*` that it will match for anything that starts with `api`. If you do not want that, you shouldnt use such a wildcard route. It is for these kind of situations that we have added `uriMatcher`, that would allow you to build your own logic such as: `add a token for anything that contains api, but does not contain v1`:

```js
httpInterceptor: {
  allowedList: [{
        uriMatcher: (uri) => uri.indexOf('api') > -1 && uri.indexOf('v1') === -1
  }],
},
```

**Comment by skerovs** [comment]
I have to say I have not understood that from the docs but it makes complete sense. Thank you will try one more time :D 
And thank you for taking the time to help out. It is much appreciated.

**Comment by skerovs** [comment]
Hello frederikprijck, so I tried again according to the example you provided above and works like charm. I have not realised that you a) have to have the paths b) the Uri matcher. At some point I tried two have multiple matches :D 
Again sorry for bothering you and thank you for your help.
