### ISSUE TITLE
page refresh breaks when angular is upgraded

### ISSUE THREAD

**Issue by rajibahmed** [auth0/auth0-angular#240]
Hi,

I have been facing an annoying issue that when I upgraded -

when angular.js > 1.5.0 then page refresh will take you to login page. I have tested it by changing, 
angular version on htm5mode example. 

https://github.com/auth0/auth0-angular/tree/master/examples/html5mode

```html
<script src="https://code.angularjs.org/1.5.1/angular.js" type="text/javascript"></script>
<script src="https://code.angularjs.org/1.5.1/angular-cookies.js" type="text/javascript"></script>
<script src="https://code.angularjs.org/1.5.1/angular-route.js" type="text/javascript"></script>
```

by changing the version numbers, I was able to be logged in when **angular version is 1.5.0**

**Comment by christiannwamba** [comment]
Hi @rajibahmed 

Could you provide more details on this issue so I can help you?

**Comment by rajibahmed** [comment]
This is solved, Its was problem in my code.
