### ISSUE TITLE
Make the package Angular 13 compatible

### ISSUE THREAD

**Issue by pantaluna** [auth0/auth0-angular#241]
### Describe the problem you'd like to have solved
`npm i`` returns an error that this package depends on Angular >=9 <=12

### Describe the ideal solution
Fix the upstream dependency conflict

## Alternatives and current work-arounds
npm i --force

### Additional context: npm log
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @angular/common@13.0.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=9 <=12" from @auth0/auth0-angular@1.8.0
npm ERR! node_modules/@auth0/auth0-angular
npm ERR!   @auth0/auth0-angular@"^1.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by frederikprijck** [comment]
Thanks for reporting this.

I will see if I can add a PR to solve this, but you might need to resort to `npm i --force` for the time being.

**Comment by frasermclean** [comment]
Yes please! I am building a new application with Angular 13 and am having issues with this.

**Comment by cskiwi** [comment]
I installed the latest version on my angular 13 app. And this is working without any issues
