### ISSUE TITLE
RefreshToken not working when loading dynamic configuration

### ISSUE THREAD

**Issue by duvet86** [auth0/auth0-angular#244]
### Describe the problem

Hello, we are dynamically loading the auth0 config through the APP_INITIALIZER using the AuthClientConfig and we are also following all the steps defined [here ](https://community.auth0.com/t/gettokensilently-userefreshtokens-getidtokenclaims-how-to-use-it-correctly/55619) in order to enable token refresh. But apparently the token is not refreshed and the is user is not authenticated. The auth0 service is returning isAuthenticate$ true but the user$ and idTokenClaims$ are null.

### What was the expected behavior?

user$ and idTokenClaims$ to be not null.

### Reproduction

1. Load auth0 config using AuthClientConfig  in APP_INITIALIZER 
2. Wait for the token to expire
3. Click on button that subscribes to user$
4. user will be null

If so, provide steps:

- Screenshots
![image](https://user-images.githubusercontent.com/5604548/143546685-2dd057ad-bc00-4646-8ab2-2aee15ae0205.png)

### Environment

- **Version of `auth0-angular` used:** "@auth0/auth0-angular": "^1.7.0",
- **Which browsers have you tested in?** Chromium Edge
- **Which version of Angular have you tested with?** "@angular/core": "12.2.0",
- **Other modules/plugins/libraries that might be involved:**

**Comment by frederikprijck** [comment]
Hi,

When subscribing to the user observable after a token is expired, it is expected to retrieve `null`. Typically, you would subscribe before the token is expired and you would get a user instance.
Subscribing to any of those observables doesn't refresh any of the tokens when expired. If you need to get a new token, u can use the service's `getAccessTokenSilently` method. Typically, this is being taken care of by the SDK's HttpInterceptor.

Let me know if that would help or if you are still experiencing issues.

**Comment by duvet86** [comment]
Thanks.
Yes, after reading this [issue ](https://github.com/auth0/auth0-angular/issues/203) and delving the source code I realised that.
Using `getAccessTokenSilently` to retrieve a new token generates a non ideal delay between actions so we decided to create snapshot of the token claims during app initialisation.

Thanks.
