### ISSUE TITLE
getTokenSilently not providing updated access_token

### ISSUE THREAD

**Issue by devilsgeographer** [auth0/auth0-angular#248]
### Describe the problem

> When our access_token expires, the process to provide a new token does not appear to emit a new access token via getAccessTokenSilently method.   We can see the http requests for the silent refresh html page with the code, the code is then exchanged for a token via another request, but the observable does not emit a new access token.   We need to store the new access_token so our app can remain connected. 

![image](https://user-images.githubusercontent.com/17552717/144505476-4f11caf6-99af-4071-a700-809542944729.png)

Our code that wires this all together is as follows: 
```ts
checkAuthEpic = (
    action$: Observable<AnyAction>,
    state$: StateObservable<IAppState>,
  ): Observable<AnyAction> =>
    action$.pipe(
      ofType(SecurityActions.CHECK_AUTH),
      switchMap(() =>
        this.authService.isLoggedIn$.pipe(
          takeWhile((isLoggedIn: boolean) => isLoggedIn),
          switchMap(() =>
            combineLatest([
              this.authService.user$,
              this.authService.getToken$(),
              this.authService.getIdTokenClaims$(),
            ]),
          ),
        ),
      ),
      switchMap(([profile, token, idToken]) => {
        console.log('composing login');
        // here, the token value never updates.  
        const loginData = this.composeLoginObj(state$, profile, token, idToken);
        return of({
          type: SecurityEpicActions.STORE_LOGIN_OBJECT,
          payload: loginData,
        });
      }),
    )
```

Looking deeper, the authService itself does not emit the new value.   
```ts
this.authService.getAccessTokenSilently().subscribe(token => {
      console.log(`token ${token}`);
});
```

### What was the expected behavior?

> When we subscribe to the getTokenSilently observable, a new access_token should be provided, after the silent refresh completes.  

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced **consistently** or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

1. In our API that the app uses, we set the Token expiration seconds to 120, Token expiration for browser flows to 100
2. Login to the angular app, wait over 120 seconds
3. Perform an API request that will need a token.   The token being expired seems to be caught, and a new access token request occurs (look for an html page, and an api request in network tab, screenshot is above).     
4. In your subscription to getAccessTokenSilently, a new access_token is not emitted.  

### Environment

> Please provide the following:

- **Version of `auth0-angular` used:**
- 1.4.1, 1.6.2, 1.8
- **Which browsers have you tested in?**
- Google Chrome 96.0.4664.45 
- **Which version of Angular have you tested with?**
- 10.0.0
- **Other modules/plugins/libraries that might be involved:**
- redux-observable

**Comment by frederikprijck** [comment]
Hey,

What is `authService` here? It does not look like it is our AuthService. Could you share the code that is in AuthService as well? Our SDK's `getAccessTokenSilently` should emit the newly retrieved token.

Thanks.

**Comment by devilsgeographer** [comment]
authService comes from node_modules\@auth0\auth0-angular\lib\auth.service.d.ts

Our AuthenticationService consumes your authService, like so:

`import { Injectable } from '@angular/core';
import { AuthService } from '@auth0/auth0-angular';
import { Observable } from 'rxjs';
import { IdToken } from '@auth0/auth0-spa-js';

@Injectable({
  providedIn: 'root',
})
export class AuthenticationService {
  constructor(public authService: AuthService) {}

  get isLoggedIn$(): Observable<boolean> {
    return this.authService.isAuthenticated$;
  }

  getToken$(): Observable<string> {
    **return this.authService.getAccessTokenSilently();**
//  this is where we would expect the new access_token to be provided
  }

  getIdTokenClaims$(): Observable<IdToken | null> {
    return this.authService.idTokenClaims$;
  }

  get user$(): Observable<any> {
    return this.authService.user$;
  }

  get isLoading$(): Observable<any> {
    return this.authService.isLoading$;
  }

  login(): void {
    this.authService.loginWithRedirect();
  }

  logout(): void {
    this.authService.logout({ returnTo: `${window.location.origin}/logout` });
  }
}
`
Thank you

**Comment by frederikprijck** [comment]
Thanks. That service seems fine.

Could you provide some more information on how we can reproduce this as I cant see why it would not emit the new `access_token`.

**Comment by devilsgeographer** [comment]
We had noticed this issue in our prod environment, after investigating some authentication errors.     We have seen this same issue in all 4 of our environments.     To reproduce this in our dev environment quickly, I changed the timeout settings to a very low amount of 2 minutes.    With that change only, we can see the issue.    I would have to put together a full app that reproduces in our environment to give any more detail on reproduction.

**Comment by devilsgeographer** [comment]
I have created a new api and sample app.    What I see is that the http interceptor is working correctly for updating the access token via:

AuthModule.forRoot({
    domain: env.auth.issuer,
    clientId: env.auth.clientId,
    audience: env.auth.audience,
    scope: env.auth.scope,
    connection: 'Username-Password-Authentication',
    httpInterceptor: {
      allowedList: ['http://localhost:8080/*'],
    },

  providers: [{  provide: HTTP_INTERCEPTORS, useClass: AuthHttpInterceptor, multi: true },

I have my API access token expiring in 2 minutes via auth0 dashboard.   In the app, I have a timer to hit the API every 15 seconds:

![image](https://user-images.githubusercontent.com/17552717/145275259-d242b2d0-bdd2-4d19-a317-debfeaad787d.png)

The access token is seen as expired, and is being refreshed in the requests.  

However, I need that access token outside the interceptor.  Specifically I am connecting to a secure websocket.    

`this.webSocketSubject = webSocket({
      url: webSocketUrl,  //  this url includes the access_token
      openObserver: this.onOpenSubject,
      closeObserver: this.onCloseSubject,
    });`

In my constructor for my AuthenticationService, I subscribe to getToken$.     The new token that I see in the requests, is never emitted by that observable.    

`export class AuthenticationService {
  constructor(public authService: AuthService) {

    combineLatest([
      interval(125000).pipe(
        startWith(0)),
      this.user$,
      **this.getToken$(),**
      this.getIdTokenClaims$(),
    ]).subscribe(([timer, 
      profile, token, idToken]) => {
      console.log('updated user stuff');      
      //  the access token is never updated here
      console.log('token from getToken:' + token);
    });
  }
....
`


How can I get the latest access token, which is available in the auth0 interceptor, but seemingly not the AuthService?

**Comment by frederikprijck** [comment]
That code is not going to work as `getToken$()` is not configured to re-emit whenever the token changes. It emits a token once and completes. What you want is something like this:

```ts
interval(125000).pipe(
  startWith(0), 
  switchMap(() => combineLatest([this.user$, this.getToken$(), this.getIdTokenClaims$()]))
).subscribe(([profile, token, idToken]) => {
  console.log('token from getToken:' + token);
});
```

**Comment by devilsgeographer** [comment]
Thank you for the explanation.  I am able to see with the above code we can get the new token.   It would be really nice if getToken$  would emit the new access tokens.   We will have to write some custom code to check the incoming tokens expiration, and schedule a future token refresh via new subscription, or listen for our failing websocket reconnection, see if the token is expired there, and if so get and store a new one before reconnecting.    Might be more appropriately done via the sdk if other users would want an updated access token.     Thanks again for your help.

**Comment by frederikprijck** [comment]
`getToken$` is your own method, so if you want it to emit the new token, you will need to change your own code. 
When using our SDK, if u need an access token, you are expected to call `getAccessTokenSilently`, as mentioned above.

> We will have to write some custom code to check the incoming tokens expiration, and schedule a future token refresh via new subscription,

Mostly, there is no need for people to worry about the access token, as an Access Token is meant for the API and our HttpInterceptor will ensure it gets passed to that API. Same with refreshing the token, this is all taken care of by the SDK.

What are you trying to do that requires you to get the access token?

**Comment by devilsgeographer** [comment]
the code for getToken$    is....   

` getToken$(): Observable<string> {
    return this.authService.getAccessTokenSilently();
  }`

We have a secure websocket on AWS, where the accessToken needs to be part of the URL.    Our customers can have the app open for several days.    When the socket disconnects, we need to fetch the new accessToken for the websocket connection.

**Comment by frederikprijck** [comment]
That code is fine, but it is important to know that code will only emit the token once, and not emit any future tokens that are retrieved. You need to call `this.authService.getAccessTokenSilently()`, or in your case `getToken$()`, everytime you need the token.
