### ISSUE TITLE
Tries to get token when it shouldn't and get "invalid state" error message

### ISSUE THREAD

**Issue by crhistianramirez** [auth0/auth0-angular#249]
### Describe the problem
I'm getting the error "Invalid state" when using the `AuthGuard` on my routes. I have a setup where all my routes have that guard except for my callback route.

When trying to debug I set a breakpoint in `redirectIfUnauthenticated` and I am seeing some strange behavior where `isAuthenticated` is true, and then very shortly therafter it is false which causes the application to try and get a new token when it shouldn't. I believe that is causing the invalid state error. 

![image](https://user-images.githubusercontent.com/16483662/144540784-b8a40093-282f-49fc-b914-f09459259308.png)

### What was the expected behavior?
I can see (on an app where it is working) that the "healthy" behavior is:
1. User is authenticated so `isAuthenticated` is true anytime its observed
2. User is not authenticated so `isAuthenticated` is false first and then `true` anytime its observed thereafter

### Reproduction
I tried to create an minimal reproducible example on a new application with the same version of angular and auth0/angular but haven't been able to reproduce which leads me to believe there is something in my code causing this issue. Is there anything you could recommend I look at to try and figure out why it thinks its unauthenticated when it actually is? 

Things I've tried:
- observed the cookies to see if they change between states (they don't)
- looked for any instances of logout

### Environment
- **Version of `auth0-angular` used:** 
- **Which browsers have you tested in?** Chrome
- **Which version of Angular have you tested with?** 10.1.5
- **Other modules/plugins/libraries that might be involved:** 1.8.0

**Comment by Jacooscript** [comment]
I am getting "invalid state" error message too, but in another scenario a bit.
1. I call loginWithRedirect()
2. After redirect I call handleRedirectCallback() (an url contains "code" and "state")
3. I get "invalid state" error permanently

"state" values on auth0 login page and on my site after redirect are always different.

Angular: 13.0.2 (based on .NET 6 default project)
@auth0/auth0-angular: 1.8.0

**Comment by crhistianramirez** [comment]
Finally tracked down the root cause. My application was being bootstrapped twice, once in main.ts and then again in app.module.ts. This was essentially causing the handleRedirectCallback to be erroneously called twice.

@EvgenStudent you shouldn't need to explicitly call handleRedirectCallback, the library does that for you. I'm guessing that is why you are seeing the error because both you and the library call it and the second time it is identified as an error.
