### ISSUE TITLE
Support Angular 13 

### ISSUE THREAD

**Issue by riknv** [auth0/auth0-angular#250]
It' will be nice if this library support Angular 13. The latest version of this library raises some warnings from when running `yarn`.

```
warning " > @auth0/auth0-angular@1.8.0" has incorrect peer dependency "@angular/core@>=9 <=12".
```
And Ivy compatible
```
Processing legacy "View Engine" libraries:
- @auth0/auth0-angular [es2015/esm2015] (git+https://github.com/auth0/auth0-angular.git)
- @auth0/auth0-angular [main/umd] (git+https://github.com/auth0/auth0-angular.git)
Encourage the library authors to publish an Ivy distribution.
```

Actually this library still working well with Angular V13, and it's great if we could fix it.

I don't know how much efforts for removing the upgrading, but if someone could do it..it's so nice :)

**Comment by stevehobbsdev** [comment]
Support has been added in https://github.com/auth0/auth0-angular/pull/243 and should appear in a release very soon 👍🏻
