### ISSUE TITLE
Using auth0-angular in incognito/safari throws login_required and looses the token on subsequent logins

### ISSUE THREAD

**Issue by vitali-kviatkouski** [auth0/auth0-angular#251]
### Describe the problem

Using auth0-angular in incognito/safari throws login_required and looses the token on subsequent logins
with refresh token configuration like:
{
    domain: 'xxx',
    clientId: 'xxx',
    audience: 'xxx',
    useRefreshTokens: true,
    cacheLocation: ('localstorage' as CacheLocation),
    httpInterceptor: {
      allowedList: [{
        uri: '<all-urls>',
        allowAnonymous: true
      }],
    }
  }

### What was the expected behavior?

Subsequent logins in incognito / safari works fine, no login_required exceptions thrown, token stored in localStorage and retrieved using getTokenSilently

### Reproduction

1. Add support of auth0 with configuration above + add auth0-angular HttpInterceptor as anonymous to all routes
2. Login first time with auth0 - works fine
3. Login second and subsequent times - user not logged in, access token absent in localStorage
- reproducible not reliably, depends on how quickly iframe loads (see guess on the error cause below)

My guess this is related to concurrency issues:

Probably root cause is Auth0Client.getTokenSilently called from AuthHttpInterceptor before handleRedirectCallback+oath2 token retrieval completes its work.

Seems like app can send requests to server (wrapped in Auth0 AuthHttpInterceptor) before handleRedirectCallback retrieves the oath2 token after successful login. With such scenario AuthHttpInterceptor will try first load token from localStorage, but it's not there as interceptor could be called before handleRedirectCallback + oauth2 token retrieval finally complete. So it won't find access token in localStorage and then try to get it using iframe - and for incognito mode this attempt will always fail resulting in login_required expcetion. which in turn calls logout() method wiping the token from localStorage if it is there. Key point here iframe login_required can be thrown AFTER handleRedirectCallback+oauth2 token finally provision token to localStorage - and exception effectively wipe it out.
Probably need to order the sequence of actions or make AuthHttpInterceptor wait until handleRedirectCallback + oauth2 token provision logic complete its work

### Environment

- auth0-angular 1.8.0 + auth0-spa-js 1.19.2
- Safari/Incognito Chrome latest version
- Angular 12

**Comment by frederikprijck** [comment]
Thanks for reporting this. I will try and look into this as soon as possible.

Would you perhaps have a reproduction example app available that we can look into?

**Comment by frederikprijck** [comment]
Typically, u can use the `isLoading$` observable and wait until it emits false. This allows you to guarantee `handleRedirectCallback` is called before doing any other work that needs access to the SDK. It's hard to tell that that's causing the behavior, but I am happy to look into a more detailed reproduction sample.

Closing for now, feel free to reply and we can reopen.
