### ISSUE TITLE
Uncaught Error: Type AuthModule does not have 'ɵmod' property.

### ISSUE THREAD

**Issue by ewencodes** [auth0/auth0-angular#252]
### Describe the problem

Cannot add AuthModule.

```js
Uncaught Error: Type AuthModule does not have 'ɵmod' property.
```

```js
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AuthModule } from '@auth0/auth0-angular';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    AppRoutingModule,
    AuthModule.forRoot({
      clientId: '***',
      domain: '***',
    }),
  ],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

### On Chrome
<img width="525" alt="Screen Shot 2021-12-03 at 4 51 24 PM" src="https://user-images.githubusercontent.com/46159873/144631951-db8e17ad-24ee-45ef-8828-f1f3d2e5758c.png">

### On Firefox Developer
<img width="464" alt="Screen Shot 2021-12-03 at 4 52 11 PM" src="https://user-images.githubusercontent.com/46159873/144632067-5bf165c6-f036-45c8-9b78-13987377c12b.png">

The weird thing is that emod is well defined...
```js
import { ModuleWithProviders } from '@angular/core';
import { AuthConfig } from './auth.config';
import * as ɵngcc0 from '@angular/core';
export declare class AuthModule {
    /**
     * Initialize the authentication module system. Configuration can either be specified here,
     * or by calling AuthClientConfig.set (perhaps from an APP_INITIALIZER factory function).
     * @param config The optional configuration for the SDK.
     */
    static forRoot(config?: AuthConfig): ModuleWithProviders<AuthModule>;
    static ɵfac: ɵngcc0.ɵɵFactoryDeclaration<AuthModule, never>;
    static ɵmod: ɵngcc0.ɵɵNgModuleDeclaration<AuthModule, never, never, never>;
    static ɵinj: ɵngcc0.ɵɵInjectorDeclaration<AuthModule>;
}

```

### Environment

> Please provide the following:

- **Version of `auth0-angular` used:** ^1.8.0
- **Which browsers have you tested in? ** Firefox Developer, Chrome
- **Which version of Angular have you tested with?** 13

**Comment by ewencodes** [comment]
I think it's cause by pnpm. With yarn it's working fine. Sorry for this unnecessary issue!

**Comment by ahmed-abdulmoniem** [comment]
I am using yarn and this is always happening as well @ewencodes 

Now I am totally blocked!

**Comment by AlexanderNZ** [comment]
I'm getting this same issue with the same setup as originally described, except with version 1.8.1 of the library. Is there a fix for this coming?
