### ISSUE TITLE
Bower installs the latest version of auth0.js which contains breaking changes

### ISSUE THREAD

**Issue by gnandretta** [auth0/auth0-angular#258]
As reported in auth0/auth0.js#155, running
```
bower install auth0-angular
```
installs auth0.js 7.0.0 which was released yesterday and includes breaking changes.

**Comment by steve-baer** [comment]
Just had to fork and lock the version. Surprised that the bower dependency definitions are so optimistic.

**Comment by abanctelchevrel** [comment]
A temporary workaround is to explicitly require auth0.js in your angular app bower.json (add the second line in code below): 
```
    "auth0-angular": "^4.1.0",
    "auth0.js": ">= 6.8.3 < 7.0",
```
This will resolve auth0.js to v6.8.3
