### ISSUE TITLE
App stalls for an extended period of time after trying to authorize after logout

### ISSUE THREAD

**Issue by crhistianramirez** [auth0/auth0-angular#258]
### Describe the problem
Building off of [this issue](https://github.com/auth0/auth0-angular/issues/257) trying to get auth0 to work with capacitor. I am 99% of the way there but seeing a peculiar issue where after logging out if the user closes their application and opens it again they get a white screen. When opening the console I see a 400 to the /authorize endpoint and it isn't until about 30 seconds later that my auth guard gets hit and finally redirects the user to the login screen so they can re-authenticate. It seems like two things are happening that shouldn't 

1. Authorize is being called even after the user has logged out
2. The error event isn't being propagated immediately which stalls the app for much longer than it should

### What was the expected behavior?
I would expect the error to bubble up quickly so that the user doesn't see a white screen for longer than they need to.

### Reproduction

1. Clone [this repo](https://github.com/crhistianramirez/auth0repro)
2. Add `domain` and `clientId` to [src/environments/environment.ts](https://github.com/crhistianramirez/auth0repro/blob/main/src/environments/environment.ts#L7-L8)
2. Run `npm install` to install dependencies
3. Run `npm run build` to build application
4. Add `com.auth0.samples://carmmunity-dev.auth0.com/capacitor/com.auth0.samples/callback` to your auth0 Allowed Callback Urls
5. Add `com.auth0.samples://carmmunity-dev.auth0.com/capacitor/com.auth0.samples/callback` to your auth0 Allowed Logout Urls
6. Add `capacitor://localhost` to your auth0 Allowed Origins (CORS) settings
7. Run `npx cap run android` to run on native platform=
8. When first navigating to application you will be redirected to login page, go ahead and login
9. Click log out
10. Hard close application
11. Try to open application and see that you are presented with a white screen, the app is stalled. About 30 seconds later you should be redirected to the login page.

### Environment

- **Version of `auth0-angular` used:** The sample app uses `^1.5.1` but I have reproduced on most current version (`1.8.0`)
- **Which browsers have you tested in?** Chrome
- **Which version of Angular have you tested with?** 11.2.0
- **Other modules/plugins/libraries that might be involved:** capacitor, ionic

**Comment by crhistianramirez** [comment]
By the way, the 400 I am seeing is "the specified redirect_uri does not have a registered origin". I posted about it [here](https://community.auth0.com/t/silent-authentication-fails-on-capacitor-app-with-error-the-specified-redirect-uri-does-not-have-a-registered-origin/74440) but I suspect I'm just getting an incorrect error message because I can successfully build an authorizeUrl and logoutUrl which uses that redirect uri.

**Comment by frederikprijck** [comment]
Hey @crhistianramirez,

Sorry for the delay here. 

> Add capacitor://localhost to your auth0 Allowed Origins (CORS) settings

Did you follow our guide for Ionic and Angular, which you can find at https://auth0.com/docs/quickstart/native/ionic-angular#configure-origins ?

Specifically, for android, you need `http://localhost`. `capacitor://localhost` is for iOS.

Can you verify this helps?

**Comment by frederikprijck** [comment]
Closing this as no more response. Feel free to reply and we can always reopen!

**Comment by crhayes** [comment]
@crhistianramirez Did you ever resolve this issue? I am experiencing the same issue right now.

**Comment by crhistianramirez** [comment]
@crhayes I never fixed the issue. By the time @frederikprijck followed up I had already moved on from the project and no longer have access to the code. If you're still able to recreate and create a minimal reproducible example it is probably worth opening a new issue. @frederikprijck is very kind and helpful, he assisted me in other issues.

**Comment by frederikprijck** [comment]
Thanks @crhistianramirez !

@crhayes  feel free to open another issue and provide a reproduction. Be also sure that you have followed [the quickstart to intergrate Auth0-Angular in an ionic application](https://auth0.com/docs/quickstart/native/ionic-angular).
