### ISSUE TITLE
On latest Chromium 96, isAuthenticated$ returns false, /token is never called while logged in

### ISSUE THREAD

**Issue by hypesystem** [auth0/auth0-angular#261]
### Describe the problem

There is a discrepancy between latest Firefox and Chrome on Windows + Firefox on Ubuntu and latest Chromium on Ubuntu.

When logged in and performing a hard refresh on a page in Chromium on Ubuntu, the authService.isAuthenticated$ returns false even if the user is logged in.

Without a hard refresh the user can navigate to the same page and get true. Performing *just* a ctrl+f5 results in the value being false, but the login in still remembered by Auth0 when logging in (so that happens instantly).

Interestingly we cannot reproduce the error in latest Firefox on Ubuntu or on any browser we have tested on Windows 😕 

### What was the expected behavior?

authService.isAuthenticated$ should resolve to the value `true` when the user is logged in, even after a hard refresh.

### Reproduction

I don't know what to add here, I think I've covered the setup above. Let me know if you want more details - I haven't had time to build a minimal reproduction (as it is a bit complex to get to that point), but I thought I would still report it here :smile:

### Environment

> Please provide the following:

- **Version of `auth0-angular` used:** 1.8.1
- **Which browsers have you tested in?** Firefox+Chrome on Windows; Firefox+Chromium on Ubuntu
- **Which version of Angular have you tested with?** 9.1.4
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by hypesystem** [comment]
I might have time to add a reproduction in a few days, let me know if that's needed for you :smile:

**Comment by frederikprijck** [comment]
> I haven't had time to build a minimal reproduction

Could you try and see if you can reproduce this with our example app? https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01

Are you perhaps using Chrome in incognito or are 3rd party cookies blocked ?

**Comment by hypesystem** [comment]
Ah you are right! Chromium was in incognito and that was the difference -- we get the same behavior in Firefox Windows incognito. We just didn't realize this was the behavior here!

Thanks for the quick response, and sorry for wasting your time!
