### ISSUE TITLE
External URL blocked

### ISSUE THREAD

**Issue by chpalatinus** [auth0/auth0-angular#263]
Using Ionic, when I call this.auth.loginWithRedirect() on desktop, everything works fine (redirectionto Auth0) and I can log in properly.
But I when I test the Android app, I get an error "Blocked (possibly sub-frame) navigation to non-allowed URL".
What am I doing wrong?

My config.xml file contains:
`<content src="index.html" />
    <access launch-external="yes" origin="*://*.auth0.com/*" subdomains="true" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-navigation href="*://*.auth0.com/*" />
    <preference name="Scheme" value="https" />`

**Comment by frederikprijck** [comment]
Hello,

Have u looked at our guide for using Ionic and Angular https://auth0.com/docs/quickstart/native/ionic-angular?
If not, there is also an example application you can download on that page, would that have the same behavior for you?

Thanks

**Comment by frederikprijck** [comment]
Closing this as no-reply. Feel free to comment if you need further assistance and we can reopen.
