### ISSUE TITLE
Bug when using Custom Login with redirect (auth0.js v7.0.1)

### ISSUE THREAD

**Issue by viniciusmelquiades** [auth0/auth0-angular#263]
I noticed a strange behavior on my `loginSuccess` event. The injected idToken parameter would be `undefined` and the `profilePromise` would fail. The same properties on the `auth` service would also have the same problems. 
While trying to find out what the problem was, I figured out it would also not work if I tried to use the redirect mode, and the *sign in as user* feature would not work, both ending with a hash in my URL and doing nothing with it. 

After a long debug session, I found the problem with the following lines: (src/services/auth0.service.js line 179)
```Javascript
// Redirect mode
$rootScope.$on('$locationChangeStart', function() {
  if (!config.initialized) {
    return;
  }

  var hashResult = config.auth0lib.parseHash($window.location.hash);
  if (!auth.isAuthenticated) {
    if (hashResult && hashResult.id_token) { // < HERE IS THE PROBLEM
      onSigninOk(hashResult.id_token, hashResult.access_token, hashResult.state, hashResult.refresh_token);
      return;
    }
  }
});
```

It looks like in auth0.js v7.x the `hashResult.id_token` doesn't exist. Instead it's `hashResult.idToken`. The same problem occurs with the access_token and refresh_token, but only id_token seems to cause the problem. This causes the whole process to fail. 
auth0.js v6.x works just fine.

We can believe we can fix the whole problem, and keep it working with older versions by replacing the **if** I mentioned with the following code:
```javascript
    if (hashResult && (hashResult.idToken || hashResult.id_token)) {
      onSigninOk(hashResult.idToken || hashResult.id_token, hashResult.accessToken || hashResult.access_token, hashResult.state, hashResult.refreshToken || hashResult.refresh_token);
      return;
    }
```

This kind of problem could be happening in other places of the code, but I didn't look for them.

**Comment by christiannwamba** [comment]
Hey @viniciusmelquiades 

Auth0 really appreciate the feedback. I will reproduce the problem and fix them following your detailed guideline. Thanks again

**Comment by uded** [comment]
Any movement on this? This is breaking change in that auth.js v7.x have introduced. That should be fixed or more restrictive dependency (v6.8.x) should be included rather than allowing automatic update to new one...

**Comment by christiannwamba** [comment]
Hey @uded 

This is more a heads up. We are working on this issue already and hope to push ASAP

**Comment by sakopov** [comment]
Bump. Any updates on this?

**Comment by SomaYarlagadda** [comment]
I agree with @uded When would you have the fix for breaking changes. The automatic update to v7.x has caused lot of issues. Please update us on the status. Thank you.

**Comment by christiannwamba** [comment]
Fixed and available in next release. Thanks @viniciusmelquiades
