### ISSUE TITLE
auth.signin doesn't work with auth0 v7.0

### ISSUE THREAD

**Issue by justinbwarner** [auth0/auth0-angular#268]
I believe this issue is similar to #263. The auth.signin method is not working correctly with auth0.js v7.0 because the parameters for the callback are different. Specifically these lines in auth0-angular.js, line 592:

                    var successFn = !successCallback ? null : function(profile, idToken, accessToken, state, refreshToken) {
                        if (!idToken && !angular.isUndefined(options.loginAfterSignup) && !options.loginAfterSignup) {
                            successCallback();
                        } else {
                            onSigninOk(idToken, accessToken, state, refreshToken, profile).then(function(profile) {
                                if (successCallback) {
                                    successCallback(profile, idToken, accessToken, state, refreshToken);
                                }
                            });
                        }
                    };

The idToken (and accessToken, state, and refreshToken) are now a property of the first parameter (profile) and not in the subsequent parameters of the callback. Because of this the calls to onSigninOk and the successCallback don't have the correct parameters.

**Comment by christiannwamba** [comment]
Hi @justinbwarner 
Once #268 is reviewed and merged, you will be good to go. Thanks
