### ISSUE TITLE
Redirect to login page when route is protected

### ISSUE THREAD

**Issue by MadEddieFFS** [auth0/auth0-angular#271]
I tried and tried to find code/examples for this as I felt sure there would be some but truely couln't find any.

I simply wanted to know how to have a login page (or "unauthorized") page which was unprotected (obviously) by a route guard. Should a user try to access a protected page - the AuthGuard should redirect them to this page.

**app-routing.module.ts**
````
import { AuthGuard } from '@auth0/auth0-angular';

const routes: Routes = [{
  path: 'login',
  loadChildren: () => import('./pages/login/login.module').then(m => m.LoginModule)
}, {
  path: '',
  component: LayoutComponent,
  canActivate: [AuthGuard],
  children: [
    {
      path: '',
      loadChildren: () => import('./pages/home/home.module').then(m => m.HomeModule)
    },
    {
      path: 'contacts',
      loadChildren: () => import('./pages/contacts/contacts.module').then(m => m.ContactsModule)
    },
````
I cannot find an example where I set this redirect for the AuthGuard

**Comment by frederikprijck** [comment]
Hey,

You can not configure our guard like this. Using our Guard will automatically redirect to Auth0 when the user is not authenticated but tries to access a protected route.

In the event that authentication wasn't successful, a `login_required` error will be emitted in the `error$` observable, which you can use to redirect to any `unauthorized` page.

If you need a more specific Guard, you can always roll your own guard based on our Guard https://github.com/auth0/auth0-angular/blob/master/projects/auth0-angular/src/lib/auth.guard.ts.

**Comment by MadEddieFFS** [comment]
Perfect - thanks for the help and advice
