### ISSUE TITLE
auth.signin still doesn't work with auth0 v7.0.2

### ISSUE THREAD

**Issue by sakopov** [auth0/auth0-angular#272]
In redirect mode, when trying to use the latest in master with auth0.js 7.0.2, onSigninOk throws "Cannot read property 'state' of undefined" on this [line](https://github.com/auth0/auth0-angular/blob/master/build/auth0-angular.js#L358). Both state and profile are undefined at runtime.

**Comment by christiannwamba** [comment]
Hi! Are you using CDN?

**Comment by sakopov** [comment]
Not using a CDN. I'm pulling auth0.js from bower and auth0-angular.js by pulling from master since 4.1.0 on bower is known not to work with the latest auth0.js.

**Comment by christiannwamba** [comment]
4.1.0 is not the latest version of the SDK. Can you use 4.2.1?

**Comment by sakopov** [comment]
This error occurs in 4.2.1 in conjunction with 7.0.2.

**Comment by christiannwamba** [comment]
Oh sorry. Was fixed here: https://github.com/auth0/auth0-angular/pull/270/commits/591f8bb9751e6d45028e3c522b11d451d3580a78

Will be available in the next release.

**Comment by sakopov** [comment]
I'm not sure if this is a fix for this problem. The problem starts here in auth0.service.js on this [line](https://github.com/auth0/auth0-angular/blob/master/src/services/auth0.service.js#L232) which passes the state from the URL hash to `onSigninOk` but not the profile object. `onSigninOk` always expects the state to be passed in, but it was never returned from auth0 because it was never passed to auth0 during the signin call.

**Comment by sakopov** [comment]
As a quick workaround either passing an empty object for profile from `$locationChangeStart` handler:

    onSigninOk(
        hashResult.idToken || hashResult.id_token, 
        hashResult.accessToken || hashResult.access_token, 
        hashResult.state, 
        hashResult.refreshToken || hashResult.refresh_token, 
        {});

Or checking that profile object is available before trying to use it in `onSigninOk` seem to resolve the issue:

    var onSigninOk = function (idToken, accessToken, state, refreshToken, profile, isRefresh) {
        idToken = idToken || (profile ? profile.idToken : null);
        accessToken = accessToken || (profile ? profile.accessToken : null);
        state = state || (profile ? profile.state : null);
        refreshToken = refreshToken || (profile ? profile.refreshToken : null);

       ...
    }

**Comment by DigitallyBorn** [comment]
This has actually disabled the login to our website. Is there a workaround we can deploy to address this issue?

**Comment by christiannwamba** [comment]
This issue is a breaking change caused by Auth0.js 7. Will update very soon. Thanks

**Comment by christiannwamba** [comment]
Fixed https://github.com/auth0/auth0-angular/commit/8e3271a6247e3e15e48ef5004b7731146523acf0 . Let me know if any other issue

**Comment by patlux** [comment]
Please upload **4.2.3** with this change to npm. Currently @4.2.2.
