### ISSUE TITLE
AccessDenied for CDN resource

### ISSUE THREAD

**Issue by idanb11** [auth0/auth0-angular#273]
Hello,

when trying to get this - https://cdn.auth0.com/w2/auth0-angular-4.min.js

I get AccessDenied...

This used to work until a few hours ago....

Cheers.

**Comment by Bekt** [comment]
+1

We've made a hotfix to link to https://cdn.auth0.com/w2/auth0-angular-4.js

**Comment by christiannwamba** [comment]
Fixed https://cdn.auth0.com/w2/auth0-angular-4.min.js

**Comment by Bekt** [comment]
Do you have information on what had happened?

I imagine this affected large number of users.

**Comment by christiannwamba** [comment]
Nothing actually went wrong. The build missed to include the min version. Thanks

**Comment by Bekt** [comment]
Okay, please do consider the affects you may have when you offer something via a CDN (or any service for that matter) next time you release a new version. I think this particular could have been avoided if somebody verified the files exist after the build.

This caused our entire front-end app to crash affecting a lot of users. Can't afford this from auth0 as a paying customer 👍
