### ISSUE TITLE
API Documentation does not document the API

### ISSUE THREAD

**Issue by benwozniak** [auth0/auth0-angular#274]
### Describe the problem you'd like to have solved

I would like to use the Auth0 Angular SDK. I would like to know how to use the SDK beyond the quickstart tutorial.

### Describe the ideal solution

API documentation for the package is made available.

## Alternatives and current work-arounds

I have none. If I want to, for example, see what options I can configure in the `AuthModule`, I don't know where to look.

### Additional context

<img width="169" alt="no_doc" src="https://user-images.githubusercontent.com/12916756/151254801-75926839-bb6a-400f-90be-6310f55138d8.png">
"API Reference" just links back to the current page.
The Quickstart guide is the same content that is displayed on this page.

**Comment by frederikprijck** [comment]
The 'API Reference' link is not a link back to the current page, it links to our API docs using Typedoc: https://auth0.github.io/auth0-angular/

**Comment by benwozniak** [comment]
Hi, that is the page I am talking about. That page does not contain much API documentation. It contains a quickstart guide and some common scenarios but nowhere can I find documentation on what I can use this API/SDK for.

If you take a look at the screenshot I added to the ticket, I am on the page you linked. When I click on 'API Reference' it is the same page that you just linked to. For example, what are all of the options I can pass into the `AuthModule` when configuring it via `forRoot()`? I can't find it in the docs. If I am mistaken, I apologize, a link to there would be helpful.

**Comment by frederikprijck** [comment]
Yes, the main page is exactly the same as our readme.

However, on the right side, you can see all our files, e.g. clicking on `auth.service` should eventually have you end up here: https://auth0.github.io/auth0-angular/classes/auth_service.authservice.html, where you can see our AuthService and all of its properties and methods.

If you are looking for ways to actually use the SDK, we have a list of use-cases explained in the readme: https://auth0.github.io/auth0-angular/index.html#getting-started

Would that help ?

**Comment by benwozniak** [comment]
Oh my!! Yes that is so helpful. I use a vertical screen and I didn't notice the files on the right. Thank you for pointing me to what I need.
