### ISSUE TITLE
Cypress tests stopped working with cors error after update to 1.8.2

### ISSUE THREAD

**Issue by duvet86** [auth0/auth0-angular#275]
### Describe the problem

Cypress tests stopped working after updating @auth0/auth0-angular to 1.8.2

### What was the expected behavior?

The cypress tests to continue working.

### Reproduction

After updating to @auth0/auth0-angular@1.8.2 the cypress tests that try to reload the page using the command cy.reload() have stopped working.
![image](https://user-images.githubusercontent.com/5604548/151501673-65804c3d-cecf-4fc1-a4f4-08acf5bd7c52.png)
![image](https://user-images.githubusercontent.com/5604548/151501713-b3b05843-cf9b-4eb5-8d08-fee35abaadab.png)

```
before(() => {
    cy.navigateToApp();
    cy.login(utils.username, utils.pwd);
  });

  beforeEach(() => {
    cy.reload();
    cy.url().should((url) => {
      expect(url.endsWith('/admin')).to.be.true;
    });
    utils.siteAssignPage.getPageTitle().should('be.visible');
    utils.commonElement.getLoadingSpinner().should('not.exist');
  });
```

### Environment

- **Version of `auth0-angular` used: "@auth0/auth0-angular": "1.8.2",
- **Which browsers have you tested in? Chrome
- **Which version of Angular have you tested with? "@angular/core": "13.1.3",
- **Other modules/plugins/libraries that might be involved: Cypress@7.7.0

**Comment by frederikprijck** [comment]
Hey,

CORS is an issue that is to be solved on the backend, I am not sure how a change in our SDK would impact any of this. 

What version of our SDK did it work with? And can you verify it still works ?

Would it be possible for you to share an example app that reproduces this? That would be very helpful.

Thanks

**Comment by duvet86** [comment]
It worked with version 1.7.0, we updated to 1.8.2 and a couple of tests that use `cy.reload()` have started to fail. I have investigated the issue and when the page reloads the `_getTokenFromIFrame` runs trying to get the token using an iFrame which gets blocked by cypress. Thing is we did not update cypress but only the auth0 angular sdk.
We worked around the issue using the localstorage cacheLocation.

**Comment by frederikprijck** [comment]
The `_getTokenFromIFrame` being called when the page loads has been in there for quite a while actually. So if I understand you correctly, that method isn't triggered when u use Angular 1.7.0? As far as I know, that method should also be called in previous versions. 

If you could move one of those failing tests in a blank project that reproduces the behavior, I would be happy to look at it and see what's causing it.

Given[ our own e2e tests are using Cypress](https://github.com/auth0/auth0-angular/blob/master/projects/playground/e2e/integration/playground.spec.ts), I do believe it should still work using Cypress. . Have you compared your cypress config with [ours ](https://github.com/auth0/auth0-angular/blob/master/cypress.json)?

**Comment by duvet86** [comment]
The issue was due to Chrome updating itself and enforcing [Cross Origin Opener Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy). 
Have a look at the Caution section here: https://web.dev/coop-coep/
Setting 'Cross-Origin-Opener-Policy' to 'same-origin-allow-popups' fixed the issue, but that's porbably a workaraound.

**Comment by duvet86** [comment]
Please disregard. I had updated helmet js to the latest version and it now enforces cors isoled policy.
Reverting helmet to the previous version fixed the issue.
