### ISSUE TITLE
Error: profile is undefined

### ISSUE THREAD

**Issue by ainestal** [auth0/auth0-angular#276]
I'm getting this error when running the code from grunt so I can see the code: 

`"Error: profile is undefined
this.$get</onSigninOk@http://0.0.0.0:9000/bower_components/auth0-angular/build/auth0-angular.js:363:21
this.$get</<@http://0.0.0.0:9000/bower_components/auth0-angular/build/auth0-angular.js:405:29
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@http://0.0.0.0:9000/bower_components/angular/angular.js:12181:15
$locationWatch/<@http://0.0.0.0:9000/bower_components/angular/angular.js:9207:15
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://0.0.0.0:9000/bower_components/angular/angular.js:11906:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://0.0.0.0:9000/bower_components/angular/angular.js:11734:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://0.0.0.0:9000/bower_components/angular/angular.js:12012:13
bootstrap/doBootstrap/<@http://0.0.0.0:9000/bower_components/angular/angular.js:1299:9
invoke@http://0.0.0.0:9000/bower_components/angular/angular.js:3697:14
bootstrap/doBootstrap@http://0.0.0.0:9000/bower_components/angular/angular.js:1297:1
bootstrap@http://0.0.0.0:9000/bower_components/angular/angular.js:1311:1
angularInit@http://0.0.0.0:9000/bower_components/angular/angular.js:1260:5
@http://0.0.0.0:9000/bower_components/angular/angular.js:20534:5
jQuery.Callbacks/fire@http://0.0.0.0:9000/bower_components/jquery/jquery.js:3048:10
jQuery.Callbacks/self.fireWith@http://0.0.0.0:9000/bower_components/jquery/jquery.js:3160:7
.ready@http://0.0.0.0:9000/bower_components/jquery/jquery.js:433:1
completed@http://0.0.0.0:9000/bower_components/jquery/jquery.js:104:4`

After minifiying I have this error:
`TypeError: Cannot read property 'refreshToken' of undefined`

The versions I'm using are:
"angular": "1.2.6",
"jquery": "~1.10.2",
"auth0-angular": "^4.2.3",

Everything was working and suddenly didn't work anymore. I upgraded from 4.1.0 to 4.2.3 in case it would help but without any luck.

**Comment by bojank** [comment]
this commit 8e3271a was not included in the build for some reason. just go to your bower_components/auth0-angular/build folder and modify the file to include those changes manually until they make a new release with them

**Comment by ainestal** [comment]
After modifying the file in lines 360 and 614 with the code from the commit looks like it works again, thank you !

I hope this commit get's included soon. Currently I'm developing using 2 different computers and I'm not committing bower_components. That means I have to do this change manually in both computers and avoid touching the module at all afterwards

**Comment by mamluka** [comment]
+1

**Comment by cyxou** [comment]
+1 it took me two days to figure out this myself until I found this issue

**Comment by rajibahmed** [comment]
This is not properly fixed for when you are not using refreshToken.

**Comment by christiannwamba** [comment]
Thanks. Duplicate #274
