### ISSUE TITLE
Any plan for auth0-angular2?

### ISSUE THREAD

**Issue by xinbenlv** [auth0/auth0-angular#277]
Hi I am trying to getToken() of firebase like this link 
https://github.com/auth0/auth0-ionic/blob/master/examples/firebase-sample/www/js/controllers.js#L15

But I am on angular2, I realize the auth.getToken is available through auth0-angular2. Is there a plan for auth0-angular2?

(by the way, https://github.com/auth0/auth0-angular2/ currently seems an example repo)

**Comment by kukicado** [comment]
Try this: https://github.com/auth0/angular2-jwt :)

**Comment by xinbenlv** [comment]
thank you, but I am using Auth0Lock, how do I use it with angular2-jwt to get api token for firebase?

**Comment by ntotten** [comment]
@xinbenlv: We currently support angular 2, but this repo is specifically for angular 1. Checkout our quickstarts here: https://auth0.com/docs/quickstart/spa/angular2. We just updated everything to use Angular 2 RC4.

**Comment by xinbenlv** [comment]
Thanks!


Zainan Victor Zhou 周载南
Software Engineer at Google
Email: zzn@zzn.im
Phone: (650) 336-5691
微信号（WeChat ID） xinbenlv
Alumni of Tsinghua, Hopkins, Microsoft Research Asia
Linkedin www.linkedin.com/in/zainanvictorzhou
