### ISSUE TITLE
Auth0 Lock not visible on wrong configuration

### ISSUE THREAD

**Issue by boly38** [auth0/auth0-angular#278]
Hi all,
I'm using this configuration

    <script type="text/javascript" src="//cdn.auth0.com/js/lock-9.0.js"></script>
    <script type="text/javascript" src="//cdn.auth0.com/w2/auth0-angular-4.js"></script>

And to load Auth0 widget, I'm initializing AngularJS App like this:

    (...)
    authProvider.init({
      domain: aDomain,
      clientID: aCid,
      loginUrl: '/login'
    });

And "auth.signin(..)" in my controller.

For some reason, on my side, I had an invalid value in auth0 client ID : a white char at the end (a CR or LF - I'm not sure).

In that case, on "signin(..)" call, I have a very strange behavior:
- no error on javascript console,
- no auth0 widget visible,
- auth0 widget was loaded partially and is staying invisible.

It was really hard to debug. I suggest to report a log or an error in this use case to avoid end-user to loose their time on this common error.

Regards

**Comment by christiannwamba** [comment]
Hi! This might be Lock related but I tried replicating the issue and got a reasonable error with a log in the console.
<img width="1196" alt="screen shot 2016-07-08 at 8 45 39 am" src="https://cloud.githubusercontent.com/assets/8108337/16680758/d81062f4-44e8-11e6-88a5-1f2f2a586339.png">

**Comment by boly38** [comment]
Hi, thanks for trying to reproduce @christiannwamba !
In same time I fix another issue where I loaded twice my LoginController. So I will try to reproduce without this controller issue to see if I get the same result as you.

**Comment by christiannwamba** [comment]
Ok that make sense. Feel free to re-open if you get another issue. Thanks

**Comment by boly38** [comment]
Hey @christiannwamba please re-open (seems I cant ?)

Even with fix on controller I was able to reproduce.
Here is a way I use to reproduce under. 
if you comment the first line; all is fine, auth0 lock is showed.
else the first line add a carriage return to auth0 client id: auth0 lock widget is partially created (and not visible).

```` 
aCid = aCid + String.fromCharCode(13);
authProvider.init({
      domain: aDomain,
      clientID: aCid,
      loginUrl: '/login'
    });
```` 

If I'm alone to produce this result, I have maybe another things in my context that have some side effect..

**Comment by christiannwamba** [comment]
Hi @boly38. I strongly think this should be a problem with Lock itself not the Auth0-Angular so I will create an issue in Lock and reference this. Hope you are fine with that?

**Comment by boly38** [comment]
I agree @christiannwamba Thanks!

**Comment by christiannwamba** [comment]
Ok cool. Please keep me posted on your findings.

**Comment by boly38** [comment]
I was unable to find working sample auth0-angular + Lock10.

**Comment by christiannwamba** [comment]
Hi @boly38 

You can make use of the QuickStarts: https://github.com/auth0-samples/auth0-angularjs-sample

**Comment by boly38** [comment]
out of my project context, I clone your samples
- I copy "01-Login" onto webserver
- I update app.js (around line 24)

```` 
    //Configure Auth0
    var aCid = AUTH0_CLIENT_ID;
    aCid = aCid + String.fromCharCode(13);
    authProvider.init({
      domain: AUTH0_DOMAIN,
      clientID: aCid,
      loginUrl: '/login'
    });
```` 
Without modification, your sample works well and show lock widget (after javascript "shown" alert).
With additional character 13 at the end of client id string, the lock widget became visible (after javascript "shown" alert) and stay in "loading" state indefinitively:
(nothing special in developer's view: network or JS console..)

![auth0loading](https://cloud.githubusercontent.com/assets/3100576/16729207/36feb48a-476b-11e6-8757-ad0f6e9d1f28.JPG)
