### ISSUE TITLE
Auth issues after mail verification

### ISSUE THREAD

**Issue by Teacup5000** [auth0/auth0-angular#280]
### Describe the problem

When user is authenticated and the email status becomes verified, silent token refresh will fail, moreover when calling `loginWithRedirect()`, the logged in user gets logged out with a failed token refresh log, instead of being sent to the login page.

Hence there seems to be no procedure after the user verifies his email.

### What was the expected behavior?

Call `getAccessTokenSilently` to successfully refresh the auth token, or call `loginWithRedirect()` to either successfully reauthenticate the user or to send the user to the Auth0 login page 

Or alternatively, give any other option to refetch the Auth0 user object, or any other option to refresh the token or to force a relogin.

Otherwise, there is no possibility to reflect the updated user email verified status in Angular.

### Reproduction

1. Sign up user with `loginWithRedirect()`
2. Verify email via magic link of the verification mail
3. Call `getAccessTokenSilently()` or `getAccessTokenSilently({ignoreCache: true})` which causes a silenttoken refresh error, or `loginWithRedirect()` which will not refresh the user nor send the user to the login page, but force a logout with silenttoken refresh error.

### Environment

- Auth0 Angular SDK v1.8.2.
- Firefox
- Angular 12

**Comment by frederikprijck** [comment]
Hey @Teacup5000,

Sorry for the delay here. 

> When user is authenticated and the email status becomes verified, silent token refresh will fail, moreover when calling loginWithRedirect(), the logged in user gets logged out with a failed token refresh log, instead of being sent to the login page.

Can you elaborate here? loginWithRedirect shouldn't log people out: https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L628-L633

Important to note here is that there are certain reasons `getTokenSilently` can fail and will throw an error such as `login_required`.

Our SDK doesn't handle these errors for you, as every application will require different handling here (some might want to redirect to login, others might want to redirect to another page the have, or some might even want to do something totally different).

Therefore, it's typically a good idea to catch errors that getTokenSilently throws and react accordingly, in this case being doing a loginWithRedirect.

**Comment by frederikprijck** [comment]
Closing this as no more response. Feel free to reply and we can always reopen!
