### ISSUE TITLE
Refresh token on 401 API response

### ISSUE THREAD

**Issue by Lonli-Lokli** [auth0/auth0-angular#288]
**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

### Describe the problem you'd like to have solved
Handle situation when token has been expired during external API call

> A clear and concise description of what the problem is. It's possible (especially as there is no token prefetch) that token will be expired during API call, so on UI it might be ok, while API during validation will fail.

### Describe the ideal solution

HttpInterceptor should handle 401 error and try to refetch silently new token

### Additional context

https://github.com/auth0/auth0-angular/blob/master/projects/auth0-angular/src/lib/auth.interceptor.ts

**Comment by frederikprijck** [comment]
Can you give a bit more information about your situation? What is the lifetime of your Access Token?

Our SDK is configured to automatically refresh access tokens 60 seconds before they expire. So whenever our interceptor kicks in, it will ask our underling SDK for an access token. If this access token is expiring in the next 60 seconds, we will throw it away and get a new one. That new one is used for the request.

I am not sure I understand how it can expire while in transit. So would be great if you can help us understand your situation and see what's causing it.

**Comment by Lonli-Lokli** [comment]
@frederikprijck thanks for clarification, I didn't know Auth0 client has prefetch functionality.

Btw have you tested scenario with token ttl less than 60sec?

**Comment by frederikprijck** [comment]
@Lonli-Lokli Yes, we tested that and it will not behave correctly. You should put a TTL of > 60sec (but definitely don't use things like 61). I would stick to 5 to 10 minutes as a minimum.
