### ISSUE TITLE
Type: Failed Silent Auth. Description: Multifactor authentication required

### ISSUE THREAD

**Issue by xstation1021** [auth0/auth0-angular#296]
### Describe the problem
Some users are redirected back to new universal login page after they successfully completed username + password & MFA authentication are completed.
The logs show "Type: Failed Silent Auth. Description: Multifactor authentication required".
The log history is usually 
Failed Silent Auth
Success Exchange
Success Login
OTP Auth Succeed

This happened to only some users. Not all the users.
A user could login after they successfully logged in & redirected to universal login page 4 times.
Users could login to the app when they set up MFA. However, they face this issue when they login next time. 
When they use incognito, they can login.

### What was the expected behavior?

"Failed Silent Auth" shouldn't happen if it's after they go through the login process.

### Reproduction
Angular code: useRefreshTokens & cacheLocation are added
```
 AuthModule.forRoot({
      domain: '',
      clientId: '',
      audience: '',
      redirectUri: '',
      useRefreshTokens: true, 
      cacheLocation: 'localstorage',
```

Auth0 Settings:
Require Multi-factor Auth: Never
Token Expiration: 10 hours.
Application id token expiration: 10 hours
Refresh Token Rotation enabled.

Auth0 pipeline rule. (only some users use MFA so we added this rule)
```
 context.multifactor = {
                provider: 'any',
                allowRememberBrowser: false
            };
```

Custom domain is not enabled yet.

auth0Auth.isAuthenticated$
this returns true first then false.
When it returns false, we call loginWithRedirect. (acr_values was added today, but it didn't fix)

``` 
this.auth0Auth.loginWithRedirect({
          appState: { },
          acr_values: 'http://schemas.openid.net/pape/policies/2007/06/multi-factor'
      });
```

### Environment

Environment
Angular 12
auth0-angular version: 1.9.0
Chrome (Windows 10)

**Comment by frederikprijck** [comment]
> "Failed Silent Auth" shouldn't happen if it's after they go through the login process.

With MFA there are a few things that can cause issues.

A typical one is that the user has not `checked` the "Remember this device for 30 days" for the MFA.
That together with a tenant setting that says MFA is always required, will ensure our SDK is unable to do Silent Auth.

However, it looks like this isnt the situation here based on the information you provided.

However, by setting allowRememberBrowser to false, you are getting the same behavior, being: you don't allow our SDK to use silent auth.

There has to be something that triggers a silent auth request, which could always happen.
I believe it's definetly a good idea for you to catch these errors and call `loginWithRedirect` to react to MFA_required errors.

That said, would u be able to provide a small reproduction sample, I would be happy to see what's causing it.

**Comment by xstation1021** [comment]
Hello. So adding the code below fixed the issue.
```
   const completedMfa = !!context.authentication.methods.find(
        (method) => method.name === 'mfa'
      );
```
I am not sure why some users didn't have any issues before.

I cannot provide a reproduction sample because this issue didn't happen to anyone in my team.

**Comment by frederikprijck** [comment]
I am not sure I understand why that would be a fix you want to use.

However, happy it solved it for you.
