### ISSUE TITLE
 auth0-angular repo/bower package that supported AngularJs 1.x apps has been removed

### ISSUE THREAD

**Issue by venkateshkandasamy** [auth0/auth0-angular#30]
Hey all,

I believe this repo previously housed the SDK that supported AngularJs 1.x apps. Though the SDK is still available in npm under the same name ( https://www.npmjs.com/package/auth0-angular ), it has been removed from the bower. Our app which is based on AngularJS 1.5 still uses the old SDK. 

Would like to know whether this is intentional and said NPM package will be removed in the future?

**Comment by stevehobbsdev** [comment]
Hi @venkateshkandasamy, we apologise that this has happened. While the intention was to repurpose this repository for a brand-new SDK that serves Angular 9+ developers, we did **not** intend to upset any existing published assets and failed to take that into account when we made the change. To answer your question, while we intend to deprecate the existing NPM package, we do not intend to remove it from NPM entirely.

As a next step I would like to find out from you whether any of the alternatives to bower would work for you? We have the NPM package and we also still have the SDK available:

- **NPM:** https://www.npmjs.com/package/auth0-angular
- **CDN:** https://cdn.auth0.com/w2/auth0-angular-4.2.js

Let me know, as we're keen to work out the next steps.

**Comment by venkateshkandasamy** [comment]
Thanks, Steve! We are fine as long as the NPM source is available. Renaming either the old or the new package might also help to avoid the confusion because currently, npm install auth0-angular and bower install auth0-angular would result in different SDKs.

**Comment by stevehobbsdev** [comment]
Thanks @venkateshkandasamy - yes I appreciate the confusion. The new one will be scoped - `@auth0/auth0-angular`.

Glad to head you're unblocked!
