### ISSUE TITLE
Cannot instantiate cyclic dependency! AuthService

### ISSUE THREAD

**Issue by QingLiTR** [auth0/auth0-angular#302]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

> After change to use Dynamic Configuration following the page below, we get errors on "cannot instantiate cyclic dependency!AuthService" on the page refresh/reload. The configuration set properly and it works only when redirected through the login route.

https://auth0.github.io/auth0-angular/

### What was the expected behavior?
No error should caused by page reload once user already logged in.

> Tell us about the behavior you expected to see

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

1. Change to use APP_INITIALIZER to set the AuthModule configurations.
In app.module.ts file add the APP_INIITALIZER service and the factory method.
const configInitializer =
  (
    appConfigService: AppConfigService,
    handler: HttpBackend,
    authClientConfig: AuthClientConfig
  ) =>
  () =>
    appConfigService.loadAppConfig(handler, authClientConfig);

providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: configInitializer,
      deps: [AppConfigService, HttpBackend, AuthClientConfig],
      multi: true
    }
]

2. Create a model class to represent the structure of app config.
export abstract class AppConfig {
  domain: string;
  clientId: string;
  audience: string;
  connection: string;
  baseUrl: string;
  scope: string;
  redirectUri: string;
  logoutUri: string;
}

3. Create an AppConfigService class to invoke http request to get the configurations from json file.

import { Injectable } from '@angular/core';
import { HttpBackend, HttpClient } from '@angular/common/http';
import { AuthClientConfig } from '@auth0/auth0-angular';
import { AppConfig } from './app-config';
import { AllowedServer } from '../_models/allowed-server';

@Injectable({
  providedIn: 'root'
})
export class AppConfigService extends AppConfig {
  loadAppConfig = (handler: HttpBackend, authClientConfig: AuthClientConfig) =>
    new HttpClient(handler)
      .get<AppConfig>('assets/app_config.json')
      .toPromise()
      .then((config) => {
        this.domain = config.domain;
        this.clientId = config.clientId;
        this.audience = config.audience;
        this.connection = config.connection;
        this.baseUrl = config.baseUrl;
        this.scope = config.scope;
        this.logoutUri = `${window.location.origin}/logout`;
        this.redirectUri = `${window.location.origin}/login`;

        const allowedServer: AllowedServer = {
          uri: `${config.baseUrl}/*`
        };
        authClientConfig.set({
          domain: config.domain,
          clientId: config.clientId,
          audience: config.audience,
          connection: config.connection,
          redirectUri: this.redirectUri,
          logoutUri: this.logoutUri,
          scope: config.scope,
          useRefreshTokens: true,
          httpInterceptor: {
            allowedList: [allowedServer]
          }
        });
      })
}

4. Leave AuthModule.forRoot() configuration as empty.
AuthModule.forRoot()

If so, provide steps:

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of `auth0-angular` used:  1.9.0
- **Which browsers have you tested in? Google Chrome Version 100.0.4896.75 (Official Build) (x86_64)
- **Which version of Angular have you tested with? Angular: 9.1.13
- **Other modules/plugins/libraries that might be involved: NA

**Comment by frederikprijck** [comment]
Thanks for reporting this, I tried reproducing this but haven't been able to do so using the code provided. Would you be able to try and see if you can reproduce it in our sample application https://github.com/auth0-samples/auth0-angular-samples ?

If you can reproduce it, it's easier to share it with us so we can understand what's causing it.

**Comment by frederikprijck** [comment]
Closing because of no response. Can always reopen if needed
