### ISSUE TITLE
auth0-spa-js v1.21.0 version

### ISSUE THREAD

**Issue by Dannnir** [auth0/auth0-angular#303]
Hi,
What is the process of upgrading the `auth0-spa-js` dependency?
I would like the v1.21.0 version.
[Release v1.21.0 (](https://github.com/auth0/auth0-spa-js/commit/ab3ed5b11b92330b5c35f417bc79b2a5bf564fcc)https://github.com/auth0/auth0-spa-js/pull/891[)](https://github.com/auth0/auth0-spa-js/commit/ab3ed5b11b92330b5c35f417bc79b2a5bf564fcc)

Thanks!

**Comment by frederikprijck** [comment]
Would u be able to install auth0-spa-js 1.21.0 explicitly, alongside of auth0-angular?

To be able to use this without explicitly installing auth0-spa-js, we will need to update our dependency list.

**Comment by Dannnir** [comment]
@frederikprijck What is the process of updating the dependency list?    we have around 10 apps and I would like to avoid doing it twice.
Thanks!

**Comment by Dannnir** [comment]
I see the snyk bot did the commit, I just need a new release tag.

**Comment by frederikprijck** [comment]
I don't believe you need any release here. running `npm install @auth0/auth0-angular` will already include `@auth0/auth0-spa-js` 1.21.0, without cutting a new release (Sorry, I was wrong earlier when I told you that you do need a new release). So you can upgrade our SDK, or re-install it (whatever works for you) if you are already on the latest. Doing so should pick up the latest SPA-JS automatically.

But yes, you willl need to do this for your 10apps, just like you would update any other dependency.

Closing as there is no action from our end (and the PR from Snyk is not needed for what you are asking).
