### ISSUE TITLE
Universal Login Redirection of blocked users canceled internal navigation

### ISSUE THREAD

**Issue by anschm** [auth0/auth0-angular#311]
In my application i am using the universal login. If a user is blocked and tries to login the universal login redirects the user to the callback url extended with: 

/?error=unauthorized&error_description=user%20is%2zODJNLllhUmtUaUZ0aV9fY3BndnFUbEdibGhKaXVGSw%3D%3D

Auth0 also returns an error.

In the auth.service.ts i found the following code starting from line 100.

this.shouldHandleCallback()
      .pipe(
        switchMap((isCallback) =>
          checkSessionOrCallback$(isCallback).pipe(
            catchError((error) => {
              const config = this.configFactory.get();
              this.authState.setError(error);
              this.navigator.navigateByUrl(config.errorPath || '/');
              return of(undefined);
            })
          )
        ),
        tap(() => {
          this.authState.setIsLoading(false);
        }),
        takeUntil(this.ngUnsubscribe$)
      )
      .subscribe();

This code navigates to '/' or to the errorPath given in the configuration. But it doesn't work in this case. The navigation is starten but after that the navigation is canceled, because of the redirect from the universal login. In this case its not possible to configurare another path to navigate if an error occurred. I thinks this is a bug.

But additionally I want to navigate to a page if the user is blocked to show that the user. Because the universal login doesn't show that. Is there a option on auth0 to configure a redirect url for blocked users? Currently I am listen on the error$ observable and redirects manuelly. This is not working because of the redirect from the universal login. My internal navigation is also canceled.

**Comment by frederikprijck** [comment]
> This is not working because of the redirect from the universal login. My internal navigation is also canceled.

Can you elaborate why that isn't working? I don't think I understand. For what I know, this is supposed to be working. Any chance you can share a reproduction?

**Comment by anschm** [comment]
I am listen on the erro$ observable from the auth service and handle the error like:

  private handleError(ctx: StateContext<AuthStateModel>, e: GenericError): void {
    ctx.patchState({ error: e });
    if (e.error === 'unauthorized' && e.error_description === 'user is blocked') {
      ctx.dispatch(new Navigate(['accounts/blocked']));
    }
  }

If the user is blocked I would like to navigate to accounts/blocked. But the navigation is canceled. In the screenshots you can see the error is handled and the navigation to accounts/blocked is triggert. After that the navigation is canceled and the navigation to the error redirect uri is triggert. In this case I cannot navigate to my specific page to show that the user is blocked because the redirect navigation is triggered secondly.

![Bildschirmfoto 2022-06-22 um 17 54 52](https://user-images.githubusercontent.com/79454810/175077650-461f7db3-8bc6-4a21-99af-ae94b83a1ac4.png)

![Bildschirmfoto 2022-06-22 um 17 55 22](https://user-images.githubusercontent.com/79454810/175077561-5a533826-4aca-47f0-996a-094be9842a3e.png)

**Comment by frederikprijck** [comment]
Thanks, I think I know what's happening. I will need to look into this and see how we can solve this.

**Comment by anschm** [comment]
@frederikprijck  thanks for taking a look on this issues. Do you have an update for me about the progress?

**Comment by anschm** [comment]
I checked the new release and the issues is still there.

**Comment by frederikprijck** [comment]
I could reproduce and fix it with the fix that got released on my end, so that could be related to code in your application, can you please share a reproduction sample so I can look into it and see if we need to patch something else or if it can be addressed in your project?

Thanks!

**Comment by anschm** [comment]
![Bildschirmfoto 2022-08-02 um 18 12 20](https://user-images.githubusercontent.com/79454810/182422563-167d43bf-a483-4952-8e72-2b7df8b01fe5.png)
![Bildschirmfoto 2022-08-02 um 18 12 08](https://user-images.githubusercontent.com/79454810/182422571-0f9dda2f-9c15-4c25-ba99-1905421034b4.png)

The screenshots shows that the last navigation which is done after listen on error is canceled.

**Comment by frederikprijck** [comment]
That screenshot isn't realy helpful to get our hands on what's happening in your application, could you please share a minimal reproduction that shows the behavior so I can look into it and see if the issue is inside the SDK?

**Comment by anschm** [comment]
I started working on a minimal reproducable example. You can find it under the following url:

https://stackblitz.com/edit/angular-ivy-4exios?file=src/app/app.module.ts

There is one issue that I cannot connect to auth0. The error is that the connection is refused. I dont know why. Maybe you have an idea?

**Comment by anschm** [comment]
I checked my example within a seperate browser and its working. I dont know why its not working inside the stackblitz browser. Take my example and change the credentials to use your tenant with a blocked user. Press login and enter the user credentials. After that you will redirected to the Hello-Page. Thats wrong, because inside the auth-state we listen on errors and navigate to the /example/blocked. So the Blocked-Page should be shown. But this navigation is canceled by the redirect from the server.

**Comment by frederikprijck** [comment]
Thanks, that's very helpful. I can reproduce it and will look into it.

**Comment by frederikprijck** [comment]
While in the process of investigating what's going on, I removed NGXS and used our AuthService directly, this seems to work as expected: https://stackblitz.com/edit/angular-ivy-ba8xfx 

Would that help indicating the difference between what you are doing and what I'm doing in that stackblitz?

**Comment by anschm** [comment]
Yes, I can confirm that. So I will take more investigation in that tomorrow and figure out whats the difference. Thanks for your help.

**Comment by anschm** [comment]
For now I figured out that if I remove the NGXS Router Plugin then all is working correctly. Its seems there is any other navigation which is handled by the NGXS Router Plugin and which cancels all other inner navigation. @frederikprijck could this navigation from the outside the redirect from the server?

**Comment by anschm** [comment]
Finally I found the following code within the ngxs router plugin:

    const subscription = this._router.events
      .pipe(first((event): event is RoutesRecognized => event instanceof RoutesRecognized))
      .subscribe(({ url }) => {
        // `location.pathname` always equals manually entered URL in the address bar
        // e.g. `location.pathname === '/foo'`, but the `router` state has been initialized
        // with another URL (e.g. used in combination with `NgxsStoragePlugin`), thus the
        // `RouterNavigation` action will be dispatched and the user will be redirected to the
        // previously saved URL. We want to prevent such behavior, so we perform this check

        // `url` is a recognized URL by the Angular's router, while `currentUrl` is an actual URL
        // entered in the browser's address bar
        // `PathLocationStrategy.prototype.path()` returns a concatenation of
        // `PlatformLocation.pathname` and normalized `PlatformLocation.search`.

        // `Location.prototype.normalize` strips base href from the URL,
        // if `baseHref` (declared in angular.json) for example is `/en`
        // and the URL is `/test#anchor` - then `_locationStrategy.path(true)` will return `/en/test#anchor`,
        // but `/en/test#anchor` is not known to the Angular's router, so we have to strip `/en`
        // from the URL
        const currentUrl = this._location.normalize(this._locationStrategy.path(true));
        const currentUrlTree = this._urlSerializer.parse(currentUrl);
        // We need to serialize the URL because in that example `/test/?redirect=https://google.com/`
        // Angular will recognize it as `/test?redirect=https:%2F%2Fwww.google.com%2F`
        // so we have to run the `currentUrl` via the `UrlSerializer` that will encode characters
        const currentSerializedUrl = this._urlSerializer.serialize(currentUrlTree);

        // If URLs differ from each other - we've got to perform a redirect to the manually entered URL
        // in the address bar, as it must have a priority
        if (currentSerializedUrl !== url) {
          this._router.navigateByUrl(currentUrl);
        }
      });

It seems that the router plugin takes the first event and this is the redirect from the auth0 server and overrides all other taken inner navigations with high priority. Thats why the navigations are canceled after catching the error.

**Comment by anschm** [comment]
@frederikprijck I think I found out why this all happens. So there is no task for you and this issue can be closed.
