### ISSUE TITLE
exception thrown in firefox during signin using custom login

### ISSUE THREAD

**Issue by jgangemi** [auth0/auth0-angular#317]
i'm getting the following exception in firefox when i try to `signin` via a custom login page.
```
[Exception... "<no message>"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: http://localhost:9009/vendor/auth0.js/build/auth0.js :: getRequest :: line 3931"  data: no]
http://localhost:9009/vendor/auth0.js/build/auth0.js
Line 3931
```
i don't see this problem w/ chrome or safari and it happens for both the callback and event handler implementations.

using angular 1.5.8 and this is the relevant portion of my `bower.json`
```
    "auth0.js": "7.0.3",
    "auth0-angular" : "~4.2.3",
    "a0-angular-storage":"~0.0.15",
    "angular-jwt": "~0.0.9"
```
please let me know what other information i can provide. thanks!

**Comment by jgangemi** [comment]
bueller?!?!

this issue is delaying an integration i am trying to roll out, thanks!!

**Comment by jgangemi** [comment]
i will also note that when using `lock` i get an error stating it can't reach the backend server (which may be a red herring). chrome and safari work without issue here as well.

**Comment by jgangemi** [comment]
grr - this ultimately was caused by privacy badger, nothing to see here after all.

**Comment by baerrach** [comment]
Google found this page for me, and it was definitely a privacy badger issue. Thanks.
