### ISSUE TITLE
Provide user data if error is thrown

### ISSUE THREAD

**Issue by anschm** [auth0/auth0-angular#321]
Actually we are deny the login for users which have not verified here email adresse with a action. We need some information in the application about the user (user id, email adress, name etc.). But there is no solution to transfer user information within the error. it would be great to throw a error within a action in auth0, catch the error inside the app by using the error$ observable from the auth service and have some user information.

**Comment by frederikprijck** [comment]
We can only use the information that's available from Auth0 Server.
In the case of an error, Auth0 doesn't give us any user information so our SDK can not include that.

**Comment by anschm** [comment]
Okay, and is not possible to exend the auth0 server to provide this information?

**Comment by frederikprijck** [comment]
Not that I am aware of, but general feedback can always be provided at https://auth0.com/feedback
