### ISSUE TITLE
How to add custom social connection link to Lock?

### ISSUE THREAD

**Issue by idanb11** [auth0/auth0-angular#323]
Hi,

I'm trying to add a custom social connection link/button to the Lock UI.
In Auth0 [docs ](https://auth0.com/docs/hrd#option-3-adding-custom-buttons-to-lock) you need to call - `lock.once('signin ready', function() ...` but when using auth0-angular the link variable doesn't exist...

So How exactly do I add a custom social connection link/button to the Lock UI???

Thanks for your help.

**Comment by idanb11** [comment]
nobody???  :-)

**Comment by runes83** [comment]
Trying to find it also, but no luck so far.

**Comment by ashishdasnurkar** [comment]
Please try this

```
authProvider.auth0lib.on('signin ready', function() {
     var link = angular.element('<a class="a0-zocial a0-sharepoint" href="#"><span>Login with Steam</span></a>');
     var iconList = angular.element(document.querySelector('.a0-iconlist'));
     iconList.append(link);
     link.on('click', function() {
         authProvider.auth0lib.getClient().login({connection: 'Steam'});
     });
  });
```

**Comment by runes83** [comment]
That worked, but as a side note why does not these (custom connections) show up as the other connections? Much easier if everything could be administered from the portal (Auth0) instead of adding custom code.

**Comment by ashishdasnurkar** [comment]
Glad to hear it worked. And you make great suggestion. Could you post a enhancement request on auth0-lock repo?
