### ISSUE TITLE
constructorInfo.constructor is not a constructor

### ISSUE THREAD

**Issue by gpicazo** [auth0/auth0-angular#334]
Getting error:

`constructorInfo.constructor is not a constructor` when trying to initialize my authProvider. I am using webpack and typescript. I am only using auth0, not auth0-lock since I have custom forms.

Here is the configuration class where the error occurs:

    export default class Auth0Config {
        static $inject:Array<string> = ['authProvider'];

        constructor(authProvider:auth0.angular.IAuth0ServiceProvider) {
            authProvider.init({
                domain: 'mydomain.auth0.com', // this value is replaced with my real domain
                clientID: 'myClientID', // this value is replaced with my real client ID
                loginUrl: '/auth/login'
            });
        }
    }

Any help would be greatly appreciated.

**Comment by gpicazo** [comment]
Anyone?

**Comment by Zeychiel** [comment]
Hi,

Same error since a new npm i, after working fine for a year.
I am using it with browserify and AngularJS

**Comment by Zeychiel** [comment]
I solved it by downgrading to a <10.0.0 version (9.2.2).
auth0-lock ^10.0.0 is not supported yet by Angular #313

**Comment by gpicazo** [comment]
Closing this issue. The problem was that I was including an npm package called "auth0" instead of "auth0-js".

**Comment by Amialc** [comment]
As you can see [here](https://github.com/auth0/auth0-angular/blob/master/README.md#deprecation-notice) there is [angular-lock](https://github.com/auth0/angular-lock) package that support lock v10.
