### ISSUE TITLE
cannot read property 'refreshToken' of undefined

### ISSUE THREAD

**Issue by razlani** [auth0/auth0-angular#353]
![image](https://cloud.githubusercontent.com/assets/4509685/25383376/2b39be52-29ff-11e7-959e-4a0cf3ff37d1.png)

Hi all,

I'm signing in with:

`                    lock.show({
                        auth: {
                            params: {
                                scope: 'openid offline_access',
                                device: 'kek'
                            }
                        }
                    });`

And listening for the event and, once the event is triggered, storing some data with angular store

`lock.on('hash_parsed',
                        function (authResult) {
                            if (!authResult) {
                                $state.go('login');
                                return;
                            }.....`

But when I try to call auth.refreshIdToken(refreshToken) with a valid refreshToken, I get the error as per screenshot attached.

In auth0-angular line ln587, it doesn't seem to have a auth0js attached to the config:

`                auth.refreshIdToken = function(refresh_token) {
                    var refreshTokenAsync = authUtils.promisify(config.auth0js.refreshToken, config.auth0js);....`

Am I missing a step or is this a bug?

/**
 * Angular SDK to use with Auth0
 * @version v4.2.7 - 2016-10-31
 * @link https://auth0.com
 * @author Martin Gontovnikas
 * @license MIT License, http://www.opensource.org/licenses/MIT
 */

**Comment by cmddavid** [comment]
Having a similar problem here, config.auth0js also undefined:
`jQuery.Deferred exception: config.auth0js is undefined this.$get</auth.refreshIdToken@http://localhost:9000/bower_components/auth0-angular/src/services/auth0.service.js:395:25`

**Comment by cmddavid** [comment]
@razlani, how did you fix this problem?

**Comment by razlani** [comment]
@cmddavid I used angular-auth0 v 2 and the renew auth method to silently authenticate.

Good luck dude!
