### ISSUE TITLE
Create auth0 client lazily

### ISSUE THREAD

**Issue by oschlegel** [auth0/auth0-angular#354]
### Describe the problem you'd like to have solved

> Following szenario: I'm using dynamic configuration for auth0 and i'm using ngx-translation for internationalization. The translations are a json file which is loaded from the cdn during bootstrap of the application.
> The problem: When the translations are loaded the auth0 http interceptor is instantiated and with it the auth0 client, even though the request needs no authorization.

### Describe the ideal solution

> The auth0 client used by the interceptor should be instantiated when the first request is sent, which needs authentication. This way it is easier to use dynamic configuration feature of auth0.

## Alternatives and current work-arounds

> A workaround would be to not use http service of angular for requests that need to be made before the dynamic configuration has been set.

**Comment by frederikprijck** [comment]
Thanks for reaching out.

If I understand correctly, you are using `HttpClient` to retrieve translation files. These can be requested before the user is authenticated, however our interceptor kicks in, which might not be desired.

This is expected and can be solved in two ways:

- Configure our `AuthModule` in such a way that it will not try and attach any token to the requests for the translation files by configuring which requests it should attach a token to more explicitly, see : https://github.com/auth0/auth0-angular#configure-authhttpinterceptor-to-attach-access-tokens
- Do not inject `HttpClient`, but instantiate a `new HttpClient` with an injected `HttpBackend` as shown in https://github.com/auth0/auth0-angular#dynamic-configuration, this is useful when using an APP_INITIALIZER. If not, I would go with configuring the AuthModule's interceptor configuration.

Can you see if that would work ?

**Comment by oschlegel** [comment]
> Configure our AuthModule in such a way that it will not try and attach any token to the requests for the translation files by configuring which requests it should attach a token to more explicitly, see : https://github.com/auth0/auth0-angular#configure-authhttpinterceptor-to-attach-access-tokens

This will not solve this issue. Angular instantiates all providers for `HTTP_INTERCEPTORS` as soon as the first request is sent and `AuthHttpInterceptor` and `Auth0ClientService` is built in a way that the configuration is required when the interceptor is instantiated

> Do not inject HttpClient, but instantiate a new HttpClient with an injected HttpBackend as shown in https://github.com/auth0/auth0-angular#dynamic-configuration, this is useful when using an APP_INITIALIZER. If not, I would go with configuring the AuthModule's interceptor configuration.

I don't know how interceptors are instantiated in this case

**Comment by frederikprijck** [comment]
When u use `new HttpClient(httpBackend)`, where httpBackend is injected into the class, it will bypass all interceptors. This is a common pattern used when you want to do an HTTP request that's required for configuration, such as environmental settings or translations. 

Definetly not ideal, but not uncommon for these scenario's and needed with the current state of the SDK.

Having said that, I want to leave this issue open as I believe there are opportunities to try and improve for our next major version.

**Comment by frederikprijck** [comment]
Closing this, as I believe this is possible using [Dynamic Configuration](https://github.com/auth0/auth0-angular#dynamic-configuration).

If you believe otherwise and there are any changes we can make that would make things easier, we are always open to discuss.
