### ISSUE TITLE
Upgrade @auth0/auth0-spa-js from 1.22.* to 2.0.0

### ISSUE THREAD

**Issue by sjacaspuig** [auth0/auth0-angular#363]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### @Auth0/auth0-spa-js has released a new major version with important changes to the packages that will fix issues that currently exist with the current version.

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Upgrade @Auth0/auth0-spa-js to the latest version (2.0.0) and refactor the code involved with the changes.

> A clear and concise description of what you want to happen.

### Do nothing, continue to use the version currently installed in the project.

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

### I propose to upgrade that package (@auth0/auth0-spa-js) because I've a lot of issues with the integration of this package (@auth0/auth0-angular) with my own project so I think If you upgrada that package (@auth0/auth0-spa-js) this package (@auth0/auth0-angular) could work better and help me to solve the issues that I've.

> Add any other context or screenshots about the feature request here.

**Comment by ewanharris** [comment]
Thanks for raising this @sjacaspuig! 

We have plans to update the spa-js SDK this quarter alongside some other changes, however we don't have a timeline for this right now.

I'll leave this issue open for now as a tracking issue

**Comment by frederikprijck** [comment]
Hey @sjacaspuig ,

Could you elaborate on the issues you are currently experiencing that would be solved by including SPA-JS V2? I believe it would be good for us to understand the issue, and how it's solved for you with V2.

Thanks!

**Comment by frederikprijck** [comment]
This has been resolved in our beta branch through https://github.com/auth0/auth0-angular/pull/366.

There is no timeline on the beta release, but I would expect it to go out in the coming weeks.

Closing this, as the work has been done and will be available once the beta is released.
