### ISSUE TITLE
Avoid sending Bearer while following redirect

### ISSUE THREAD

**Issue by sgerme** [auth0/auth0-angular#387]
### Describe the problem you'd like to have solved

We are using a backend with a minio storage. When requesting some documents, we send a 302 redirect with a temporary URL to the front-end.

Despite the fact that the domain does not match any of the uri provided in the httpInterceptor.allowedList, the Bearer token is provided, resulting in a conflit with the minio server that sends back a 400 BadRequest. 

## Alternatives and current work-arounds

We have an alternative : proxy in front of minio to strip of Bearer Token headers. But that's not ideal.

**Comment by frederikprijck** [comment]
Thanks for reaching out, I don't believe this should be happening as our Interceptor should only add tokens to requests that match with the allowedList.

Could you provide more information about the configuration used for the interceptor, as well as the request URL that has a token attached while you believe it shouldn't be attached?

Thanks.

**Comment by sgerme** [comment]
So the request to the back end is a request for a document :  
- api.example.com/enterprise/{id}/document 
with a bearer
the response is a 302 redirect.

And the redirection has a Bearer token as well, but the domain is completely different : 
minio.anotherapi.com 
(sorry, can't give you the real examples here) 

We've tried removing the token by hand in a curl, it works. as long as we keep it : the response is still a bad request.





in the environment.ts we have : 
```
export const environment: Environment = {

    auth: authConfig,
    apiUrl: authConfig['apiUri'],
    appUrl: authConfig['appUri'],
    stripe: window['env']['stripe'],
    httpInterceptor: {
        allowedList: [  {
            uriMatcher: (uri) =>  uri.includes("api.example.com"),
        }
        ],
    },
```

and authConfig is defined :
```

const authConfig: AuthConfig = {

    httpInterceptor: {
        allowedList: [
            {
                uriMatcher: (uri) =>
                    uri.includes("api.example.com/register") && !uri.includes('begin'),
            },
            {
                uri: "api.example.com/users/*',
            },
            {
                uriMatcher: (uri) => uri.includes(`"api.example.com/calendar`)
            },
            {
                uriMatcher: (uri) => uri.includes("api.example.com/enterprise'),
            },
            {
                uri: "api.example.com/signing-authorities",
            },
            {
                uriMatcher: (uri) => uri.includes(`"api.example.com/messaging`),
            },
        ],
    },

};
```

and app.module.ts 
```

    imports: [
 AuthModule.forRoot({
            ...env.auth,
        }),
]

```

**Comment by frederikprijck** [comment]
Thanks, I have tried this myself and I can see it sends the Authorization header. However, I believe this isn't caused by our interceptor, but by the fact that the browser follows the redirect with the exact same headers.

I have set up a backend with one route:
- /api/external: This returns a 302 to `https://meowfacts.herokuapp.com/`

When I call `/api/external`, you can see the interceptor is only triggered for `api/external`, and not for the redirect call.

You can reproduce this behavior in native `XMLHttpRequest` (which Angular's `HttpClient` uses):

```ts
const req = new XMLHttpRequest();
req.addEventListener('load', function reqListener() {
   console.log(this.responseText);
});
req.open('GET', 'http://localhost:3001/api/external');
req.setRequestHeader('Authorization', 'Bearer ' + token);
req.send();
```

As well as with `fetch`:

```ts
const response = await fetch('http://localhost:3001/api/external', {
  headers: {
     Authorization: 'Bearer ' + token,
  },
});

const data = await response.json();
```

When using the above code, outside of Angular, you will notice the same behavior, being the `Authorization` header being set on the request to `https://meowfacts.herokuapp.com/`. This is a browser thing we can't realy solve in our SDK.

**Comment by sgerme** [comment]
thanks for ur answer ! Ill work on this.
