### ISSUE TITLE
No Refresh Token emit

### ISSUE THREAD

**Issue by olivierscheffler** [auth0/auth0-angular#395]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

During a PKCE Flow, I achieve the login and redirection to my angular app. When I ask for a token manually with 
this.auth.getAccessTokenSilently().subscribe(data => {
      console.log(data);
    })
I get a token but this one expires shortly after and when I try again the same function, no new token have been emit so I have only the old token.

### What was the expected behavior?

A new token should have been emit since the old is older and not valid anymore,

### Environment

> Please provide the following:

- **Version of `auth0-angular` used:** 1.10.1
- **Which browsers have you tested in?** Chrome
- **Which version of Angular have you tested with?** Angular 14
- **Other modules/plugins/libraries that might be involved:** No other module

**Comment by frederikprijck** [comment]
Thank you for reaching out.

Please provide a reproduction of the issue at hand, because the behavior you are describing is expected to work when you use the SDK. It should refresh tokens internally when expired.

Thanks.

**Comment by frederikprijck** [comment]
Closing as no response. Feel free to reply with a reproduction sample and we can take a look what's going on.
