### ISSUE TITLE
Auth0 SDK not compatible with Angular 9

### ISSUE THREAD

**Issue by azizajmeri45** [auth0/auth0-angular#401]
ERROR in ./node_modules/@auth0/auth0-angular/fesm2015/auth0-auth0-angular.js 101:190-208
"export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'   

ERROR in ./node_modules/@auth0/auth0-angular/fesm2015/auth0-auth0-angular.js 146:194-212
"export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'   

ERROR in ./node_modules/@auth0/auth0-angular/fesm2015/auth0-auth0-angular.js 238:161-179
"export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'   

ERROR in ./node_modules/@auth0/auth0-angular/fesm2015/auth0-auth0-angular.js 521:246-264
"export 'ɵɵFactoryTarget' (impo

**Comment by frederikprijck** [comment]
Thanks for reporting this. As mentioned in the [README](https://github.com/auth0/auth0-angular), we only support versions of Angular that are officially supported by Google, [which is only 13 or above](https://angular.io/guide/releases#actively-supported-versions). This means we do not support anything below Angular 13 with our latest versions.

We encourage you to upgrade to a supported version of Angular.

Having said that, u can pin your version of Auth0-Angular to `1.10.1`, that should work with Angular 9.
