### ISSUE TITLE
Android isAuthenticated$ does not fire

### ISSUE THREAD

**Issue by mikkimichaelis** [auth0/auth0-angular#405]
### Describe the problem
isAuthenticated$ does not fired for exactly 60 seconds consistently after the app is allowed to sit for several minutes while logged in.  I know this sounds ridiculous but it is what I am experiencing and desperately need help resolving it.

I’m using the Ionic Angular sample app located at https://github.com/auth0-samples/auth0-ionic-samples.

NOTE that if I install the app, launch it, login, close, and restart I do not see this behavior.  It is only after letting the app sit in a logged in state for a period of time that this issue shows up.

I just tested the React sample on the same Android device and it exhibits the same issue with an added twist.  The ‘Auth0 React Sample’ title does not even appear until 60 seconds after startup when the Login button shows.

I tested the React sample on an Android Emulator Pixel 3 API 29 and it exhibits the same issue as a device.

I have tested both the Angular and React sample app on the iOS platform with perfect functionality :-).

I have tested in browsers with success also.

### What was the expected behavior?

When app initially runs isAuthenticated$ should fire immediately with auth status.

### Reproduction
1. uninstall auth0-ionic-samples from android test device
2. clone this repo https://github.com/auth0-samples/auth0-ionic-samples
3. cd auth0-ionic-samples/angular
4. npm i
5. follow sample instructions and update auth.config.ts with domain and client id
6. ionic cap run android
7. app is running on android test device
8. Login
9. Leave app in the foreground for 5 minutes
10. Close app without Logout
11. run app

Login button will not be displayed as isAuthenticated$ does not fire
60 seconds later isAuthenticated$ fires and the Login button displays

Once this unusual behavior starts, it can not be stopped w/o an app uninstall

I am also not receiving my Auth0 profile pic properly as I do when running the sample app on iOS or web.

### Logcat

2022-12-23 23:42:42.150 7279-7350/com.auth0.samples W/chromium: [WARNING:display_webview.cc(31)] WebView overlays are enabled!
2022-12-23 23:42:43.748 7279-7279/com.auth0.samples I/Capacitor/Console: File: http://localhost/main.js - Line 207 - Msg: ios: false android: true
2022-12-23 23:42:43.749 7279-7279/com.auth0.samples I/Capacitor/Console: File: http://localhost/main.js - Line 209 - Msg: com.auth0.samples://meetingmaker.us.auth0.com/capacitor/com.auth0.samples/callback
2022-12-23 23:42:44.127 7279-7279/com.auth0.samples I/Capacitor/Console: File: http://localhost/vendor.js - Line 80521 - Msg: Angular is running in development mode. Call enableProdMode() to enable production mode.
2022-12-23 23:42:44.149 7279-7344/com.auth0.samples D/Capacitor: Handling local request: http://localhost/common.js
2022-12-23 23:42:44.149 7279-7336/com.auth0.samples D/Capacitor: Handling local request: http://localhost/node_modules_ionic_core_dist_esm_ion-app_8_entry_js.js
2022-12-23 23:42:44.156 7279-7279/com.auth0.samples V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 129665211, pluginId: App, methodName: addListener
2022-12-23 23:42:44.157 7279-7279/com.auth0.samples V/Capacitor: callback: 129665211, pluginId: App, methodName: addListener, methodData: {"eventName":"appUrlOpen"}
2022-12-23 23:42:44.169 7279-7344/com.auth0.samples D/Capacitor: Handling local request: http://localhost/src_app_home_home_module_ts.js
2022-12-23 23:42:44.492 7279-7336/com.auth0.samples D/Capacitor: Handling local request: http://localhost/assets/icon/favicon.png
2022-12-23 23:42:44.604 7279-7279/com.auth0.samples V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 129665212, pluginId: App, methodName: addListener
2022-12-23 23:42:44.605 7279-7279/com.auth0.samples V/Capacitor: callback: 129665212, pluginId: App, methodName: addListener, methodData: {"eventName":"backButton"}
2022-12-23 23:42:44.605 7279-7336/com.auth0.samples D/Capacitor: Handling local request: http://localhost/node_modules_ionic_core_dist_esm_index-0bc00b33_js.js
2022-12-23 23:42:44.605 7279-7344/com.auth0.samples D/Capacitor: Handling local request: http://localhost/node_modules_ionic_core_dist_esm_status-tap-20472ffa_js.js
**<app is loaded, home screen is blank>
<note here is the 60s delay>**
2022-12-23 23:43:44.803 7279-7331/com.auth0.samples D/Capacitor: Handling local request: http://localhost/node_modules_ionic_core_dist_esm_ion-button_2_entry_js.js
2022-12-23 23:43:44.806 7279-7344/com.auth0.samples D/Capacitor: Handling local request: http://localhost/assets/icon/favicon.png
2022-12-23 23:43:44.886 7279-7344/com.auth0.samples D/Capacitor: Handling local request: http://localhost/node_modules_ionic_core_dist_esm_ion-ripple-effect_entry_js.js

### Screenshots
![image](https://user-images.githubusercontent.com/78762019/211700187-db833a81-9121-4f07-852f-7c4e8fb2510d.png)
![image](https://user-images.githubusercontent.com/78762019/211706650-44566453-722a-453d-ac7b-0e5522707967.png)

### Environment

- **Version of `auth0-angular` used:**
"@auth0/auth0-angular": "^1.11.1”

- **Which browsers have you tested in?**
None, I’m testing on an Android physical device
moto g pure XT2163DL
Android Version 12

- **Which version of Angular have you tested with?**
"@angular/core": "^15.0.3”,

- **Other modules/plugins/libraries that might be involved:**
"rxjs": "^7.8.0”,
"typescript": "^4.8.2"

**Comment by frederikprijck** [comment]
Thank you for reaching out. I managed to reproduce this on Pixel 5 with API 32 as well.

I'll have a look to try and identify what's happening that's causing this behavior.

**Comment by mikkimichaelis** [comment]
Thank you so much for your attention to this.  I’m very relieved to know you are able to reproduce it.

**Comment by Oussie00** [comment]
I'm currently experiencing the same issue, it only occurs in my android application.

**Comment by Oussie00** [comment]
@mikkimichaelis have you tried to change the cache location to 'localstorage'? That seems to be a workaround for this issue.

**Comment by frederikprijck** [comment]
We have done some further debugging and believe we understand what's causing it, even though we are still looking into how we can resolve the behavior with the existing configuration, you should be able to avoid the behavior by:

- setting `useRefreshTokens` to `true`
- setting `useRefreshTokensFallback` to `false`, this will ensure iframes aren't being used to contact auth0, which is what we believe the thing that's not working and causing the issue you are experiencing.

This should avoid the error in the scenario you are experiencing @mikkimichaelis, could you try that?

However, this would not remember the user on refresh / closing and restarting the app. To avoid that, you could use `cacheLocation: 'localstorage'`, while we try and see if we can avoid this by ensuring iframes work as expected in ionic.

To be clear, the issue above is when combining our SDK using Ionic and not when used in a regular Angular application.

Thanks for catching and reporting this @mikkimichaelis, we will do some additional investigation but it might turn out that we need to update our docs to ensure we mention these things when combining our SDK with ionic.

**Comment by mikkimichaelis** [comment]
@frederikprijck I have implemented your suggestions and I now have an acceptable level of functionality.  Thank you for addressing this issue so quickly and providing a solution.  I greatly appreciate the work the Auth0 team has put into providing us these drop in solutions that work effectively.  As much time as I spent identifying this bug, I would have spent a whole lot more time implementing my own (buggy) auth client lib.  Many thanks!

**Comment by mikkimichaelis** [comment]
I wanted to note that today while implementing auth0/auth0-angular in the SPA version of my app I experienced this same issue.  I tested with the ionic [sample app](https://github.com/auth0-samples/auth0-ionic-samples) and to reproduce it simply log in then reload the page.  60 sec delay until login button is displayed.  I tested Chrome, Firefox , and Safari with the same results.  The solution provided fixed the issue.  I find it very interesting this issue does not exist when running on iOS.

**Comment by frederikprijck** [comment]
@mikkimichaelis That should have a different cause, be sure to check the Auth0 tenant logs. But my guess is you need to add `http://localhost:4200` to the Allowed Web Origins in the Application settings, as mentioned in https://auth0.com/docs/quickstart/spa/angular/interactive

> To be clear, the issue above is when combining our SDK using Ionic and not when used in a regular Angular application.

To be more accurate here, the issue only exists when not running in the browser. So only when running ionic on Android. Using ionic in the browser should work just fine without setting any of the above properties on the SDK, but does require a properly configured tenant.

**Comment by mikkimichaelis** [comment]
Thank you for your response @frederikprijck .  I hate to disagree with you, however what I am experiencing and can replicate in [auth0-ionic-samples](https://github.com/auth0-samples/auth0-ionic-samples) is the above reported issue.  I just verified this again, the issue exists when running Ionic/Angular in the browser.  Setting the values

`useRefreshTokens: true,
useRefreshTokensFallback: false,
cacheLocation: 'localstorage’`

resolves the issue in my browsers (chrome/firefox/safari).

I have my tenant properly configured for the ionic sample app and the login flow works just fine.  Meaning the initial login goes perfectly as expected.  Then refreshing the page will cause the 60 sec delay.

**Comment by frederikprijck** [comment]
@mikkimichaelis I can reproduce it as well, and I know your solution works. But the solution can be different here, and shouldn't require any of those settings, as in this case it should be a tenant misconfiguration. Did you verify that what I said also works?

I believe the behavior is the same, but the solution is different. 

The SDK should work without setting those 3 values when running in the browser. If it doesn't, it sounds like a tenant configuration issue. I agree it can still be mitigated with the 3 properties you mention, but that's not the recommendation. I would always ensure the tenant is configured correctly. I mean, you can still use those 3 settings, but not just to avoid the error you are seeing as that should not come up in the first place.

That said, yes if you need one solution to work both on browser and on Android, yes you need those 3 settings. But just to ensure we do not confuse people, this is still correct:

> To be more accurate here, the issue only exists when not running in the browser. So only when running ionic on Android. Using ionic in the browser should work just fine without setting any of the above properties on the SDK, but does require a properly configured tenant.

If we ignore the fact that it should also run in Android (as some people do use ionic for these kind of apps sometimes), there should be no need for these properties.

**Comment by frederikprijck** [comment]
> I have my tenant properly configured for the ionic sample app and the login flow works just fine. Except that once logged in a page refresh will cause the 60 sec delay.

Do you have any information in the Auth0 Logs? I was able to reproduce this using our Ionic sample, and fix it by ensuring my tenant is configured correctly. 

> I have my tenant properly configured for the ionic sample app 

You need to configure it for the Angular app, as mentioned in the link I shared. Because an Ionic app running in the browser behaves as a regular Angular app: https://auth0.com/docs/quickstart/spa/angular/interactive

As you can see, the configuration is slightly different.

In this case, as mentioned, I assume you do not have `http://localhost:4200` in your Allowed Web Origins, which will lead to the behavior you are experiencing.

**Comment by mikkimichaelis** [comment]
Can you tell me what was misconfigured in your tenant?

I have however found something more.  I’m experiencing this issue when serving from HTTPS using a development certificated as used when running

ionic serve --ssl

and configuring auth.config to instead use https://localhost:8100 and adding that allowed origins to my tenant config.

If I switch back to plain HTTP served on http://localhost:8100 and adding that also to allowed origins the problem goes away.

**Comment by mikkimichaelis** [comment]
To be clear I am not using port 4200 because the ionic-sample uses port 8100.  I’ve added both

http://localhost:8100
https://localhost:8100

as allowed origins.

I have removed the authService config of

`useRefreshTokens: true, useRefreshTokensFallback: false, cacheLocation: 'localstorage’`

when configuring the sample app’s auth.config.ts file with a web callback of

http://localhost:8100

and running the command

ionic serve

the app functions as expected

when configuring the sample app’s auth.config.ts file with a web callback of

https://localhost:8100

and running the command

ionic serve --ssl

I experience this issue.

**Comment by frederikprijck** [comment]
> Can you tell me what was misconfigured in your tenant?

The Allowed Web Origins. 

> If I switch back to plain HTTP served on http://localhost:8100/ and adding that also to allowed origins the problem goes away.

I guess you mean Allowed Web Origins, and not Allowed Origins? It are two different fields in the application.

> To be clear I am not using port 4200 because the ionic-sample uses port 8100.

I use `npm start` (as per our readme: https://github.com/auth0-samples/auth0-ionic-samples/tree/main/angular) and it runs it on 4200. But as long as you configure the correct port, that shouldn't matter.

~~Can you please take a look at the Auth0 logs and verify there are no errors showing up? On top of that, do you get any errors in the browser's console?~~ I was able to reproduce this on SSL without any errors on both sides, will look into it. Thanks!

**Comment by mikkimichaelis** [comment]
Ok, yes I may have something incorrectly configured and I am seeing now some errors in the tenant logs.  I apologize the confusion.  It’s 2:40am here and I’ve been working all day.  I need to eat and sleep and address this tomorrow.

Thanks for your help.

**Comment by mikkimichaelis** [comment]
I have corrected the configuration regarding Allowed Web Origins and the sample app is running as expected in the browser without the fix for this issue.

**Comment by frederikprijck** [comment]
Closing this, we updated the docs and sample for using this SDK with Ionic based on [my comment above.](https://github.com/auth0/auth0-angular/issues/405#issuecomment-1387675799)

Thanks again for reporting this, this will definetly help others!
