### ISSUE TITLE
Authentication struggles on iOS

### ISSUE THREAD

**Issue by davidobrien1985** [auth0/auth0-angular#406]
I am using auth0 free plan (for now).
I have an Angular SPA which is already using auth0 successfully, everywhere except on Apple devices.
On Chrome, Edge, all is well, on iOS I get weirdness.

I use `'@auth0/auth0-angular'` in my app.

In app.module.ts I initiate the client like so:
```
    AuthModule.forRoot({
      ...env.auth,
      useRefreshTokens: true,
      cacheLocation: 'localstorage',
      scope: 'openid email profile',
      httpInterceptor: {
        allowedList: [`*`],
      },
    }),
```
I first noticed issues when a dropdown menu on the first page (after login) didn’t populate with values from our backend APIs (other pages, without dropdowns are fine though).
Then, when users refresh the page they end up in a login loop. The page has lost the state it seems and thinks the user is not logged in, says they should log in (doesn’t redirect to auth0 anymore though) and just stops working.

In `home.component.ts`:

We use `isAuthenticated$ = this.authService.isAuthenticated$` from `import { AuthService } from '@auth0/auth0-angular';`.

In `home.component.html`:

```
<ng-template #unAuthenticated>
  <h2>Please log in from the menu.</h2>
</ng-template>
<div class="container" *ngIf="isAuthenticated$ | async; else unAuthenticated">
  <div class="row">
```

Again, this works as we expect everywhere, except Apple.

What are we missing here?

Thanks for your help!
David

**Comment by frederikprijck** [comment]
Thanks for reaching out.

Can you verify that the problems persists when using our [sample application](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) on iOS?

If it does, could you elaborate on what versions of iOS and Safari you are using?

**Comment by davidobrien1985** [comment]
I will need to test this.
Versions used are all over the place. It's been reported by multiple end users with iPhones and iPads.
My iPad uses the very latest updates of everything and has the issue.

I'll need a day or so to test the sample app, especially because it needs to be deployed. I'm on windows and can't simulate an Apple endpoint locally.

Can you confirm though that the code I pasted should work and there's nothing that wouldn't work on Apple?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by frederikprijck** [comment]
When running [our sample application](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) on an iOS 15 emulator using Safari, using the same config as you have:

```
useRefreshTokens: true,
cacheLocation: 'localstorage',
scope: 'openid email profile',
httpInterceptor: {
   allowedList: [`*`],
},
```

I'm not experiencing any redirect loop, refreshing the page automatically shows the user as logged in and stays on the page.

Please give that same sample application a try to see if the behavior persists or not, as that would be very helpful to try and understand what could be causing this.

**Comment by frederikprijck** [comment]
I am going to close this, but happy to look into this further if needed. Feel free to ping me when you'd have something more for me to look into, and we can always reopen.

**Comment by ssh-pereira** [comment]
Hi guys, I am having the same issue and was redirect from this issue: https://community.auth0.com/t/authentication-struggles-on-ios/98039/2

I have a reactjs application that works perfectly fine on computers and android, but on IOS it just does not work in any browser

I have opened an detailed issue here:
https://community.auth0.com/t/unable-to-configure-verification-page-when-on-incognito-or-other-computer/103885

But no comments so far

**Comment by frederikprijck** [comment]
@Hugo-Pereira-98 , this is the respository for our Angular SDK, I would recommend opening an issue in the appropriate repository.

However, I would lean towards opening an issue on [auth0-js](https://github.com/auth0/auth0.js/), and not auth0-react, as I do not believe the issue originates from our React SDK.

Given the fact that it does not work in Incognito and Safari, it sounds like it has something to do with third party cookies, can you verify before opening an issue?

**Comment by maurocolella** [comment]
@frederikprijck I am seeing something similar (once a day or more), but I just wanted to point out that we aren't using a specific client, just issuing requests to the API directly.

We will investigate the likelihood of this issue being related to Safari Incognito and tracking cookies. In the meantime, the discussion can be found here:
https://community.auth0.com/t/ios-refresh-auth-loop-on-safari/108504

**Comment by frederikprijck** [comment]
Thanks for reaching out. We cant help much from the SDK side as you aren't using our SDK. 

On top of that, this repository doesnt have API's for passwordless, so not sure about whether or not it relates to the issue being logged here.

I do see you mention on the community you have no idea where to report this.

Personally, i would provide a minimal reproduction sample on the community post you openend, makes it easier for anyone to step in. Currently, the community post has little information for anyone to work with.

There is also always the option for professional services, you can reach out to your Account Manager.

**Comment by kinizumi** [comment]
auth0 is not working on iphone, just tested

**Comment by ubirajaramnj** [comment]
I really don't understand why this ticket is closed. I'm facing exactly the same problem here, I tested many different configuration without success.

If anyone have any tip of how to solve this issue I would appreciated.

**Comment by frederikprijck** [comment]
@ubirajaramnj it's closed because the OP never got back and the rest is kinda unrelated.

Feel free to open an issue with the required context and we can have a look.

**Comment by GodOfFunder** [comment]
I also agree with @ubirajaramnj, this seems like avoidance. I am having the same issue. Every platform works great other than Apple. All items discussed are exactly what I am seeing. This ticket shouldn't be closed.

**Comment by jonschmidt** [comment]
Did anyone in this thread ever uncover anything? We have a few users who are extremely upset with our company because of this, as they just cannot use our app on iOS, and we are kind of at a loss as to how to move forward, except potentially away from auth0.
