### ISSUE TITLE
'redirectUri' link in README leads to 404 page

### ISSUE THREAD

**Issue by DreadedHippy** [auth0/auth0-angular#407]
### Describe the problem

> The 'redirectUri' link in the readme of the 'auth0-angular' repository as well as the docs, leads to a 404 page

### What was the expected behavior?

> I expected to click on the 'redirectUri' link and read about the 'redirectUri' option for 'loginWithRedirect()' function and possibly read on other options

### Reproduction
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- go to [auth0-angular github repo](https://github.com/auth0/auth0-angular)
 - Press 'Ctrl+ F' for 'Find in page'
 - Enter 'redirectUri'
 - Click on the 'redirectUri' link in the readme
 - You will arrive at [this](https://auth0.github.io/auth0-angular/interfaces/auth_config.authconfig.html#redirecturi) page, A 404 page.

**Comment by frederikprijck** [comment]
Thank you for letting us know! I opened a PR to address this.
