### ISSUE TITLE
Update to 2.0.0 breaks unit tests

### ISSUE THREAD

**Issue by Nightapes** [auth0/auth0-angular#412]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

After updating Auth0 Angular to 2.0.0 all jest tests are failing with error:

` ReferenceError: Cannot access 'AuthConfigService' before initialization`

If changing the order in `node_modules/@auth0/@auth0-angular/fesm2015/auth0-auth0-angular.mjs` so that 
`AuthConfigService` is before `AuthClientConfig.ɵfac` the tests are working 

### What was the expected behavior?

All exiting tests should work

### Environment

> Please provide the following:

- **Version of `auth0-angular` used:** 2.0.0
- **Which browsers have you tested in?** Jest Dom
- **Which version of Angular have you tested with?** 14.2.0
- **Other modules/plugins/libraries that might be involved:** Jest, Nrwl NX

**Comment by frederikprijck** [comment]
Thanks for reaching out.

I created [a branch](https://github.com/auth0/auth0-angular/tree/fix/export-order), could you verify these changes allow your tests to run successfully?

You will need to ensure you run:

- npm install
- npm run build
- cd dist/auth0-angular
- npm pack

Then run `npm install path/to/generated.tgz` in your project.

**Comment by Nightapes** [comment]
@frederikprijck I tested your changes and they are working. All our tests are now running. 

Thank you 👍

**Comment by Nightapes** [comment]
@frederikprijck is there a Timeline for a Release of this bug?

**Comment by frederikprijck** [comment]
Sorry about that: https://github.com/auth0/auth0-angular/pull/414
