### ISSUE TITLE
State partitioning with Firefox

### ISSUE THREAD

**Issue by magwas** [auth0/auth0-angular#415]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

I see this message in the firefox log, and the application logs out by itself right after logging in.

Setting the network.cookie.cookieBehavior config to 0 in firefox is a workaround for the problem.

```
Partitioned cookie or storage access was provided to “https://kode-konveyor.eu.auth0.com/authorize?client_id=OqUGGMvs9Ch8yitD3sf2lm6mN61MZqPw&scope=openid+profile+email&redirect_uri=http%3A%2F%2Flocalhost%3A9090%2Fangulartest%2F&prompt=none&response_type=code&response_mode=web_message&state=<redacted>%3D%3D&nonce=<%3D%3D&code_challenge=EOe3JsMxwLwxzWgbted5Q_7979acKCcaRa_oaa1xvsredacted>8&code_challenge_method=S256&auth0Client=<redacted>” because it is loaded in the third-party context and dynamic state partitioning is enabled.
```

Also I see this for 4 cookies.:

```
Cookie “_legacy_auth0.<redacted>.is.authenticated” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite main.4514c6d71a7a0148.js:1:653534
```

> Provide a clear and concise description of the issue

The SameSite attribute is not correctly given.

> Tell us about the behavior you expected to see

I would like to see normal behaviour with network.cookie.cookieBehavior=5 

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.

I have followed your tutorial.

Commit 041a874cba4c791c0a0af97a56f648b88b9722fe of https://github.com/kode-konveyor/angulartest/

> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

1. ...
2. ...
3. ...

If so, provide steps:

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of `auth0-angular` used:**
- **Which browsers have you tested in?**
- **Which version of Angular have you tested with?**
- **Other modules/plugins/libraries that might be involved:**

**Comment by frederikprijck** [comment]
Thanks for reaching out. 

The partitioned cookie seems to be about the cookie for the auth0 domain, which we have no control over from our SDK. 

What I believe is happening is that it's used through our iframe, which we use to silently authenticate, which relies on third party cookies unless you use custom domains.

To avoid issues with third party contexts, we recommend using custom domains or refresh tokens. Browsers like Safari, and potentially others in the future as well, will start blocking third party cookies. See: https://github.com/auth0/auth0-angular/blob/master/FAQ.md#1-user-is-not-logged-in-after-page-refresh

The isAuthenticated cookie is our own cookie, and it's not intended to ever be sent anywhere so there is no need for it to have SameSite to work in third party contexts and it's perfectly fine for it to not be sent in the future.

>  If your application depends on this cookie being available in such contexts, , please add the “SameSite=None“ attribute.

So the above recommendation from the warning is not something we need.

> I would like to see normal behaviour with network.cookie.cookieBehavior=5

cookieBehavior 5 requires either custom domains or refresh tokens.

Let me know if that helped.

**Comment by frederikprijck** [comment]
Closing as I think this is answered, happy to re-open if not.
