### ISSUE TITLE
In v2 is there a way to get the login/logout URLs without the Browser involvement?

### ISSUE THREAD

**Issue by mendhak** [auth0/auth0-angular#417]
### Describe the problem you'd like to have solved

Hello, in our company we've got a common webcomponent used across our sites, as a global navigation bar, that provides login/logout methods, and we use it in our sites by providing it with the login and logout URLs to use.  

Here's a contrived example

```html
<shared-component
  loginUrl=“{YOUR_LOGIN_URL}”
  logoutUrl=“{YOUR_LOGOUT_URL}”
  ... 
 ...
></shared-component>
```

While upgrading to v2.0.0 we can see that the `buildLogoutUrl` and `buildAuthorizeUrl` methods [have been removed](https://github.com/auth0/auth0-angular/blob/beta/MIGRATION_GUIDE.md#buildauthorizeurl-has-been-removed), so we are wondering what can be done to extract those URLs to pass on to another component?  In other words, are there any pointers/guidance you can give us on getting those values out?

Thanks
mendhak

**Comment by frederikprijck** [comment]
Thanks for reaching out.

There is no way in v2 to do that with our SDK, as we believe you should login and logout through using our SDK, and we rely on a transaction to be started (which was previously done as part of buildAuthorizeUrl, so it didnt just built the URL for you, but it did a lot more that you might not expect such as starting a transaction and waiting for it to complete once you get back from Auth0).

So imagine in v1 you call `buildAuthorizeUrl`, it created a transaction. If the user never actualy hits that Url and comes back, you are stuck with a transaction that's started but never finished and might create weird behavior. On top of that, these methods were never introduced to support a scenario like that, but only for a scenario where you need to use external browsers when using things like Ionic, where you still instantly open the browser after calling `buildAuthorizeUrl` or `buildLogoutUrl`, which should be done in v2 using openUrl (but doesn't help your scenario).

What you can do is provide your own URL, that when called calls our SDK instead.

That also allows for the URLs to be shorter and more user friendly, and even allows you to make it whatever URL you like. But does mean more work in user-land when you want a behavior like that.

We did consider keeping these methods in the SDK for v2 without the transactional side-effect, but they have no purpose to exist in that way as you are unable to use the URL with our SDK if you don't initialize a transaction.

So even if we would have exposed the URLs in v2, there is no way to use that URL without calling `loginWithRedirect` on our SDK, which defeats the purpose of exposing it in the first place.

**Comment by mendhak** [comment]
> What you can do is provide your own URL, that when called calls our SDK instead.

Thanks a lot for your response, that's not a bad idea.  We can try this out.

**Comment by frederikprijck** [comment]
Closing this as I don't think we should action anything here. Happy to continue the conversation or reopen as needed.
