### ISSUE TITLE
Documentation for signUp / feature to go to signUp page directly

### ISSUE THREAD

**Issue by CharlieGreenman** [auth0/auth0-angular#418]
### Describe the problem you'd like to have solved

I would like to be able to click on the Sign-Up button and have it go to Auth0 SignUp tab directly. Looking at the documentation here there is only: https://auth0.github.io/auth0-angular/classes/AuthService.html#loginWithRedirect

### Describe the ideal solution

I would like there to be a `signUpWithRedirect` method that goes directly to the auth0 signUp page with redirect baked in

## Alternatives and current work-arounds

None that I've found so far

### Additional context

NA

**Comment by frederikprijck** [comment]
You can do this using `loginWithRedirect`, but by passing it the `screen_hint` value, see https://auth0.github.io/auth0-angular/interfaces/AuthorizationParams.html#screen_hint

```ts
loginWithRedirect({
  authorizationParams: {
    screen_hint: 'signup'
  }
})
```

More on this: https://auth0.com/docs/authenticate/login/auth0-universal-login/new-experience#signup

**Comment by CharlieGreenman** [comment]
thank you
