### ISSUE TITLE
observable user$ does not return all the permissions

### ISSUE THREAD

**Issue by JoseLuisAza** [auth0/auth0-angular#419]
auth0Service.user$.subscribe does not return all permissions and when evaluating the token in jwt.io if it contains all permissions around 70 permissions and user$ observable only returns 50, is there any permission restriction in the token?

auth0 version: 1.11.0
angular version: 13.2.4

**Comment by frederikprijck** [comment]
Thanks for reaching out, I was unable to reproduce this.

Can you verify you are testing the id token on jwt.io, and not the access token?

**Comment by JoseLuisAza** [comment]
thanks for answered, i was testing  in jwt.io  the id token and only has 50 permission, and the access token has 71 permission, the id token does not has all the permission, what would be the answer to this?

**Comment by JoseLuisAza** [comment]
I already discovered the error, in the auth0 rules and in the ManagementClient package and its getUserPermissions function, I was only requesting 50 results per page, I am very sorry for your wasted time, in any case, thank you very much for answering
