### ISSUE TITLE
SSR redirects to home page when AuthService is added

### ISSUE THREAD

**Issue by fchau-ralis** [auth0/auth0-angular#422]
### Describe the problem

> I'm having an issue with Angular SSR and the Auth0 AuthService library. Every time I add the AuthService into my custom CustomerService service, Angular redirects to the home page. I'm not sure what's causing this problem. 

### What was the expected behavior?

> The expected behavior is to load the correct page that's supposed to be rendered. If I go to the `/faq` page for example and run my SSR app, I click on 'View Source' and the contents of the home page show up. If I remove the AuthService library, then I see the contents of the `faq` page properly.

I'm using Angular 10 with "@auth0/auth0-angular": "1.10.1"

When I load the page in my browser, I see a flash of the home page before going to the correct FAQ page. However the page source only shows the home page contents. Is there a redirect happening behind the scenes? I'm not calling any particular function in the AuthService at the time of initialization so I'm confused as to why there's something happening.

**Comment by frederikprijck** [comment]
Thanks for reaching out.

Yes our SDK does redirect on page load. Could you provide a reproduction so we can see if there is anything we can do to solve this?

Keep in mind we only support angular 13+, as those are the only versions supported by Google themselves.

I think the behavior would be the same in angular 13, but be good to verify first.

Thanks.

**Comment by fchau-ralis** [comment]
@frederikprijck Thanks for replying. 

I stripped down my codebase for you to check out here: https://github.com/fchau-ralis/auth0-issue

All you need to do is do a `yarn` and `yarn build` and then serve the website via `node .`

if you go to localhost:3000 you'll see a really basic homepage

if you go to localhost:3000/faq you'll see a basic FAQ page which works fine, however if you view source, you'll see the contents of the home page is there instead of the faq page. I suspect it's because I'm using a service called "CustomerService", which utilizes Auth0's AuthService in my 'app-site-footer' component. When viewing the page normally through the browser, there's a quick flash of the home page before the correct faq page renders.

If you go to http://localhost:3000/about the view source renders the correct about page. I don't use AuthService there so there's no redirect going on.

As you can see, just importing the AuthService into the constructor makes it so that my site redirects to the home page and it messes up SSR since SEO is only going to see the home page. Is there a way for me to go around this? Ideally I wouldn't want auth0 to be involved in the server side but there's no documentation on how to navigate through that.

Your help is greatly appreciated. I've been struggling through this over the past couple days and I hope that there's a way to fix it.

EDIT:

I created a new build with the latest angular and auth0: https://github.com/fchau-ralis/auth0-issue2

Still the same issue. Go to localhost:4000/faq and you'll see its not rendering the faq page but if you go to localhost:4000/about, the page renders fine

**Comment by frederikprijck** [comment]
Hello,

Sorry for the delay.

I see you are importing our AuthModule in AppModule, and AppModule is being imported in your server specific module. You should not do that.

Please read my comment at https://github.com/auth0/auth0-angular/issues/305#issuecomment-1118261182 to see how you want to setup our SDK with SSR.

There is also a repo of a user linked in that thread that i fixed that was using the same setup.

The issue you reported is different, but the origin is the same, being our SDK getting executed on the server, which isnt supported.

Let me know if that doesnt help.

**Comment by frederikprijck** [comment]
Closing as I believe this is answered. If not, we can always reopen.

**Comment by fchau-ralis** [comment]
@frederikprijck  Thanks for the response. Your answer about setting up AuthService and setting up a fake one works. However I'm running into a different issue. Assuming I define my AuthService like the following...

` providers: [
        // Add universal-only providers here
        {
            provide: AuthService,
            useValue: {},
        },
        { provide: AuthConfigService, useValue: {} as any },
    ],`

I run into an issue where there's an error when I try to go to a page that's protected by AuthGuard.

When I go to an page protected by AuthGuard I get the following error in my SSR app:
Error: Uncaught (in promise): TypeError: Cannot read property 'pipe' of undefined

The error happens in the following code block of the angular auth0 library:

` redirectIfUnauthenticated(state) {
        return this.auth.isAuthenticated$.pipe(tap((loggedIn) => {
            if (!loggedIn) {
                this.auth.loginWithRedirect({
                    appState: { target: state.url },
                });
            }
        }));
    }`

The issue, I assume, is the fact that since the this.auth variable isn't defined, the guard doesn't work properly. What happens in the browser is when I access the page, there's a flash to the home page I log in and then I am able to access the protected page but in the server logs I get the error. Is there a way to fix that?

**Comment by frederikprijck** [comment]
You need to ensure you provide the correct mock:

```
 { provide: AuthService, useValue: { isAuthenticated: of(true) }, }
```

Be sure to extend the above with any method that you are accessing on the server side.
