### ISSUE TITLE
invalid state

### ISSUE THREAD

**Issue by magwas** [auth0/auth0-angular#425]
### Describe the problem

My code to handle the callback url in a capacitor based app is functionally identical to that in auth0-ionic-samples/angular.

It receives the following callback url:

`com.kodekonveyor.angulartest://kode-konveyor.eu.auth0.com/capacitor/com.kodekonveyor.angulartest/callback?code=v7lvaWs4uGUXZN9ngACA5HHqaWm8wI3bi0gVYtafNpBd2&state=VUFpcHYuc1FLbEdKWnMwT0tEb0hfWlV1Z2xTLTloenduYzI0WFFnUl80Zw%3D%3D`

and throws `Error: Invalid state` in `handleRedirectCallback`

the last thing I see before the error is `url parameters checked`

Working fine in the browser though, just I guess this code does not get triggered there.

I do not see the auth0 authentication page in the process. I guess it is because the user I test with is already logged in. I haven't find any way to log it out.

my ngOnInit:

```
  ngOnInit(): void {
    console.log("ngOnInit")
    void App.addListener('appUrlOpen', ({ url }) => {
      console.log("listening to", url)
      this.ngZone.run(() => {
        console.log("in zone, comparing to", callbackUri)
        if (url?.startsWith(callbackUri)) {
          console.log("url start checked")
          if (
            url.includes('state=') &&
            (url.includes('error=') || url.includes('code='))
          ) {
            console.log("url parameters checked")
            this.auth
              .handleRedirectCallback(url)
              // eslint-disable-next-line @typescript-eslint/promise-function-async
              .pipe(mergeMap(() => Browser.close()))
              .subscribe(() => {
                console.log("in subscriber for browser close")
              });
          } else {
            console.log("closing browser 1")
            void Browser.close();
          }
        } else {
          console.log("closing browser 2")
          void Browser.close();
        }
      });
    });
  }

```

### What was the expected behavior?

`handleRedirectCallback` logs in the user 

### Reproduction

I can open the offending github project to public if needed.
I might have missed yet other undocumented something about applying the ionic angular sample to my project.
What I did apply:
- reworked the routing, converted my ex main module to lazy-loadable
- added the extra intent-filter to AndroidManifest.xml dor app/src/main
- added polyfills.ts and zone-flags.ts to src, and referenced polyfills.ts in tsconfig.app.json

### Environment

> Please provide the following:

- **Version of `auth0-angular` used:** 2.0.1
- **Which browsers have you tested in?** Android with ionic/capacitor
- **Which version of Angular have you tested with?** 15.0.0
- **Other modules/plugins/libraries that might be involved:** 
   - "@angular/animations": "^15.0.0",
   - "@angular/common": "^15.0.0",
   - "@angular/core": "^15.0.0",
   - "@angular/forms": "^15.0.0",
   - "@angular/platform-browser": "^15.0.0",
   - "@angular/platform-browser-dynamic": "^15.0.0",
   - "@angular/router": "^15.0.0",
   - "@auth0/auth0-angular": "^2.0.1",
   - "@capacitor/android": "^4.5.0",
   - "@capacitor/app": "^4.1.1",
   - "@capacitor/browser": "^4.1.0",
   - "@capacitor/core": "^4.5.0",
   - "@capacitor/haptics": "^4.1.0",
   - "@capacitor/ios": "^4.5.0",
   - "@capacitor/keyboard": "^4.1.0",
   - "@capacitor/status-bar": "^4.1.0",
   - "@ionic/angular": "^6.3.8",
   - "@ngrx/effects": "^15.1.0",
   - "@ngrx/store": "^15.1.0",
   - "@stryker-mutator/jest-runner": "^6.3.1",
   - "immer": "^9.0.19",
   - "rxjs": "~7.8.0",
   - "stryker-cli": "^1.0.2",
   - "tslib": "^2.3.0",
   - "zone.js": "~0.12.0"

**Comment by frederikprijck** [comment]
Thanks for reaching out. Using our SDK does not require lazy-loading. So if you weren't using lazy loading before, there is no reason to do so only for the purpose of integrating out SDK.

Does this error also show if you run our sample application? If not, can you find any differences between the two that cause it?

Please provide a **minimal reproduction** for us to look into the issue to try and find out what's causing it. I am not able to reproduce this as I have been able to successfully login using the Sample application.

Attached, you can find a screen-recording of me running a fresh cloned version of the sample application:

https://user-images.githubusercontent.com/2146903/218724390-7324630c-eba9-4591-bbc1-2ad4490e94aa.mp4

**Comment by magwas** [comment]
The problem can be seen at commit 7160633a67f97bfaf10e7ed478383503eff2ca7a of https://github.com/kode-konveyor/angulartest.git

Your sample application does use a complicated routing approach with lazy loading. In it it differs from your own other sample app for vanilla angular. It was not apparent for me if it is needed for catching the callback, so I copied that as well.

When it was working on web and not working in android, I identified that you added an extra intent-filter. By reproducing that in my project my app was able to receive the callback.

When it was still working on the web and not working in android, I have identified that your application have some polifills. So I added them to my application.

When It still did not work, I got fed up with the guesswork and have written this bugreport.

Yes, your sample application is working, but apparently something to actually make it work is not documented. And the code contains a couple of things which from where I stand with my limited understanding may or may not have something to do with getting it to work.

**Comment by frederikprijck** [comment]
> Your sample application does use a complicated routing approach with lazy loading. In it it differs from your own other sample app for vanilla angular. It was not apparent for me if it is needed for catching the callback, so I copied that as well.

Thanks for calling that out. I am happy to try and make them more the same to avoid that confusion.

I tried running your sample, and can reproduce the issue (invalid state). It does look like a complicated project for someone without context to understand but I will have a look and see if I can find out what's causing it.

**Comment by magwas** [comment]
from com.kodekonveyor.angulartest mostly the login button and the module definitions are of concern. The rest does not get called before authentication.
the basic app is com.kodekonveyor.app, which looks mostly like src/app in the example app.

**Comment by frederikprijck** [comment]
To solve the issue, you need to remove `AuthModule.forRoot()` from the `AngulartestModule` (so drop [this line](https://github.com/kode-konveyor/angulartest/blob/feature/android/src/com.kodekonveyor.angulartest/angulartest-module.ts#L51)). Once I did that, I managed to login succesfuly.

`forRoot` is a pattern used in Angular throughout all kinds of libraries, and is also explained in the [angular docs](https://angular.io/guide/singleton-services#the-forroot-pattern).

It's used to provide singleton services and ensure they stay singleton in a lazy loaded setup.

What is happening, in this case, is that you are using `AuthModule.forRoot` twice (once in `AppModule`, once in `AngulartestModule`), this means you have two different instances of our underling`Auth0Client`, one being used in the `LoginButtonComponent` and one in the `AppComponent`. This is conflicting and will break behavior, just as it would break behavior by importing `EffectsModule.forRoot`, `StoreModule.forRoot`, `RouterModule.forRoot` or any other forRoot in `AngulartestModule`. 

In Angular,`forRoot`'s should always go in the "root" InjectionContext (typically by importing it in `AppModule`) and **never** anywhere else.

Hopefully this helps to unblock you.

**Comment by frederikprijck** [comment]
Regarding the difference in routing setup compared to our Regular Angular sample, I did some research and our Ionic sample is using the official blank ionic+capacitor starter, see https://github.com/ionic-team/starters/tree/main/angular/official/blank/src/app.

What we did was take that as a base using `ionic start app-name blank --type=angular --capacitor`, and added Auth0 to it. I believe it makes sense to keep that, even though it differs from our regular Angular sample.

**Comment by magwas** [comment]
Thank you, it worked.

Well, starting from the blank template does make sense. Probably the blank template already having routing set up this way also make sense. Understanding ionic, angular routing, lazy loaded modules, android build environment etc. at the same time was steep :)
