### ISSUE TITLE
AuthHttpInterceptor fails with 'allowAnonymous: true' when the error is 'missing_refresh_token'

### ISSUE THREAD

**Issue by bknicholls** [auth0/auth0-angular#429]
### Describe the problem

Hi, I'm facing a problem using AuthHttpInterceptor with `allowAnonymous: true` similar to this closed issue: https://github.com/auth0/auth0-angular/issues/174. In my case I'm calling a graphql endpoint (always /api/graphql) so it's valid for certain queries to be anonymous.

The fix for the linked issue (https://github.com/auth0/auth0-angular/pull/180) explicitly checks for 'login_required' or 'consent_required', but in my case the error code is "missing_refresh_token". This kills my entire request.

### What was the expected behavior?

If allow anonymous is enabled then all requests to the api should be allowed to go through regardless of any errors returned from auth0. 

### Environment

> Please provide the following:

- **Version of `auth0-angular` used: 2.0.1**
- **Which browsers have you tested in? Chrome**
- **Which version of Angular have you tested with? 14.2.3**
- **Other modules/plugins/libraries that might be involved: auth0-spa-js 2.0.3**

**Comment by frederikprijck** [comment]
Thanks for reaching out, I added `missing_refresh_token` to the list of errors to ignore. Not adding all errors, as that would suddenly silence all kind of other error that have a meaning beyond not just authenticated and might need to be resolved accordingly instead of being ignored.
