### ISSUE TITLE
Add option to disable automatic navigation in 'handleRedirectCallback'

### ISSUE THREAD

**Issue by mfrey-WELL** [auth0/auth0-angular#431]
Hi,
I followed the official tutorial on how to [add login to my Ionic App](https://auth0.com/docs/quickstart/native/ionic-angular/interactive). The login works but whenever I call 'handleRedirectCallback(url)' my app also navigates to '/' and I do not want that.
This is triggered [here](https://github.com/auth0/auth0-angular/blob/master/projects/auth0-angular/src/lib/auth.service.ts#L320) and from what I can see there is no option to disable that behaviour.

So my question is: Is there an alternative way to handle the callback without automatic navigation? If not I could create a PR to add it.

**Comment by frederikprijck** [comment]
Thanks for reaching out. Before considering a PR, can you tell a bit more about the use case to avoid any navigation? 

Keep in mind that auth0 redirects back to your app with certain query parameters, which we use, exchange and need to remove from the url.

So even if you don't want the navigation, we still need to consider that part.

However, curious to understand more about the use case here first.

Thanks.

**Comment by mfrey-WELL** [comment]
In summary: 
1. User clicks 'Login'
2. App opens InAppBrowser
3. User completes Login in separate window, InAppBrowser closes
4. App handles redirectUrl in the background
5. App fetches data from backend
6. App navigates to home screen

In my use case, the login happens in the InAppBrowser so there is no redirection necessary within my SPA. The App stays on the login page while the user signs in from a separate window. I need to call 'handleRedirectCallback' to complete the login but before navigating away from the login screen I want to fetch some data from the backend with the access token.

**Comment by frederikprijck** [comment]
Thanks for that context. 

I am not saying I am not open to add a configuration option for this. But I believe it's worth considering other solutions first with what's available in the SDK, before modifying the SDK for a specific use-case that may be solvable differently.

Is there any reason you are unable to solve this by either:
- fetching the data in a resolver?
- use an intermediate route to handle the data fetching before redirecting to whatever route you want.

Would love to understand if and why both of the above aren't working for you.

**Comment by mfrey-WELL** [comment]
Thanks for the alternative suggestions. For architectural reasons we cannot handle it in a resolver. I tried [overriding the target](https://github.com/auth0/auth0-angular/blob/b009101606cf8758a3db61ee61b785f8031fe061/FAQ.md#3-user-is-redirected-to--after-successful-sign-in-with-redirect) but it doesn't seem to apply, it still forwards to '/'. For now I have resorted to injecting a mock navigator into the service.

**Comment by frederikprijck** [comment]
Thanks for the feedback.

You should be able to specify the `appState.target` when calling `loginWithRedirect`.
But yes, using a specific AbstractNavigator, allows you to take control of when to redirect, and when not.

Therefore, as you have a workaround that achieves what you are looking for, I am going to close this.
