### ISSUE TITLE
The example for `login_required` error isn't compiled

### ISSUE THREAD

**Issue by AlexElin** [auth0/auth0-angular#435]
### Describe the problem
The [example](https://github.com/auth0/auth0-angular/blob/d7b52ce31d4756993f37da4c9ce4dbf273e41fde/EXAMPLES.md) for `login_required` error isn't compiled.

I get the following error:
```
Error: src/app/app.component.ts:15:32 - error TS2304: Cannot find name 'GenericError'.

15       filter(e => e instanceof GenericError && e.error === 'login_required'),
```

### What was the expected behavior?

The code is succefully compiled

### Reproduction

Ccompile the following code (html template is any)
``` typescript
import { Component, OnInit } from '@angular/core';
import { AuthService } from '@auth0/auth0-angular';
import { filter, mergeMap } from 'rxjs/operators';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {

  constructor(private readonly auth: AuthService) {}

  ngOnInit(): void {
    this.auth.error$.pipe(
      filter(e => e instanceof GenericError && e.error === 'login_required'),
      mergeMap(() => this.auth.loginWithRedirect())
    ).subscribe();
  }

}
```

### Environment

> Please provide the following:

- auth0-agular: **2.0.1**
- angular: **15.1**

**Comment by frederikprijck** [comment]
Thanks for reaching out, we'll look into getting that example fixed!

You should be able to work around it by importing `GenericError` from `@auth0/auth0-spa-js`:

```
import { GenericError } from '@auth0/auth0-spa-js';
```

Let me know if that works!

We will look into exposing these Error types through the Angular SDK directly and ensure the example works.

**Comment by AlexElin** [comment]
Yes, importing `GenericError` from `@auth0/auth0-spa-js` helps.
