### ISSUE TITLE
Support functional canActivate Route Guards

### ISSUE THREAD

**Issue by darko1002001** [auth0/auth0-angular#442]
Currently auth0-angular provides a guard which can be used to protect the routes/require auth.

```
const routes: Routes = [
  {
    path: 'profile',
    loadChildren: () =>
      import('./features/profile/profile.module').then((m) => m.ProfileModule),
    canActivate: [AuthGuard],
  }
];
```

This uses"canActivate" with a class Guard when defining the route which at this point is deprecated in favour of using functional guards

You can add something like this and export it as a public API. Obviously for backwards compatibility you can restructure the code a bit to support both the class based guard and functional.

auth.guard.ts
```
import { ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';
import { inject } from '@angular/core';
import { AuthService } from '@auth0/auth0-angular';
import { tap } from 'rxjs';

export const authGuard = (_: ActivatedRouteSnapshot, state: RouterStateSnapshot) => {
    const auth = inject(AuthService);
    return auth.isAuthenticated$.pipe(
        tap((loggedIn) => {
            if (!loggedIn) {
                auth.loginWithRedirect({
                    appState: { target: state.url },
                });
            }
        })
    );
};

```

routes.ts
```
import { authGuard } from './core/auth.guard';
const routes: Routes = [
  {
    path: 'profile',
    loadChildren: () =>
      import('./features/profile/profile.module').then((m) => m.ProfileModule),
    canActivate: [authGuard],
  }
];
```

**Comment by frederikprijck** [comment]
Thanks, we will most likely add support for that. However, you should be able to use [the helpers from Angular](https://github.com/angular/angular/blob/main/packages/router/src/utils/functional_guards.ts#L35-L38) to transform class based guards to functional guards, [as per the Angular team](https://github.com/angular/angular/pull/47924#issuecomment-1466934598).

Meaning you should be able to use the following with Angular 16:

```ts
import { mapToCanActivate } from '@angular/router';
import { AuthGuard } from '@auth0/auth0-angular';

const routes: Routes = [
  {
    path: 'profile',
    loadChildren: () =>
      import('./features/profile/profile.module').then((m) => m.ProfileModule),
    canActivate: mapToCanActivate([AuthGuard]),
  }
];
```

Same would go for canActivateChild, but you'd use the [mapToCanActivateChild](https://github.com/angular/angular/blob/main/packages/router/src/utils/functional_guards.ts#L48-L51) instead.

Let me know if that helps in the mean time.

**Comment by frederikprijck** [comment]
Closing. 

We are planning to add support for this but are a bit blocked for the time being because we are compiling using Angular 13.

Once we are at Angular 15, we will happily provide the following functional artifacts:

- authGuard
- authInterceptor
- provideAuth

For now, please work around it by using the following:

- for `authGuard`, use `mapToCanActivate([AuthGuard])` or `mapToCanActivateChild([AuthGuard])`
- for `authInterceptor`, use `const authInterceptor = (req: HttpRequest<any>, handle: HttpHandlerFn) =>
  inject(AuthHttpInterceptor).intercept(req, { handle });`
- Add `AuthHttpInterceptor` to the providers.
- for `provideAuth`, please use the `importProvidersFrom` for now.

Here is an example of how you could use it all:

```ts
const routes: Routes = [
  {
    path: 'profile',
    component: ProfileComponent,
    canActivate: mapToCanActivate([AuthGuard]),
  }
];

const authInterceptor = (req: HttpRequest<any>, handle: HttpHandlerFn) =>
  inject(AuthHttpInterceptor).intercept(req, { handle });

bootstrapApplication(AppComponent, {
  providers: [
    provideRouter(routes),
    AuthHttpInterceptor,
    importProvidersFrom(
      AuthModule.forRoot(/* Auth Config Goes Here */)
    ),
    provideHttpClient(
      withInterceptors([authInterceptor])
    ) 
  ]
});
```

Definetly not ideal, but it should allow you to use our SDK in a more functional manner.

**Comment by frederikprijck** [comment]
Added a [PR](https://github.com/auth0/auth0-angular/pull/445) to include these in our SDK, to make integration easier.
