### ISSUE TITLE
"OIDC Conformant" must be enabled in V2

### ISSUE THREAD

**Issue by mtsuggs** [auth0/auth0-angular#450]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hello!  We have been using your package for about 4 years now.  I am tying to upgrade to V2 from V1.  I noticed a couple concerning items:

Ensure that "JsonWebToken Signature Algorithm" is set to RS256 and that "OIDC Conformant" is enabled.

We need to be able to pass custom parameters to be ran in Auth0 actions.  This gives our action flows context as to what needs to be done in the rule.  Our current v1 engine supports this by turning this flag off.  How can I support passing custom parameters to actions in v2?

Current way I am accomplishing this is as follows:

            let myParam = 'hello world'
            return this.authService.getAccessTokenSilently({ myParam: myParam, ignoreCache: ignoreCache}).pipe(map(t => {

Will this continue to be supported or what is the work around?

### Describe the ideal solution

Support custom parameters passing via getTokenAccessSilently with ignore cache = true.

### Alternatives and current workarounds

N/A

### Additional context

Great package!

**Comment by frederikprijck** [comment]
Thanks for reaching out. Sending custom parameters is still supported in V2, but they need to be set as authorizationParams:

```
this.authService.getAccessTokenSilently({
  authorizationParams: {
    myParam: "myValue"
  },
  cacheMode: 'off'
})
```
As you can see, with v2 ignoreCache is also replaced by cacheMode.

I recommend checking https://github.com/auth0/auth0-angular/blob/master/MIGRATION_GUIDE.md#introduction-of-authorizationparams and https://github.com/auth0/auth0-angular/blob/master/MIGRATION_GUIDE.md#ignorecache-on-getaccesstokensilently-has-been-replaced-by-cachemode

In general, nothing should have changed in V2 regarding OIDC confortmant. Everything that worked before, should still work, possibly using a slightly different public API.

**Comment by frederikprijck** [comment]
Closing as I believe your question was answered. Can always reopen if needed.
