### ISSUE TITLE
AuthService.isAuthenticated$ first emits false then true

### ISSUE THREAD

**Issue by restfulhead** [auth0/auth0-angular#455]
### Checklist

- [X] The issue can be reproduced in the [auth0-angular sample app](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When the user is logged in, reloading the Angular sample application should cause the `isAuthenticated$` Observable to emit `true`. However, it first emits `false` and then `true`. This causes the app to display the unauthenticated state (login button, etc.) for a brief moment, which is a bad user experience.

See the video here: https://github.com/auth0/auth0-angular/assets/558375/e531a63a-6b23-48da-9870-0c8546aca608

Created a new ticket as requested in https://github.com/auth0/auth0-angular/issues/447#issuecomment-1641427974

### Reproduction

1. Clone `git@github.com:auth0-samples/auth0-angular-samples.git`
2. Inside `Sample-01` create `auth_config.json` with a SPA application
3. Start sample app: `npm run start` 
4. Login
5. Navigate to the "External API" page
6. Reload your browser and notice that the "login" button is briefly displayed, and then the UI updates.

### auth0-angular version

2.1.0

### Angular version

16, but also happens in 15

### Which browsers have you tested in?

Safari

**Comment by frederikprijck** [comment]
Thanks for logging a different issue.

As you are using safari, this might be expected as they block third party cookies, see our [faq](https://github.com/auth0/auth0-angular/blob/master/FAQ.md)

Can you verify it works with chrome (ensuring it doesnt block third party cookies)?

For safari, as mentioned in our faq, you want to enable custom domains.

If that's not an option, you should be able to use refresh tokens with local storage.

Can you verify that as well?

But do know we recommend custom domains over local storage when possible.

Thanks

**Comment by restfulhead** [comment]
> Can you verify it works with chrome?

I see the same behavior in Chrome (see video).

> you want to enable custom domains.

I'm still in the evaluation phase and using the free version, which doesn't support it.

> you should be able to use refresh tokens with local storage.

Oh, I have to admit I completely missed the FAQ. Thanks for pointing it out. Adding the following to my environment config works:

```
useRefreshTokens: true,
cacheLocation: 'localstorage' as const,
``` 

Would it make sense to use these settings as default in the Angular sample app, so other users don't run into it?

**Comment by frederikprijck** [comment]
Does your chrome block third party cookies?

We don't want to use this setting by default in the sample app, no. Localstorage is opt in, and not something we want to recommend by default. 

We recommend custom domains for people that dont like the behavior you are seeing (which only happens when third party cookies are blocked, which is exactly what custom domains solve).

**Comment by frederikprijck** [comment]
Closing as i think it works as expected because of browsers blocking third party cookies as indicated in our FAQ.
