### ISSUE TITLE
TypeError: this.router.navigateByUrl is not a function when handling callback

### ISSUE THREAD

**Issue by ThomasGaboriau** [auth0/auth0-angular#463]
### Checklist

- [X] The issue can be reproduced in the [auth0-angular sample app](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

First of all, I apologise for not having a reproduction of the problem on my machine. It only appears after deployment.

After a successful connection, an error occurs during callback handling : `TypeError: this.router.navigateByUrl is not a function`

### Reproduction

For context, the app only allows authenticated users. 

So when a user arrives, he's immediately redirected to the Auth0 login page.
But after redirection, the app remains stuck on `{url}/?code=...&state=...`.
The user looks correctly authenticated, redirecting to `{url}` manually works fine.

When you inspect the console, the following message appears:
```javascript
main.a3a2f6c09ba54b50.js:1 ERROR TypeError: this.router.navigateByUrl is not a function
    at ie.navigateByUrl (main.a3a2f6c09ba54b50.js:1:375082)
    at main.a3a2f6c09ba54b50.js:1:377309
    at main.a3a2f6c09ba54b50.js:1:68368
    at k._error (main.a3a2f6c09ba54b50.js:1:67846)
    at k.error (main.a3a2f6c09ba54b50.js:1:60212)
    at k._error (main.a3a2f6c09ba54b50.js:1:60455)
    at k.error (main.a3a2f6c09ba54b50.js:1:60212)
    at k._next (main.a3a2f6c09ba54b50.js:1:67792)
    at k.next (main.a3a2f6c09ba54b50.js:1:60100)
    at main.a3a2f6c09ba54b50.js:1:76087
``` 
After comparing the minified code and the source, here what I think happens : 

- the `handleReirectCallback` of `AuthService` calls `this.navigator.redirect()` : [auth.service.ts](https://github.com/auth0/auth0-angular/blob/81459fe903e0049a874a449279f7f3d5e337783b/projects/auth0-angular/src/lib/auth.service.ts#L305-L327)
- for a reason I don't know, the navigator has a router that has no `navigateByUrl()` method, and raises a TypError : [abstract-navigator.ts](https://github.com/auth0/auth0-angular/blob/81459fe903e0049a874a449279f7f3d5e337783b/projects/auth0-angular/src/lib/abstract-navigator.ts#L23-L31)
- it is then caught by the `catchError` in the constructor of `AuthService`, which attemps to redirect to the `errorPath` but fails again because still no `navigateByUrl()` : [auth.service.ts](https://github.com/auth0/auth0-angular/blob/81459fe903e0049a874a449279f7f3d5e337783b/projects/auth0-angular/src/lib/auth.service.ts#L95-L112)
  
I have no idea how the router can have no `navigateByUrl()` method. Maybe also check its presence before trying a redirection ?

For the record, downgrading to auth0-angular v1 works fine.

### Additional context

Here is the `app.routing.module.ts` : 
```typescript
const routes: Routes = [
    {
        path: 'forbidden',
        component: ForbiddenComponent
    },
    {
        path: '',
        loadChildren: () => import('./features/core/core.module').then(m => m.CoreModule),
        canActivate: [authGuardFn]
    }
];
``` 

Here is the config of the `AuthModule` : 
```typescript
AuthModule.forRoot({
    domain: environment.auth0Domain,
    clientId: environment.oauth2ClientID,
    authorizationParams: {
        audience: environment.auth0Audience,
        redirect_uri: window.location.origin,
        scope: `${environment.scope} profile email`
    },
    errorPath: '/forbidden',
    useRefreshTokens: true,
    cacheLocation: 'localstorage',
    httpInterceptor: {
        allowedList: [ ... ]
    },
    useFormData: false
}),
``` 

### auth0-angular version

2.2.1

### Angular version

16.1.8

### Which browsers have you tested in?

Chrome, Firefox

**Comment by frederikprijck** [comment]
Thanks for reporting.

The angular router has a navigateByUrl method, so we shouldnt check for it's existence nor should it not be available.

Please provide something for us to reproduce. 

I understand you say it happens on deployment, does it also happen if u do `ng build` followed by `npx http-server dist`? 

If not, theres not much i can help. If it does happen in that case, please share a sample and i can help investigate.

**Comment by ThomasGaboriau** [comment]
Hello

Sorry for the close / reopen, I missclicked.

After removing random bits of code, I finally managed to find the culprit, even if I dont get how it can be responsible for the error.

I have a custom `TitleStrategy` to be able to have translated titles based on routes titles

```typescript
import { Injectable } from '@angular/core';
import { RouterStateSnapshot, TitleStrategy } from '@angular/router';
import { TranslateService } from '@ngx-translate/core';
import { Title } from '@angular/platform-browser';

@Injectable()
export class I18nTitleStrategy extends TitleStrategy {
    public constructor(
        private translateService: TranslateService,
        private readonly title: Title) {
        super();
    }

    public override updateTitle(snapshot: RouterStateSnapshot): void {
        console.log(snapshot);
        const title = this.buildTitle(snapshot);
        if (title) {
            const translatedTitle = this.translateService.instant(title);
            this.title.setTitle(translatedTitle);
        }
    }
}
``` 

Registered in the providers of the `app.module`
```typescript
providers: [
        {
            provide: HTTP_INTERCEPTORS,
            useClass: AuthHttpInterceptor,
            multi: true
        },
        {
            provide: TitleStrategy,
            useClass: I18nTitleStrategy
        }
    ],
``` 

I will provide you a repo, maybe it can be useful.

**Comment by ThomasGaboriau** [comment]
You can find the reproduction repo [here](https://github.com/ThomasGaboriau/auth0-repro).

**Comment by frederikprijck** [comment]
Thanks for the reproduction. Just want to update that I can see the issue but I am not sure this is an issue with our SDK. Will continue investigation as well.

**Comment by frederikprijck** [comment]
Just an update, once I change the TitleStrategy to:

```ts
@Injectable()
export class I18nTitleStrategy extends TitleStrategy {
  public constructor(private readonly title: Title) {
    super();
  }

  public override updateTitle(snapshot: RouterStateSnapshot): void {
    const title = this.buildTitle(snapshot);
    if (title) {
      this.title.setTitle(title);
    }
  }
}
```

Everything works as expected. Can you confirm?
That does not solve anything, but at least it shows where we should be looking.

**Comment by ThomasGaboriau** [comment]
Hello,
I confirm, removing the TranslateService does fix the issue.
Having it unused, only in the constructor, is enough for the issue to come back.

**Comment by frederikprijck** [comment]
I haven't been able to find how to work around it, but neither am I sure it's an issue with our SDK. 

Have you been able to find a workaround yourself?

**Comment by ThomasGaboriau** [comment]
Currently my workaround is to use the v1 of the lib, and overriding its dependencies to my local Angular version in the package.

Since I'm no to keen on this, and if it is not fixable I will drop the TitleStrategy and manage my titles more manually. The app is not big enough for it to be a hassle.

**Comment by frederikprijck** [comment]
I will give it another look to try and find out why it does work with v1, and not with v2. The only difference I can think of is the version of Angular that we use in the corresponding Auth0-Angular version.

Just to be sure, what version of v1 works for you?

**Comment by ThomasGaboriau** [comment]
I'm using the latest v1 version of @auth0/auth0-angular, 1.11.1

**Comment by Ookamini95** [comment]
Hello please let me join in the discussion. I'm also having some trouble on the angular-ionic starter project. Once everything is configurated everything works as expected until I get to the redirect callback (namely after i log in with google); there I managed to get 3 possible behaviours:
- gets stuck after login press on device (Xiaomi M2007J3SY + Chrome) > Seems to work with "Mi Browser" > Stuck after google login
-  gets stuck after google login on simulator but actually redirects to callback?code={code} but fails to load the page
- after login with google redirects to /home without any apparent UI effect (no user shown)

Should I open a separate bugreport? (it's my first I'm shy)

**Comment by frederikprijck** [comment]
Please open a new issue, make sure to provide a reproduction for us to look into.

Thanks

**Comment by frederikprijck** [comment]
Hey @ThomasGaboriau,

Trying to look into this again, I am unable to reproduce this anymore. I pulled [your reproductions again](https://github.com/ThomasGaboriau/auth0-repro) and I am getting a different error:

```
i18n-title-strategy.ts:7 ERROR Error: NG0200: Circular dependency in DI detected for InjectionToken HTTP_INTERCEPTORS. Find more at https://angular.io/errors/NG0200
    at throwCyclicDependencyError (core.mjs:228:11)
    at R3Injector.hydrate (core.mjs:9297:13)
    at R3Injector.get (core.mjs:9189:33)
    at injectInjectorOnly (core.mjs:652:33)
    at ɵɵinject (core.mjs:656:60)
    at inject (core.mjs:740:12)
    at http.mjs:1650:40
    at http.mjs:1624:76
    at R3Injector.runInContext (core.mjs:9152:20)
    at http.mjs:1624:57
```

Which is reported here https://github.com/ngx-translate/core/issues/1317, and can be solved comparable to that github issue:

```diff
TranslateModule.forRoot({
    defaultLanguage: 'en',
    loader: {
        provide: TranslateLoader,
        useFactory: i18nLoaderFactory,
-       deps: [HttpClient]
+       deps: [HttpBackend]
    }
}),

-export function i18nLoaderFactory(http: HttpClient): TranslateHttpLoader {
-    return new TranslateHttpLoader(http, './assets/i18n/', '.json');
-}

+export function i18nLoaderFactory(http: HttpBackend): TranslateHttpLoader {
+    return new TranslateHttpLoader(new HttpClient(http), './assets/i18n/', '.json');
+}
```
Once I do that, I can run your sample without any issues and see the title being updated. I think this is a fair solution because you probably do not want interceptors to run when fetching the translation files.

Closing this, but let me know if I am missing something and I am happy to reopen and try and investigate further!

**Comment by ThomasGaboriau** [comment]
Hello @frederikprijck,

Thanks a lot for coming back to this issue !
I confirm it solved the problem also on the original project.

**Comment by frederikprijck** [comment]
Thank you for confirming. I am happy it was resolved on your application as well!
