### ISSUE TITLE
Cannot access CheckSession() for cross-app single sign on and single sign off

### ISSUE THREAD

**Issue by mattcheah** [auth0/auth0-angular#466]
### Checklist

- [X] The issue can be reproduced in the [auth0-angular sample app](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hey all, my apologies if this belongs in the auth0 community but I've had no luck posting there or looking there for `auth0-angular` issues. 

I'm trying to implement cross-app SSO (sign-on and sign-off) with 2 separate domains connecting to a custom domain using Universal Login. It appears as if others have gotten this working fine according to [this issue comment](https://github.com/auth0/auth0-angular/issues/87#issuecomment-732815106), but I'm having no luck finding documentation of how to actually implement this properly, besides [this article suggesting to use CheckSession()](https://auth0.com/docs/authenticate/login/configure-silent-authentication#poll-with-checksession-) which is not publicly exposed, and [these examples from 5 years ago](https://github.com/adrianchia/auth0-angular-samples) that rely on [Auth0.js](https://auth0.com/docs/libraries/auth0js)

Is there anything I'm missing or some way to call `CheckSession()` on load to log my user in? And eventually to poll `CheckSession()` every 15 minutes to log a user out via single sign off?  (or if there's a better way to do it?)

Thanks for your help!

### Reproduction

1. 2 Domains set up without any AuthService calls on load (no `loginWithRedirect`, `handleRedirectCallback`, `getAccessTokenSilently`). 
2. Subscribe to `isLoading$`, `isAuthenticated$`, `user$`, `errors$`
3. AuthGuard not in use (homepage is protected via `*ngIf="authService.isAuthenticated | async"`

4. Make sure a.com and b.com are logged out. 
5. log in to a.com 
6. refresh b.com - user is not logged in. 
7. refresh a.com - user is still logged in. 

and vice versa. 

### Additional context

Doesn't work on localhost or live. 

### auth0-angular version

2.1.0

### Angular version

14.2.12

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Have u set the cookieDomain option to ensure the cookie we use is linked to the top level domain, and not including your sub domain?

See https://auth0.github.io/auth0-spa-js/interfaces/Auth0ClientOptions.html#cookieDomain

This is ofcourse assuming the two applications share the same top level domain. If this isn't the case, you will need to ensure you call `loginWithRedirect` yourself (either on page-load when isLoading is false and isAuthenticated is false (but avoid a loop), or manually through a button. This should redirect the user to Auth0, and instantly redirect back when they are already authenticated.

**Comment by mattcheah** [comment]
Thank you @frederikprijck.
The 2 applications are on different domains. Since my homepage content changes depending on whether the user is authenticated or not, I don't want to immediately call `loginWithRedirect()` on load if the user is not authenticated. Is there a way to silently authenticate on page load and if the user is not logged in then we just ignore?

**Comment by frederikprijck** [comment]
No, you need to go through interactive login if the domains are different.

If you want to do it silently, you want to ensure you use the same top level domain, and configure the cookieDomain option.

Using checkSession for this isn't going to work, as [it relies on the cookie](https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L566) (which is set by using interactive login, but can be shared across top-level domains by setting the cookieDomain).

**Comment by frederikprijck** [comment]
Closing as I think it has been answered. Feel free to ping me if I can assist any further.
