### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by mraible** [auth0/auth0-angular#469]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

`main` is a more developer-friendly name

### Describe the ideal solution

The default branch is `main`

### Additional context

This is a nice guide: https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main

**Comment by frederikprijck** [comment]
Thanks, renamed it to main 👍
