### ISSUE TITLE
Package configuration via service

### ISSUE THREAD

**Issue by brandon-sigao** [auth0/auth0-angular#47]
### Describe the problem you'd like to have solved

My organization does not use the angular environment files for build variables because that method forces the application to be rebuilt in every CI/CD environment which introduces instability.  Instead, we include an appSettings.json file with our package and let the application query for environment specific variables on load.  This means that configuration via the module.forRoot() parameters isn't possible as it replies on a typescript file getting compiled into the app.

### Describe the ideal solution

Our internal configuration provider package is designed to grab the values out of appSettings and provide them in a service to the app. Ideally Auth0 would give us the option to delay configuration until services are provided like so:

```
constructor(
    public configService: NgAppConfigService,
    public auth0: Auth0Service) { 

    const config = this.configService.getconfig();
    this.auth0.initialize(config.auth0Settings);
}
```

## Alternatives and current work-arounds

Our current workaround is to use our internal Auth0 wrapper (@sigao/ng-auth0) that allows for initialization via the service.  However, we would like to switch over to using the SDK if possible.

**Comment by stevehobbsdev** [comment]
Hey @brandon-sigao, thanks for raising this and apologies for the radio silence here.

I've taken it as a point to investigate how we can better provide configuration options to the SDK, it looks like we might have to have the option to provide such options through a provider rather then specifying them through `forRoot`. For now, we've gone with the latter but I'll look at how we can improve that experience going forward.

Thanks for raising!

**Comment by gagaXD** [comment]
Hey there,

My organization also use a service to resolve environment dynamically, with the `APP_INITIALIZER` provider.

With the configuration in the `forRoot`, we aren't able to use our dynamically load environment.

Initializing the auth0 client later in the app process, could be a great improvment

**Comment by stevehobbsdev** [comment]
Thanks @gagaXD.

A question for both of you; so that I understand more about your use-case, what's the ideal API you would want to see that would solve your issue?

I'm looking for a way I can have both the `forRoot` configuration option as well as the configuration option you're looking for.

**Comment by brandon-sigao** [comment]
Sure, I can show you the way we're currently doing it.  I'm sure there's a more elegant solution, but this has been working so far:


Module definition
```
export class NgAuth0Module {
  static forRoot(config?: Auth0Config): ModuleWithProviders {
    return {
      ngModule: NgAuth0Module,

      providers: [
        Auth0Service,
        Auth0LoggedInGuard,
        { provide: 'NG_AUTH0_CONFIG', useValue: config },
        { provide: 'AUTH0_CLIENT', useValue: createAuth0Client },
        {
          provide: HTTP_INTERCEPTORS,
          useClass: InterceptorService,
          multi: true
        }
      ]
    };
  }
}
```

Auth0Service constructor
```
constructor(
    @Inject('NG_AUTH0_CONFIG') @Optional() private _config: Auth0Config,
    @Inject('AUTH0_CLIENT') private _clientFactory: ClientFactory,
    private router: Router,

  ) {

    // If config comes from module
    if (this._config) {
      this.init(this._config);
    }
  }

  public init(config: Auth0Config): void {

    // save this again in case it wasn't injected
    this._config = Object.assign({}, config);

    this._auth0ClientStream = (from(
      this._clientFactory(config)
    ) as Observable<Auth0Client>).pipe(
      shareReplay(1), // Every subscription receives the same shared value
      catchError(err => throwError(err))
    );

    this.setupStreams();
  }
```

Basically I'm just running the same init function for the values coming into the forRoot as well as the service.  The caveat being that the timing of things may get weird if you aren't providing/using the service top level in the app.component.  I haven't really tested that scenario as 100% of our projects use the appSettings.json I mentioned.

**Comment by arthurbrack** [comment]
I have also the same issue. Need to provide runtime configuration (obtained via rest call from the server) for the Auth0 module, 

Here is a possible solution for a comparable module (angular-oauth-oidc). They use a provider for the AuthConfig:
https://stackoverflow.com/questions/54469571/angular-load-external-configuration-before-appmodule-loads

However, it does not work with auth0-angular, since AuthModule.forRoot requires an AuthConfig object.

**Comment by stevehobbsdev** [comment]
Thanks all.

This is what I'm proposing. Luckily internally the configuration can already be provided via DI but the mistake is that we're passing it statically to a function that creates the Auth0Client.

I've [pushed a diff](https://github.com/auth0/auth0-angular/compare/sdk-1977/config-provider) that might get you what you want, would appreciate your comments.

The module API in your app would look like this. If you don't specify config to `forRoot` nor provide the config through a factory function or similar, you will simply get an error from Angular to say that it could not resolve a dependency.

```js
import { AuthConfigService, AuthModule } from '@auth0/auth0-angular';


@NgModule({
  declarations: [
    AppComponent,
    ProtectedComponent,
    UnprotectedComponent,
    ChildRouteComponent,
    NestedChildRouteComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    ReactiveFormsModule,
    AuthModule.forRoot(),     // no config specified here
  ],
  providers: [
    {
      // Provide the config here
      provide: AuthConfigService,
      useFactory: () => ({
        domain: 'DOMAIN',
        clientId: 'CLIENT_ID'
      })
    },
  ],
  bootstrap: [AppComponent],
})
```

**Comment by arthurbrack** [comment]
@stevehobbsdev thanks, looks promising!
Would this approach also allow to preload the config from a REST-call via APP_INITIALIZERS?

**Comment by brandon-sigao** [comment]
@arthurbra @stevehobbsdev I'm not sure this is going to solve our problem.  With this method the configuration is still relying on the values being provided before the app is compiled. What Arthur and I are looking for is a way to supply those configuration properties after the app has been compiled and made a request to some service to gather configuration options.  The reason being that we want to avoid using the environment.ts file and by extension avoid re-compiling the app in all the environments of our CI/CD process (as well as giving us the ability to push new variables to the system without pushing a whole new build).  Typically this is done via an APP_INITIALIZER function which makes an http request to retrieve configuration settings and modify services before the rest of the app loads.

We can modify previously provided services that are injected into the APP_INITIALIZER function, but as far as I know we can't dynamically provide a new service with the configuration settings we received from the http request.  I believe if we tried to do that the AppModule would have already failed because it was looking for an instance of AuthConfigService before it ran the APP_INITIALIZER.

**Comment by stevehobbsdev** [comment]
> The reason being that we want to avoid using the environment.ts file and by extension avoid re-compiling the app in all the environments of our CI/CD process

Ok, but our SDK does not require you to use the `environment.ts` file, it's just one method we show in a sample that _uses_ this SDK.

Let me go back and find out how best to incorporate APP_INITIALIZER, but I don't think we're too far off.

**Comment by brandon-sigao** [comment]
That's fair, I could be missing something with what you proposed.  In your example how would you recommend providing different values to the AuthConfigService factory if they needed to change between environments?

**Comment by mendhak** [comment]
Ah, I just started implementing this library in a new app and ran into this issue; I'm contemplating falling back to auth0-spa-js but this library is so convenient!  Would appreciate any movement on this @stevehobbsdev 🙏 

What we're basically looking to do is build our Angular apps once and deploy to multiple environments.  This requires the domain/clientId values to be loaded dynamically and the most common way to do this is with `APP_INITIALIZER` which calls a method which then makes an HTTP request, either to an external service or a `.json` file in assets, for example.  The values like domain and clientId are then provided from the response.

At the moment, since `.forRoot()` happens before the `APP_INITIALIZER`, there's no choice but to build multiple times.

**Comment by stevehobbsdev** [comment]
Thanks @mendhak. Just to update, I have a PR nearly ready to go for this and will be raising it as soon as I can. Hopefully tomorrow, early next week at the latest.

**Comment by stevehobbsdev** [comment]
@brandon-sigao We have a solution ready to go, would appreciate your thoughts on it to make sure it would meet your needs: #62

**Comment by mendhak** [comment]
(I'm not the original poster) I was able to try the Playground in your branch, I did have to modify the config initializer method like so to make it perform the HTTP request:

```
function configInitializer(config: AuthClientConfig, http: HttpClient): () => Promise<any> {

  return () =>
    http
      .get('https://api.npoint.io/86e813b730424ff5fcd0')
      .toPromise()
      .then((loadedConfig: any) => config.set(loadedConfig));   // Set the config that was loaded asynchronously here
}
```

I couldn't get the HTTP request working the way you have in your pull request example.  Is it worth changing or did that work for you?


Additionally in the example I believe this line should change:

```
import { AuthModule } from '@auth0/auth0-angular';
```

to 

```
import { AuthModule, AuthClientConfig  } from '@auth0/auth0-angular';
```

**Comment by brandon-sigao** [comment]
@stevehobbsdev Looks good to me!  That injectable config service will give us a lot of flexibility on start up.  Thank you guys for taking the time to add this, I'm looking forward to using this library.

**Comment by stevehobbsdev** [comment]
> Is it worth changing or did that work for you?

Yes it worked for me. Let me confirm. I've updated in the sample in the PR to show the imported type, too - thanks for raising that.

**Comment by stevehobbsdev** [comment]
@mendhak This is what I've been working with locally, which works for me: https://github.com/auth0/auth0-angular/blob/dynamic-example/projects/playground/src/app/app.module.ts

**Comment by mendhak** [comment]
Oh I see, I didn't see an `http.get` in your working branch so I had gotten confused. 

https://github.com/auth0/auth0-angular/blob/sdk-1977/config-provider/projects/playground/src/app/app.module.ts#L26-L31

**Comment by stevehobbsdev** [comment]
Yes. In the playground we demonstrate using a Promise even though it just returns some static config, instead of standing up a server to serve some config. But as long as you're returning a promise you can load the config from anywhere.

**Comment by mendhak** [comment]
Sorry for the noise. I opened a [new issue](https://github.com/auth0/auth0-angular/issues/70) regarding httpInterceptor
