### ISSUE TITLE
Progressive profiling example

### ISSUE THREAD

**Issue by christianblust** [auth0/auth0-angular#501]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hi all, 

I use the new universal login experience of auth0 with organizations. I need to also add the first name and the last name of a user to its profile, at the moment auth0 does not offer to expand the registration form, hence I plan to implement it via progressive profiling according to https://www.okta.com/blog/2023/06/using-redirect-with-actions-to-gather-user-info-and-increase-conversions/?amp. 

I was able to create the post login action which does the redirect to my webapp (angular frontend & spring boot backend). I am also able to redirect back to the action via the continue endpoint with the state parameter. 

However, I am not sure how to secure the communication of first and last name (or any other future fields) to auth0. Auth0 suggests using a jwt with a shared secret. I dont think I can save the secret securely in my frontend, which leads me to the thought of saving it in my backend. 

However, in that case I dont know how to secure the api call to my backend, since in that state the client does not have an access token yet. Can this be an open endpoint?

I guess this is the case in the provided example in the blog (https://glitch.com/edit/#!/okta-cic-pp-demo) this is the case. 

I know this is probably not the best place for such a request, however, some sort of angular or spa specific documentation for the flow of progressive profiling would be very much appreciated. 

### Describe the ideal solution

Minimal example of how to do progressive profiling in an angular app with a backend (e.g. spring boot). Also, just and explanation of the general process would be great.

**Comment by frederikprijck** [comment]
Thanks for reaching out. 

> I know this is probably not the best place for such a request, however, some sort of angular or spa specific documentation for the flow of progressive profiling would be very much appreciated.

Progressive profiling happens outside of our SDK and isn't something we can help with from the SDK side.

I recommend reaching out to your contact at Auth0 (Account Manager, Solutions Engineer, ...) and they should be able to assist accordingly.
