### ISSUE TITLE
traceparent & request-header CORS errors when trying to get token

### ISSUE THREAD

**Issue by mfish0005** [auth0/auth0-angular#516]
### Checklist

- [X] The issue can be reproduced in the [auth0-angular sample app](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm working on an Angular/.NET Core Web API app that's been around for a few years.  It's using auth0-angular v1.1.0.  Within the past few months it has started having trouble retrieving the user's info when the app loads.  The app will try a few times to get the user's info but the calls time out and throws CORS errors.

Nothing has really changed auth-wise in the app.  The same urls are present in the trusted origins on Auth0, the app is still deployed to the same urls.  None of the auth logic or flow has changed inside of the Angular app or API.  

These are the errors that are printed to the console once the user logs in and Auth0 redirects back to the app:

```
POST https://login.blah.com/oauth/token 504 (Gateway Timeout)

Access to fetch at 'https://login.blah.com/oauth/token' from origin 'https://www.blah.com' has been blocked by CORS policy: Request header field request-context is not allowed by Access-Control-Allow-Headers in preflight response.

POST https://login.blah.com/oauth/token 504 (Gateway Timeout)

Access to fetch at 'https://login.blah.com/oauth/token' from origin 'https://www.blah.com' has been blocked by CORS policy: Request header field traceparent is not allowed by Access-Control-Allow-Headers in preflight response.
```

For testing I created an HTTP interceptor that strips out both the traceparent and request-context header but somehow the problem still occurs.  This makes me think that maybe the headers are coming from calls inside of the auth0-angular library? 

```ts 
@Injectable()
export class CorsInterceptor implements HttpInterceptor {
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    if (req.headers.has('request-context')) {
      const newHeaders = req.headers.delete('request-context');
      const newReq = req.clone({ headers: newHeaders });

      return next.handle(newReq);
    } 

    if (req.headers.has('traceparent')) {
      const newHeaders = req.headers.delete('traceparent');
      const newReq = req.clone({ headers: newHeaders });

      return next.handle(newReq);
    } 

    return next.handle(req);
    
  }
}
```

I'm running out of ideas on the issue and can't seem to find anyone else with this problem.  Any input would be greatly appreciated.  Thanks in advance

### Reproduction

I'm not sure how to replicate this issue outside of the application.

### auth0-angular version

1.11.0

### Angular version

14

### Which browsers have you tested in?

Chrome, Edge, Firefox

**Comment by frederikprijck** [comment]
Did you update the SDK version in any way? If not, I do not see how this can be an SDK issue.

If you can reproduce this behavior in [our Samples app](https://github.com/auth0-samples/auth0-angular-samples), I can have a look (please do share the reproduction with me in that case). But as mentioned, if this worked before and now does not anymore, and you didnt update the SDK, there should be another reason for this. Happy to give this a debugging spin to see if I can spot anything obvious, but do know you can reach out to your contact at Auth0 for getting a different kind of support here.

> For testing I created an HTTP interceptor that strips out both the traceparent and request-context header but somehow the problem still occurs. 

The interceptor does not strip out both. If you have both present, it only strips out `request-context`.

**Comment by mfish0005** [comment]
Thanks @frederikprijck .  I didn't update the SDK at all but I thought maybe that could be the problem.  Since I can't manually strip out the request-context and traceparent headers from each request I'm pretty sure the auth0-angular library is the one making the requests for the token.  So Auth0 doesn't expect those headers to be sent from auth0-angular and that's causing the CORS errors to be thrown.

I'll reach out to Auth0 directly but last time they just pointed me towards the configuration in the dashboard and I'm pretty sure that's correct as it worked fine for years

**Comment by frederikprijck** [comment]
If the SDK version worked fine before, i don't see why it would stop working.

You can always see if it works if you update, but i cant see why.

Sure the angular sdk is the one doing the request, but we don't add headers, nor do we check on the headers, so the error seems to be originating elsewhere.

Closing, but feel free to ping me if you believe there is an issue with the SDK.
