### ISSUE TITLE
Support Angular 16 for version 1 

### ISSUE THREAD

**Issue by PuriaRad** [auth0/auth0-angular#522]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

For some reason, it's impossible for us to upgrade our auth0/auth0-angular library to version 2 and we are still using `1.11.1`. 
However, this version doesn't support angular 16 and its max version is 15. 

### Describe the ideal solution

It would be appreciated if you support angular 16 for version 1.

**Comment by frederikprijck** [comment]
> For some reason, it's impossible for us to upgrade our auth0/auth0-angular library to version 2

Can you help us understand what's stopping you from updating to v2? Is there anything we can improve so you can update to v2?

**Comment by PuriaRad** [comment]
> > For some reason, it's impossible for us to upgrade our auth0/auth0-angular library to version 2
> 
> Can you help us understand what's stopping you from updating to v2? Is there anything we can improve so you can update to v2?

We customized some functionalities and based on that, we used some methods such as `getUser` that are no longer public in V2. We are planning to rework everything in the future but for now, due to such incompatibilities, we are forced to use the V1 until the whole refractory.

**Comment by frederikprijck** [comment]
Given Angular 15 is still supported for a while, I would recommend to stick to Angular 15 until you are able to migrate our SDK to v2, as v1 does not support v16, and adding support for that might open additional complexities.

Additionally, our SDK is opensource, so feel free to fork it and ensure it works for your situation for the time being.
