### ISSUE TITLE
Version 2.2.1 generates timeout error

### ISSUE THREAD

**Issue by rnimesniciuc** [auth0/auth0-angular#524]
### Checklist

- [X] The issue can be reproduced in the [auth0-angular sample app](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello,
We've been working with @auth/auth-angular version 1.11.1 and recently we wanted to do an update to the latest version which is 2.2.1 
The problem is that now if I try to connect to the application I get an error (server_error : Unable to issue redirect for OAuth 2.0 transaction) . It seems to also generate a TIMEOUT error when trying to access silent token.
Any idea why is this happening?
We didn't changed anything in matters of config and version 1.11.1 works while 2.2.1 is not working. 
Maybe there is something different about getAccessTokenSilently function that we're missing , maybe a parameter or something.
Or maybe in our general config we need to add something extra that was not needed in version 1.11.1 .

### Reproduction

If we go to our app we are being redirected to the custom login from auth0 , we enter the correct credentials and then we are prompted to a page (created by us ) where we display any auth0 error.
This is the error message we receive server_error : Unable to issue redirect for OAuth 2.0  . What is this error about?

### auth0-angular version

2.11.1

### Angular version

15

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Did you configure a `redirect_uri` as per [the configuration in our readme](https://github.com/auth0/auth0-angular#static-configuration)?

With v1, that was not mandatory. With v2, it is. Else, it can not issue the redirect (hence the error)

> We didn't changed anything in matters of config

Be sure to check out [the migration guide](https://github.com/auth0/auth0-angular/blob/main/MIGRATION_GUIDE.md), as you might need to change additional configuration for v2.

**Comment by rnimesniciuc** [comment]
> Did you configure a `redirect_uri` as per [the configuration in our readme](https://github.com/auth0/auth0-angular#static-configuration)?
> 
> With v1, that was not mandatory. With v2, it is. Else, it can not issue the redirect (hence the error)

Yes, we've done this from v1. And the redirect uri is also added in the list of allowed callback url.

**Comment by frederikprijck** [comment]
Can you share your configuration? Redirect URI in v1 is configured differently from v2.

**Comment by rnimesniciuc** [comment]
{
  "domain": "our_dev_tenant_domain",
  "clientId": "our_app_client_id",
  "redirectUri": "callback_url",
  "cacheLocation": "localstorage",
  "useRefreshToken": true,
  "httpInterceptor": {
    "allowedList": [
      "*"
    ]
  }
}

**Comment by frederikprijck** [comment]
Please have a look at the link I shared [above](https://github.com/auth0/auth0-angular/issues/524#issuecomment-1787019649).

You said you configured `redirect_uri` as per our readme, but that's not what I am seeing. 

Update your configuration as per our readme to :

```json
{
  "domain": "our_dev_tenant_domain",
  "clientId": "our_app_client_id",
  "cacheLocation": "localstorage",
  "useRefreshToken": true,
  "authorizationParams": {
    "redirect_uri": "callback_url"
  },
  "httpInterceptor": {
    "allowedList": [
      "*"
    ]
  }
}
```

This is also called out in our migration guide: https://github.com/auth0/auth0-angular/blob/main/MIGRATION_GUIDE.md#introduction-of-authorizationparams.

Closing as this should be answered. Ping me if you have additional problems and we can reopen as needed.
