### ISSUE TITLE
AuthHttpInterceptor: AllowAnonymous logic

### ISSUE THREAD

**Issue by iherbak** [auth0/auth0-angular#525]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hi, I am just dealing a cosmetic/logic issue.

When a route has allowanonymous set to true, the code after a succesfull uri match calls the getAccessTokenSilently and on error checks if it is allowanonymous.
That creates a failed silent auth on the auth0 dashboard.

Thanks

### Describe the ideal solution

Would be good if the code checked for anonymous allowance first.
If it is allowed for anonymous then attach a token if only that is already present, instead of initiating a failed call and only fetch a token if it is not allowed for anonymous access.

### Alternatives and current workarounds

As a workaround I had to enlist all routes need token attached, and that could be tedious.

**Comment by frederikprijck** [comment]
AllowAnonymous does not mean it should be anonymous. If we do not have a token locally, it could still be the case that we can retrieve a token from Auth0, so calling Auth0 is expected to ensure we can still attach a token if we can.

You could have the same request for the interceptor in general, to only attach a token when we have one locally and do not call Auth0, but that's also not how it currently works.

Based on that, I do not think we should change how allowAnonymous works, however, we could add an additional property to  `HttpInterceptorRouteConfig`, something along the lines of: `localOnly` (exact name still up for discussion), which would make the interceptor work with localOnly entirely on a per route config level, would that help your use-case?

What it would look like would be:

```js
{
        uri: '/api/products/*',
        allowAnonymous: true,
        localOnly: true
},
```
We can even use this beyond allowAnonymous:
```js
{
        uri: '/api/products/*',
        localOnly: true
},
```
This last example would not try and renew the token if there isn't one found locally.

**Comment by iherbak** [comment]
That would be great to have it, thanks

**Comment by frederikprijck** [comment]
Not something I can prioritize soon, but will see to implement this when I find some time.

**Comment by frederikprijck** [comment]
Having looked at this in more depth, I realize this should already be possible:

```
{
        uri: '/api/products/*',
        allowAnonymous: true,
        tokenOptions: {
            cacheMode: 'cache-only'
        }
},
```

TokenOptions allows for all kinds of customization on a per-interceptor-configuration basis, including setting the `cacheMode` to `cache-only`.

Closing, as I think the requested feature is already possible. Can always reopen if needed.
