### ISSUE TITLE
unexpected post-login redirect behavior

### ISSUE THREAD

**Issue by markanye** [auth0/auth0-angular#53]
### Describe the problem

I'm using auth0-angular to provide Auth0 login for the admin module of a small Angular-based web application. I've configured auth0-angular to redirect to my admin route after login. The import config in my main app module looks like this:

```javascript
AuthModule.forRoot({
      domain: 'MY-DOMAIN.us.auth0.com',
      clientId: 'MY-CLIENTID',
      redirectUri: 'http://localhost:4200/admin',
    }),
```
Initially this works as expected. I'm redirected back to http://localhost:4200/admin after login. BUT, after the login is processed, auth0-angular then fires Router.navigate('/') and sends me to the application root.

Is this the expected behavior? Instead, I would like to STAY on the '/admin' route after the session is loaded, instead of automatically navigating back to '/'. Is there a way to configure that behavior?

### Reproduction

This should be simple to reproduce by configuring a redirectUri to return the user somewhere other than '/'.

### Environment

> Please provide the following:

- **Version of `auth0-angular` used:** 1.0.0
- **Which browsers have you tested in?** Chrome 85.0.4183.83
- **Which version of Angular have you tested with?** 9.1.12

**Comment by stevehobbsdev** [comment]
The way we'd expect you to do this is by using [`AuthGuard`](https://github.com/auth0/auth0-angular#protect-a-route). If you remove the configuration for `redirectUri` and instead use `AuthGuard` in the `canActivate` hook on the route to your admin module, you should then get the desired behaviour.

Could you try this out and let me know how you get on?

**Comment by markanye** [comment]
That does the trick. Thank you @stevehobbsdev for the fast help!

**Comment by stevehobbsdev** [comment]
No worries!

**Comment by sean-hurley** [comment]
@stevehobbsdev @markanye 

Can either of you expand on this or provide an example of how you're getting this to work? No matter what I try, it bounces me back to the root of my application.

I'm using auth0-angular 1.0.0 and angular 10.0.8

Thank you!

**Comment by markanye** [comment]
@sean-hurley All I did was add a canActivate check to the /admin route that I'm redirecting to. Looks like this in my app:

```javascript
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

// Import the authentication guard
import { AuthGuard } from '@auth0/auth0-angular';


const routes: Routes = [{
  path: '',
  loadChildren: () => import('./checkout/checkout.module').then(m => m.CheckoutModule),
}, {
  path: 'receipt',
  loadChildren: () => import('./receipt/receipt.module').then(m => m.ReceiptModule),
}, {
  canActivate: [ AuthGuard ],
  path: 'admin',
  loadChildren: () => import('./admin/admin.module').then(m => m.AdminModule),
}, {
  path: '**', redirectTo: '/',
}];

@NgModule({
  imports: [RouterModule.forRoot(routes, {
    initialNavigation: 'enabled'
})],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

**Comment by sean-hurley** [comment]
@markanye Thanks for the quick reply!

I have roughly the same thing in my test app I created, but how or at what point are you actually sending the user to your `admin` module? Is that occurring as part of the call to `loginWithRedirect(...)`?

I've tried specifying the route there as well as in the `redirectUri` parameter of the `AuthModule.forRoot({...})` as well as having it in both places.

EDIT: Or...are you allowing Auth0 to redirect to the root of your app, where you then send them to the admin module via a call to something like `router.navigate(['/admin'])`?

**Comment by markanye** [comment]
@sean-hurley 

Hey Sean, the way it's working in my app is as follows:

1. An unauthenticated user visits the /admin route.
1. The canActive AuthGuard fails, which triggers a redirect to Auth0 for login, without an explicit call to loginWithRedirect()
1. User completes login and is redirected back to the /admin route as a result of the redirectUri config (see start of this thread)
1. The login is processed by the auth0-angular service, the canActive check now passes, and user ends up on /admin.

Hope this helps!

**Comment by sean-hurley** [comment]
@markanye 

Hey Mark,

That does actually help clear up how your scenario is working and mine...isn't. :)

I effectively need a "landing" or "loading" page after the user signs in so I can grab some data (via an api call) and decide where to send them  based on what was returned via that call. Doesn't appear there's a way to do that if Auth0 is going to call `Router.navigate('/')` regardless.

Thanks again!

**Comment by markanye** [comment]
@sean-hurley I would imagine that the setup I'm using could work for your scenario. If my /admin route became instead something like /landing, then anyone who made it through the canActivate guard could be redirected on to wherever they need to go in the app, based on their account details.

**Comment by sean-hurley** [comment]
@markanye 

I see what you mean there. I just might be able to make something like that work. Thanks for the tip!

**Comment by stevehobbsdev** [comment]
Just a heads up to say that I appreciate that the usage of `redirectUri` is a little weird and I think it should redirect back to the place you specify rather than the route page all the time - let me do some testing around that and see what I can do.

**Comment by sean-hurley** [comment]
@stevehobbsdev 

Thanks for the follow up! I was thinking that as well. It's likely not a common scenario, but in my case, my entire application is secure (you can only really get to a single landing page with a login button) and once they've authenticated, I can then retrieve their info and decide where they need to go within the app.

I was able to make it work using Mark's suggestion by routing them to my AuthGuard-ed callback/loading page via `router.navigate(["/loading"])` when they click the "login" button. That triggered the auth flow, then sent them back where I wanted.

I did need to do that AND set the "redirectUri", otherwise the auth flow would still send them back to the app root, THEN to my loading page. It happened very quickly, but still wasn't an ideal user experience.

Thanks for looking into it!
