### ISSUE TITLE
Errors and warnings from the closure compiler

### ISSUE THREAD

**Issue by levicc00123** [auth0/auth0-angular#53]
**28 warnings:**
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property module never defined on angular at line 27 character 2
  angular.module('auth0', [
  ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property factory never defined on ? at line 32 character 2
  angular.module('auth0.interceptor', []).factory('authInterceptor', [
  ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property module never defined on angular at line 32 character 2
  angular.module('auth0.interceptor', []).factory('authInterceptor', [
  ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property has never defined on $injector at line 41 character 15
          if (!$injector.has('auth')) {
               ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property $broadcast never defined on $rootScope at line 54 character 12
            $rootScope.$broadcast('auth0.forbidden', response);
            ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property module never defined on angular at line 61 character 2
  angular.module('auth0.storage', ['ngCookies']).service('authStorage', [
  ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property service never defined on ? at line 61 character 2
  angular.module('auth0.storage', ['ngCookies']).service('authStorage', [
  ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property module never defined on angular at line 85 character 2
  angular.module('auth0.service', ['auth0.storage']).provider('auth', functio...
  ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property provider never defined on ? at line 85 character 2
  angular.module('auth0.service', ['auth0.storage']).provider('auth', functio...
  ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property invoke never defined on $injector at line 147 character 12
            $injector.invoke(handler, auth, locals);
            ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property $$phase never defined on $rootScope.$root at line 151 character 22
          var phase = $rootScope.$root.$$phase;
                      ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property $root never defined on $rootScope at line 151 character 22
          var phase = $rootScope.$root.$$phase;
                      ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property $apply never defined on $rootScope at line 157 character 12
            $rootScope.$apply(fn);
            ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property $on never defined on $rootScope at line 190 character 8
        $rootScope.$on('$locationChangeStart', function (e) {
        ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property parseHash never defined on config.auth0lib at line 191 character 27
          var hashResult = config.auth0lib.parseHash($window.location.hash);
                           ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property getSSOData never defined on config.auth0js at line 203 character 14
              config.auth0js.getSSOData(applied(function (err, ssoData) {
              ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property lastUsedConnection never defined on ssoData at line 207 character 32
                    connection: ssoData.lastUsedConnection.strategy
                                ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property strategy never defined on ssoData.lastUsedConnection at line 207 character 32
                    connection: ssoData.lastUsedConnection.strategy
                                ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property $on never defined on $rootScope at line 214 character 8
        $rootScope.$on('auth0.forbidden', function (e, response) {
        ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property $on never defined on $rootScope at line 218 character 10
          $rootScope.$on('$routeChangeStart', function (e, nextRoute) {
          ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property $on never defined on $rootScope at line 227 character 10
          $rootScope.$on('$stateChangeStart', function (e, to) {
          ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property username never defined on options at line 240 character 33
          if (!options.popup && !options.username && (!successHandlers || suc...
                                 ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property getDelegationToken never defined on config.auth0js at line 282 character 10
          config.auth0js.getDelegationToken(clientID, this.idToken, options, ...
          ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property id_token never defined on delegationResult at line 286 character 30
              defered.resolve(delegationResult.id_token);
                              ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property promise never defined on defered at line 289 character 17
          return defered.promise;
                 ^
JSC_WRONG_ARGUMENT_COUNT: Function onSigninOk: called with 3 argument(s). Function requires at least 4 argument(s) and no more than 4 argument(s). at line 304 character 35
              var profilePromise = onSigninOk(idToken, accessToken, state);
                                   ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property promise never defined on defered at line 320 character 17
          return defered.promise;
                 ^
JSC_POSSIBLE_INEXISTENT_PROPERTY: Property promise never defined on defered at line 341 character 17
          return defered.promise;
                 ^

**Comment by rolodato** [comment]
This issue is likely not relevant anymore, closing for now.
