### ISSUE TITLE
Web workers error

### ISSUE THREAD

**Issue by caenguidanos** [auth0/auth0-angular#54]
### Describe the problem

I create a web-worker via Angular CLI and without any configuration the build fail with:

```bash
ERROR in ./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js
Module parse failed: Cannot read property 'length' of undefined
```

### What was the expected behavior?

Good way to build

### Reproduction

1. Create a web-worker with Angular CLI

```bash
ng g web-worker web-worker
```

2. Build the project with:

```bash
ng build
```

3. Get error:

```bash
ERROR in ./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js
Module parse failed: Cannot read property 'length' of undefined
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
TypeError: Cannot read property 'length' of undefined
    at /home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/worker-plugin/src/index.js:55:46
    at SyncBailHook.eval (eval at create (/home/path/to/project/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:16)
    at Parser.walkNewExpression (/home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Parser.js:1822:25)
    at Parser.walkExpression (/home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Parser.js:1613:10)
    at Parser.walkExpressions (/home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Parser.js:1569:10)
    at Parser.walkSequenceExpression (/home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Parser.js:1726:36)
    at Parser.walkExpression (/home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Parser.js:1619:10)
    at Parser.walkTerminatingStatement (/home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Parser.js:1081:32)
    at Parser.walkReturnStatement (/home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Parser.js:1085:8)
    at Parser.walkStatement (/home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Parser.js:985:10)
    at Parser.walkStatements (/home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Parser.js:868:9)
    at /home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Parser.js:1017:9
    at Parser.inBlockScope (/home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Parser.js:2060:3)
    at Parser.walkBlockStatement (/home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Parser.js:1014:8)
    at Parser.walkStatement (/home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Parser.js:949:10)
    at /home/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Parser.js:1702:10
```

### Environment

- **Version of `auth0-angular` used:** 1.0.0
- **Which version of Angular have you tested with?** 10.1.2

**Comment by stevehobbsdev** [comment]
👋  Thanks for raising. I'm afraid I'm unable to reproduce this. With `@auth0/auth0-angular@1.0.0` and Angular 10.1.2, I did the following:

* `ng new test-app`
* `ng add @auth0/auth0-angular`
* I included the module and set up a basic login button so that I could log in
* `ng g web-worker web-worker`
* `ng build`

The app builds and runs fine. I even changed the Auth0 configuration to add `useRefreshTokens: true` (a web worker is only used for refresh tokens and in-memory storage) but still works.

Anything more you can tell me about your setup? Do you have a small sample you can share that reproduces the isssue?

**Comment by caenguidanos** [comment]
If i create a new project and add auth0 and a web-worker, nothing happens, fine. But, in the project we have some simple route `guards`:

```ts
const routes: Routes = [
  {
    path: '',
    component: LayoutDefaultComponent,
    children: [
      {
        path: '',
        component: InicioComponent,
      },
    ],
    canActivate: [AuthGuard],
  },
  {
    path: 'almacen',
    component: AlmacenLayoutComponent,
    loadChildren: () =>
      import('./pages/almacen/modules/almacen.module').then(
        (m) => m.AlmacenModule
      ),
    canActivate: [AuthGuard],
  },
  ...
]
```

and in the module.ts

```ts
imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    AuthModule.forRoot({
      domain: environment.auth0.domain,
      clientId: environment.auth0.clientId,
    }),
  ],
```

and fails with the same error of the other message.

It's the only configuration that i have, nothing complex.

Thanks for your time!

**Comment by stevehobbsdev** [comment]
Thanks, and does the failure continue to happen when you run `ng build`, or when you try to access a particular route?

**Comment by caenguidanos** [comment]
When run the ng development command: `ng serve`. And fails at build step.

**Comment by GQuantrill** [comment]
I'm also seeing this with Angular 10.1.3 and auth0-spa-js 1.12.1. (Tried previous versions as well).

Running `ng build` or `ng serve` creates the same log.

**Comment by stevehobbsdev** [comment]
I'm afraid I'm still not seeing the issue. This is the app I'm working with: https://github.com/stevehobbsdev/angular-test-app

Could you please review it? If you're still getting issues, **please** can you provide a small repro that I can use to investigate.

**Comment by caenguidanos** [comment]
@stevehobbsdev here a reproduction: 

https://github.com/cenguidanos/angular-test-auth0-log

maybe the problem is `@angular-builders/custom-webpack`, luck!!

**Comment by stevehobbsdev** [comment]
Possibly. I can see the error happening with your repro, thanks for that. I've tried adding the custom webpack plugin to my own sample and copying some bits from your repro, but I still can't get it to break.

So I can't see exactly what's causing it. I have an idea though; it's actually the underlying SDK ([`auth0-spa-js`](https://github.com/auth0/auth0-spa-js)) that is being reported in the error - that does use a web worker but also it is not built using Webpack, so I wonder if the modules are incompatible.

Please let me know if you find anything further that I can help you diagnose.

**Comment by GQuantrill** [comment]
My issue has something to do with my webworks.  I'll try to put a sample app together but essentially, if I remove the line
`"webWorkerTsConfig": "tsconfig.worker.json"` in the angular.json, everything works as intended.

**Comment by stevehobbsdev** [comment]
Looks like we might be butting up against this issue raised on `worker-plugin`: https://github.com/GoogleChromeLabs/worker-plugin/issues/93

**Comment by jebbench** [comment]
I've submitted a PR (https://github.com/GoogleChromeLabs/worker-plugin/pull/94) that fixes this issue but I then get:
```
ERROR in ./.../my-worker.worker.ts (C:/code/worker-plugin/dist/loader.js?name=0!./.../my-worker.worker.ts)
Module build failed (from C:/code/worker-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: The AngularCompilerPlugin was not found. The @ngtools/webpack loader requires the plugin.
```

Downgrading `worker-plugin` to `4.0.3` fixed our build:

```
{
  "scripts": {
    "preinstall": "npx npm-force-resolutions",
    ...
  },
  "resolutions": {
    "worker-plugin": "4.0.3"
  },
  ...
}
```

**Comment by stevehobbsdev** [comment]
I'll close this for now as it doesn't seem like an issue with this SDK, but if that turns out to be wrong, please feel free to reopen.
