### ISSUE TITLE
Possible memory leak in user$

### ISSUE THREAD

**Issue by hrant-ian** [auth0/auth0-angular#56]
### Describe the problem

Calling `toPromise` on the `user$` observable seems to cause a never ending request to `/oauth/token` eventually leading to the browser crashing due to ever increasing memory.

```
public async getCurrentUser(): Promise<any> {
    return await this.auth.user$.toPromise<any>();
}
```

### What was the expected behavior?

Return a result after the request has been completed. 

### Reproduction

See description.

### Environment

> Please provide the following:

- **Version of `auth0-angular` used:** 0.2.1 and 1.0.0
- **Which browsers have you tested in?** Chrome 
- **Which version of Angular have you tested with?** Angular 10
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
Thanks @hrant-ian - the `user$` observable does not complete, and using `.toPromise()` waits until an observable completes before resolving. Can you try piping it through a `take(1)` or similar to see if that resolves your issue?

**Comment by stevehobbsdev** [comment]
Closing this for now but feel free to raise any more questions you might have.
