### ISSUE TITLE
AuthGuard on paths redirects to the base url app

### ISSUE THREAD

**Issue by cmprojectcm** [auth0/auth0-angular#572]
### Checklist

- [X] The issue can be reproduced in the [auth0-angular sample app](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have an issue, using AuthGuard on routes. After successful login, when I try to navigate to the path protected with AuthGuard, it redirects me to the root url, like for example: http://localhost:7200.

I have noticed, when I try to access the AuthGuard route, on Network I see a request with name `token` and status code 401 Unauthorized.

Please have in mind that am using a Regular Web Application service on my auth0 account for this angular project and I have provided the correct clientId as long as the domain.

I have initialized the auth0-angular like below:

Inside app.module I added:

`    AuthModule.forRoot({
      domain: [domain],
      clientId: '[clientId]',
      authorizationParams: {
        redirect_uri: `${window.location.origin}`,
      },
    }),`

On app-routing.module.ts 

`    import { DashboardComponent } from './modules/dashboard/dashboard.component';
    import { AuthGuard } from '@auth0/auth0-angular';
    
    const routes: Routes = [
    
      {
        path: 'dashboard',
        component:DashboardComponent,
        canActivate: [AuthGuard],
      },
    ];
    
    @NgModule({
      imports: [RouterModule.forRoot(routes)],
      exports: [RouterModule],
    })
    export class AppRoutingModule {}`

### Reproduction

Step 1: Iinitialize a Regular Web Application On auth0.com

Step 2: Copy the code above

Step 3: And test it

### auth0-angular version

2.2.1

### Angular version

16.2.9

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
You should not use a regular web app, and that is why its giving you unauthorized.

A regular web app requires a client secret (not sending one will give you unauthorized), which you should not set in a SPA, please ensure to use a SPA application on auth0, or set Token Authentication Method to none (but the recommendation is using a SPA app in auth0 when u use our SPA SDKs).

Once the above is resolved, the authguard should move you back to the expected route.

Also know, in case of an error, the SDK redirects to root, unless you specify another errorPath when configuring the SDK, see https://github.com/auth0/auth0-angular/blob/main/projects/auth0-angular/src/lib/auth.service.ts#L101
