### ISSUE TITLE
Add Angular 17 support

### ISSUE THREAD

**Issue by mbrammer** [auth0/auth0-angular#586]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Just tried to update to Angular 17 and got this errors:  
```
Package "@auth0/auth0-angular" has an incompatible peer dependency to "@angular/common" (requires ">=12 <=15" (extended), would install "17.2.3").
Package "@auth0/auth0-angular" has an incompatible peer dependency to "@angular/core" (requires ">=12 <=15" (extended), would install "17.2.3").
Package "@auth0/auth0-angular" has an incompatible peer dependency to "@angular/router" (requires ">=12 <=15" (extended), would install "17.2.3").
```
I'm actually running on Angular 16.2.12 already, so this is somehow strange because the messages says `requires ">=12 <=15"`.  
  
Also is there a doc which indicates which Angular versions are supported? I only found a hint in the release notes that mentioned Angular 15 support within v1.11.1

### Describe the ideal solution

`@auth0/auth0-angular` should support latest Angular version.

**Comment by frederikprijck** [comment]
You want to move to v2 of our SDK, which supports Angular 17.

v1 only supports up until 15.

We have [a migration guide](https://github.com/auth0/auth0-angular/blob/main/MIGRATION_GUIDE.md) on how to move to v2, but I am happy to help wherever needed if you have any difficulties.

The general rule is, our latest version supports all current versions supported by Angular, see https://github.com/auth0/auth0-angular?tab=readme-ov-file#requirements

When not using the latest version, compatibility depends on the time that version was released.

**Comment by mbrammer** [comment]
I am using `"@auth0/auth0-angular": "^2.2.3",` and getting this error...

**Comment by frederikprijck** [comment]
That's not something that should be happening.

As you can see [here](https://www.npmjs.com/package/@auth0/auth0-angular?activeTab=code),  v2.2.3 has a peerDependency of:

```
  "peerDependencies": {
    "@angular/common": ">=13",
    "@angular/core": ">=13",
    "@angular/router": ">=13"
  },
```

While your error talks about `requires ">=12 <=15"`, which happens to be our peerDependencies configuration on v1, see: https://www.npmjs.com/package/@auth0/auth0-angular/v/1.11.1?activeTab=code

What's the output of `npx npm-why @auth0/auth0-angular` on your project?
