### ISSUE TITLE
Login-Dialog always in English

### ISSUE THREAD

**Issue by arthurbrack** [auth0/auth0-angular#59]
### Describe the problem
In my browser German is the default language. However, the login dialog provided by Auth0 is always in English.

### What was the expected behavior?
The login dialog should use the language that is configured in the browser.

### Reproduction
1. Use the default login example provided by auth0-angular
2. Set German as the default language in Chrome

### Environment

- **Version of `auth0-angular` used:** 1.0.0
- **Which browsers have you tested in?** Chrome
- **Which version of Angular have you tested with?** 9.1.0
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
Thanks for raising, @arthurbra. The SDK itself does not control the language that you see in Universal Login; this is determined using a few different criteria.

Please see [this doc](https://auth0.com/docs/universal-login/universal-login-internationalization) for more info. Please note that the process changes depending on whether you're using the New experience or the Classic one.

If you still have further questions, the best place to get answers would be the [Auth0 Community Forums](https://community.auth0.com).
