### ISSUE TITLE
Getting Error on get Tokens  "/oauth2/v2.0/oauth/token"

### ISSUE THREAD

**Issue by hammadtariq98** [auth0/auth0-angular#590]
### Checklist

- [X] The issue can be reproduced in the [auth0-angular sample app](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

we implement  azure microsoft multi-tenant identity Version 2 which uses OAuth 2.0  for getting tokens the API route is` "/oauth2/v2.0/token"`  but SDK's get token route is  `"/oauth2/v2.0/oauth/token"`. How can I override the route to get tokens

### Reproduction

`  provideAuth0({
      domain:  'domain',
      clientId: 'clientId',
      authorizationParams: {
        organization: 'organization',
        scope: 'openid profile offline_access',
        redirect_uri: 'http://localhost:4200/login',
        invitation: 'http://localhost:4200/login',
        prompt: 'select_account',
        audience: 'http://localhost:4200',
      },
    }),`

### auth0-angular version

2.2.3

### Angular version

17

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Thanks for reaching out. This SDK is for Auth0, and it does not support using with other vendors, so there is no way to override the route.
