### ISSUE TITLE
Unknown or invalid refresh token error

### ISSUE THREAD

**Issue by CharlieGreenman** [auth0/auth0-angular#596]
### Checklist

- [X] The issue can be reproduced in the [auth0-angular sample app](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Similar issue as described here: https://community.auth0.com/t/unknown-or-invalid-refresh-token-after-refresh-token-expired/118435

We have users that are using our auth0/angular application that are sending us this error and we have to walk through with them to clear their cache to re-login. This error started happening after migrated to the latest `"@auth0/auth0-angular": "^2.2.3",`. 

I was wondering if there is a recommended approach for this one? For instance, Ideally we would ask users to re-login if it is an invalid refresh token. 

### Reproduction

I'm trying to think about it, but refresh tokens(from experience) always very difficult to reproduce. It is a similar experience to what is happening here: https://community.auth0.com/t/unknown-or-invalid-refresh-token-after-refresh-token-expired/118435

### Additional context

NA

### auth0-angular version

^2.2.3

### Angular version

17.1.2

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Previously (with v1), when using Refresh Tokens, we used to fallback to iframes. As this relies on third party cookies, and the fact that more and more browsers are blocking those by default, with v2 we no longer fallback automatically.

When using refresh tokens, without the fallback, the SDK may throw an error when there is no refresh token or the refresh token is no longer valid.

When you do use the fallback, the SDK will try and fallback to using iframes. If that works, all will be good. If it doesn't work, you will receive a `login_required` error.

There are a couple of things I can recommend:

- Keep everything as is, but catch the mentioned error and redirect the user to Auth0 to login again.
- Or you can set `useRefreshTokensFallback` to true, which will fallback to iframes. Note that this relies on third party cookies. So if these are blocked, or there is no active session with Auth0, it will still throw `login_required`, which you need to handle accordingly (e.g. by redirecting to Auth0 for logging in).

Hopefully this brings some clarification. 

Closing, but feel free to ping me for further questions / clarification.

**Comment by CharlieGreenman** [comment]
Thank you for this. My auth config now looks like: 

```
useRefreshTokens: true,
useRefreshTokensFallback: true,
```  

> it will still throw login_required, which you need to handle accordingly (e.g. by redirecting to Auth0 for logging in).

Would you happen to know how this can be handled? Right now I have an HTTP auth interceptor, and an auth config and everything is handled out of the box. Will this login re-direct likewise be handled by auth0 automatically?

**Comment by frederikprijck** [comment]
There is an error observable on the AuthService you can subscribe to, and handle errors accordingly.

**Comment by CharlieGreenman** [comment]
@frederikprijck I am thinking about how to catch this error. Let's say for instance we use graphql and specifically apollo client. 

We have an HTTP interceptor which taps into 
```
return this.authService.isAuthenticated$.pipe(
      take(1),
      mergeMap((isAuthenticated: any) => { 
```      

Would we be able to update this HTTP interceptor to understand if a refresh token should be supplied? Note, for some of our APIs we have a public view and a private view. So not being authenticated just means the public view and not necessarily an incorrect refresh token. 

Thank you for your help.
