### ISSUE TITLE
NullInjectorError: No provider for AbstractNavigator

### ISSUE THREAD

**Issue by michaelvobejda** [auth0/auth0-angular#60]
### Describe the problem

I keep getting a `NullInjectorError` in the browser's console when I import `AuthService` into a component. I have tried adding `AuthService` as a provider in my `app.module.ts` as well as in the component, to no avail. I have imported and initialized AuthModule in  `app.module.ts`.
![image](https://user-images.githubusercontent.com/19294162/94768198-bd330e80-037c-11eb-8b37-5365aa052fe8.png)

### What was the expected behavior?

No error should be thrown, I have mirrored the setup from https://auth0.com/docs/quickstart/spa/angular?framed=1&sq=1#configure-auth0

### Reproduction

1. `ng new`
2. `npm install @auth0/auth0-angular`
3. declare `AuthModule.forRoot(...)` in module
4. add `private auth: AuthService` to `AppComponent` constructor

### Environment

- **Version of `auth0-angular` used:**
"@auth0/auth0-angular": "^1.0.0"
- **Which browsers have you tested in?**
Chrome, Safari
- **Which version of Angular have you tested with?**
"@angular/core": "~8.2.3"
- **Other modules/plugins/libraries that might be involved:**
none

**Comment by rnicholls** [comment]
@michaelvobejda were you able to figure this out. I am having the same issue.
