### ISSUE TITLE
AuthHttpInterceptor adds auth_token instead of id_token

### ISSUE THREAD

**Issue by testud** [auth0/auth0-angular#61]
### Describe the problem

AuthHttpInterceptor attaches the auth_token to the Authentication header when making an api call (Bearer [auth_token]).
The auth_token is much shorter than the id_token.

### What was the expected behavior?

AuthHttpInterceptor attaches the id_token to the Authentication header when making an api call (Bearer [id_token]).
The id_token is much longer than the auth_token.

### Reproduction

1. Add @auth0/auth0-angular to your project
2. Register AuthHttpInterceptor in the app module
3. Check the authentication header of an api request in your browser (network tab)

app.module.ts
`providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: AuthHttpInterceptor,
      multi: true
    }
  ],`

Screenshot of browser network tab
![grafik](https://user-images.githubusercontent.com/47748510/95060302-60c44c00-06fa-11eb-910a-1d1e1fb881d1.png)

### Environment

- Version of `auth0-angular` used: 1.0.0
- Firefox (browser is not relevant)
- Version of angular: 10.0.2

**Comment by testud** [comment]
As a temporary solution I wrote my own interceptor. I use `@auth0/auth0-spa-js` and call `getTokenSilently()`. By using this function I receive the id_token.

**Comment by stevehobbsdev** [comment]
Typically ID tokens are not sent to APIs, you do want to be using an access token, which is what the built-in Http Interceptor uses.

Looking at your example, you are sending an access token but it is not a JWT. I suspect that you are not specifying an `audience` value when configuring `AuthModule`. If you do this, your app will receive a JWT access token which you can then send to an API.

Please see the [API quickstart](https://auth0.com/docs/quickstart/spa/angular/02-calling-an-api) which shows how to specify the audience for an API.

Closing for now but feel free to raise any more questions you have.
