### ISSUE TITLE
Don't forget custom base href

### ISSUE THREAD

**Issue by Mikastark** [auth0/auth0-angular#625]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hi!

I recently deployed an Angular app using this package on a shared HTTP server, which requires hosting the app in a subfolder (e.g., https://www.mysite.fr/foo/). To accommodate this, I adjusted the base href during build time (ng build --base-href /foo/).

Following the [Auth0 Angular quickstart](https://auth0.com/docs/quickstart/spa/angular/01-login#register-and-providing-auth0), I noticed that you recommend using window.location.origin as the redirect_uri. However, I was surprised by this suggestion because document.baseURI accounts for the base href, while window.location.origin does not.

Could you clarify why window.location.origin is recommended over document.baseURI?

### Describe the ideal solution

Update [Auth0 Angular quickstart](https://auth0.com/docs/quickstart/spa/angular/01-login#register-and-providing-auth0) by replacing the code example by this : 

```ts
import { bootstrapApplication } from '@angular/platform-browser';
import { provideAuth0 } from '@auth0/auth0-angular';
import { AppComponent } from './app.component';

bootstrapApplication(AppComponent, {
  providers: [
    provideAuth0({
      domain: '{yourDomain}',
      clientId: '{yourClientId}',
      authorizationParams: {
        redirect_uri: document.baseURI
      }
    }),
  ]
});
```

Also update [Add logout to your application example](https://auth0.com/docs/quickstart/spa/angular/01-login#add-logout-to-your-application) the same way : 

```ts
import { Component, inject } from '@angular/core';
import { AuthService } from '@auth0/auth0-angular';
import { DOCUMENT } from '@angular/common';

@Component({
  selector: 'app-auth-button',
  template: `
    <ng-container *ngIf="auth.isAuthenticated$ | async; else loggedOut">
      <button (click)="logout()">
        Log out
      </button>
    </ng-container>

    <ng-template #loggedOut>
      <button (click)="auth.loginWithRedirect()">Log in</button>
    </ng-template>
  `,
  standalone: true
})
export class AuthButtonComponent {
  private readonly document = inject(DOCUMENT);
  private readonly auth = inject(AuthService);

  logout(): void {
    this.auth.logout({ logoutParams: { returnTo: this.document.baseURI } })
  }
}
```

### Additional context

I found this [related topic](https://community.auth0.com/t/problem-with-angular-login-if-compiled-with-base-href/36583) but the proposed solution is partial and seems overcomplicated to me (using `LocationStrategy`)

**Comment by frederikprijck** [comment]
The window.location.origin is something that works in a lot of situations and is what we add to our quickstart, you are free to change it to whatever you like.

I don't think baseURI is commonly known or used, and it may confused more people (and I have not tried if it works in as many use-cases as window.location.origin).

You can use any URL that works for you.

**Comment by Mikastark** [comment]
It’s unfortunate I didn’t convince you, as document.baseURI is massively supported and using it cover the same use-cases as window.location.origin and more (as I guess, the first use the later).
