### ISSUE TITLE
Feature Request: Open signup tab by default

### ISSUE THREAD

**Issue by iimpulse** [auth0/auth0-angular#68]
### Describe the problem you'd like to have solved

> I would like signup tab to be displayed by default on the universal login.Leveraging this api, I do not see options for such a feature.

### Describe the ideal solution

> A parameter to pass to loginWithRedirect similar to other sdks {screen_hint:"signup"}.

## Alternatives and current work-arounds

> None that I know of, but there seems to be support in the auth-spa-js client. I could be missing something here..

**Comment by frederikprijck** [comment]
Hi @iimpulse ,

Considering this is just a wrapper around our SPA-JS SDK, this is already possible by passing `screen_hint: signup` to loginWithRedirect.

In our playground application, it works when you change this line https://github.com/auth0/auth0-angular/blob/master/projects/playground/src/app/app.component.ts#L45 to:

```
this.auth.loginWithRedirect({
  screen_hint: 'signup'
});
```

Keep in mind that this only works when u use the new login experience, which you can configure in Auth0:

![image](https://user-images.githubusercontent.com/2146903/96046493-dc00cd00-0e73-11eb-9d87-c0a2fcc9a15d.png)

Let me know if this doesnt work.
