### ISSUE TITLE
ERROR: Configuration must be specified either through AuthModule.forRoot or through

### ISSUE THREAD

**Issue by GipHub123** [auth0/auth0-angular#73]
### Describe the problem

I'm having troubles with dynamic configuration.
According to the log -statements order seems to be correct -> Config should be set. 

### What was the expected behavior?
Configuration should be set correctly. 

### Reproduction

**AppModule**
```
@NgModule({

  declarations: [
    AppComponent
  ],
    providers: [
    EnvironmentStore,
    {provide: APP_INITIALIZER, useFactory: auth0Factory, deps: [AuthClientConfig, EnvironmentStore], multi: true}
  ]
  imports: [
    AuthModule.forRoot()
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
```

**Factory Method**
```
function auth0Factory(authClientConfig: AuthClientConfig, environmentService: EnvironmentStore): () => Promise<void> {

  return () => {
    const config: AuthenticationConfig = environmentService.config.authentication;
    authClientConfig.set(config.auth0);
    console.log('Called Auth0 factory');
    console.log('Auth config:' + JSON.stringify(authClientConfig.get()));

    return of<void>().toPromise();

  };
}
```

**EnvironmentStore** 

```
@Injectable({
  providedIn: 'root'
})
export class EnvironmentStore {

  private readonly _config: GeneralServiceConfig;

  constructor(@Inject(SERVICE_CONFIG_TOKEN) config: GeneralServiceConfig) {
    this._config = config;

    console.log('EnvironmentStore constructor called');
  }

  public get config(): GeneralServiceConfig {
    return this._config;
  }

}
```

**Error** 

![auth0_error](https://user-images.githubusercontent.com/12637608/97012761-e2b4d180-1550-11eb-8834-26254430289f.png)

If so, provide steps:

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

- **Version of `auth0-angular` used:** 1.2.0
- **Which browsers have you tested in?** Crome
- **Which version of Angular have you tested with?** 10.2
- **Other modules/plugins/libraries that might be involved:** -

**Comment by frederikprijck** [comment]
Hi @GipHub123,

Are you perhaps importing `AuthModule.forRoot()` somewhere else as well? Also where and how are u injecting the AuthService ?

**Comment by GipHub123** [comment]
AuthModule.forRoot() is imported only in one place. 

AuthService is injected in AuthenticationStore

```
@Injectable({
  providedIn: 'root'
})
export class AuthenticationStore {

  private readonly _authService: AuthService;

  constructor(authService: AuthService) {
    this._authService = authService;
  }

}
```

**Comment by stevehobbsdev** [comment]
@GipHub123 I'm not able to reproduce this, unfortunately. If I able to see some config at the point where I call `authConfigClient.get()` (as in, it's not `undefined`) then everything works as expected.

I think what would help here is a small sample that reproduces the problem so we can take a closer look.

**Comment by GipHub123** [comment]
This might be tricky to reproduce since original configuration is not the simplest one :| 
I'll keep tabs on if anyone else has similar problems. You can close the issue if needed

**Comment by stevehobbsdev** [comment]
Thanks @GipHub123, if you manage to get a repro then please let us know and reply here.

**Comment by laverix** [comment]
same here
