### ISSUE TITLE
AuthGuard not firing when access token has expired

### ISSUE THREAD

**Issue by turkingj** [auth0/auth0-angular#75]
### Describe the problem

> Following the quick start guide when I reduce the Token Expiration (Seconds)* to 30, all routes with the AuthGuard still fire.

### What was the expected behaviour?

> AuthGuard should redirect to Auth0 universal login page if isAuthenticated is false.

### Reproduction
1. Create a new Angular app
2. Follow Auth0 Angular quickstart guide
3. Set API app to Token Expiration (Seconds)* to 30
4. Protect the user profile component with an AuthGuard
5. Click on /profile route, user profile successfully displayed
6. Wait 30 seconds, click back to home and then onto /profile, user profile is not displayed but the AuthGuard has not fired.

### Environment

> Please provide the following:

- **Version of `auth0-angular` used: 1.2
- **Which browsers have you tested in? Chrome
- **Which version of Angular have you tested with? 10.2
- **Other modules/plugins/libraries that might be involved: N/A

**Comment by frederikprijck** [comment]
The Access Token that is issued for the configured API Audience is used to access that API, which is not part of the AuthGuard.
The interceptor is responsible for fetching a new Access Token if the existing one has expired. So as long as there is no Interceptor involved, a new token will not be requested.

Having an expired Access Token for the given API doesn't mean the user is not authenticated with the IDP anymore.
