### ISSUE TITLE
SSR ( Server-side rendering) and window -reference

### ISSUE THREAD

**Issue by GipHub123** [auth0/auth0-angular#78]
Hi, I tried to run my application using server-side rendering (SSR) with Angular Universal but got 'window is not defined' -error. 
Problem seems to be in auth.client.ts -file:

```
return new Auth0Client({
      redirect_uri: redirectUri || window.location.origin,
      client_id: clientId,
      max_age: maxAge,
      ...rest,
      auth0Client: {
        name: useragent.name,
        version: useragent.version,
      },
    });
  }
```

![auth0_error](https://user-images.githubusercontent.com/12637608/97782718-c4c41e00-1b9b-11eb-8622-a4d5f44b309e.png)

![auth0_error_1](https://user-images.githubusercontent.com/12637608/97782734-cf7eb300-1b9b-11eb-9b50-284185248f0a.png)

### What was the expected behavior?

No "window is not defined" -error. 

### Environment

- **Version of `auth0-angular` used:** 1.2.0
- **Which browsers have you tested in?** Crome
- **Which version of Angular have you tested with?** 11.0.0-rc.1
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
Thanks for raising @GipHub123. We have outlined [our Angular Universal support in the readme](https://github.com/auth0/auth0-angular#angular-universal).

Right now it's not supported out of the box but is something we plan to revaluate in the future based on feedback.

**Comment by sanderspaul** [comment]
Any plans to reconsider this? It's stopped our enterprise implementation dead in the water. I'd really hate to have to roll our own bespoke implementation because this isn't supported.
