### ISSUE TITLE
Infinite redirect loop 

### ISSUE THREAD

**Issue by rrjohnson85** [auth0/auth0-angular#79]
### Describe the problem

Our account currently has a rule to check if a user is allowed to access a particular application, and if they do not, it throws an unauthorized error.  Note that this user may and likely does have access to other applications, just not this particular application.

When unauthorized error is thrown in the rule, the application using the Angular Auth0 library finds the user to be unauthenticated (which is probably fine) but throws the user into an infinite redirect loop.  I believe this is caused by this line https://github.com/auth0/auth0-angular/blob/ef3bc5d31ed8fd92513177558f7fd971adde7e1e/projects/auth0-angular/src/lib/auth.service.ts#L107

We're currently able to prevent this loop by logging the user out in a callback page; however, this is undesirable because the user will need login again to access any of our other applications.

### What was the expected behavior?

It would be nice if there were some way to provide a url or function of sorts for errors like this where the user is quasi logged in so we could respond to errors accordingly. 

### Reproduction

I cannot share a sample, but would be happy privately demo the issue or try to provide further details as needed.

### Environment

> Please provide the following:

- **Version of `auth0-angular` used:** ^1.2.0
- **Which browsers have you tested in?**  Chrome
- **Which version of Angular have you tested with?** ^10.2.0
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by frederikprijck** [comment]
Hi,

Just to get a bit more context here, is your root url (`/`) secured as well?

If that is the case, I can reproduce this behavior. Thanks for reporting this.

**Comment by rrjohnson85** [comment]
@frederikprijck yes, the only insecure route that I have is a callback page.

**Comment by frederikprijck** [comment]
Thanks. I can reproduce this and will have a look at how we can address this as I think this is a valid use-case that is causing problems.

**Comment by ThomasPrikrylBE** [comment]
Is there maybe already an update on a fix for this?

Maybe also verify that the solution works in combination with https://github.com/auth0/auth0-angular#dynamic-configuration

**Comment by frederikprijck** [comment]
I added a PR https://github.com/auth0/auth0-angular/pull/84, feel free to have a look to see if this solves your use case!
