### ISSUE TITLE
AuthService not resolving when accessing claims or user

### ISSUE THREAD

**Issue by AustinMcPhail** [auth0/auth0-angular#80]
### Describe the problem

- An Angular resolver is used before default layout component is loaded on the main route of an app. 
- The purpose of the resolver is to use the `user.sub` to fetch some permissions for the user from an api.
- The `user.sub` is being accessed successfully.
- The call to the api is successful.
- The resolver never resolvs, resulting in the default layout components hanging.

### What was the expected behavior?

```js
// ...
guard: [AuthGuard],
resolve: {
    users: UserResolver
},
component: LayoutComponent,
// ...
```
Should result in the user being logged in if not already, some details being fetched for the user, and then that data should be then available on the route in the layout component.

### Reproduction
1. Create a basic angular app and follow the steps provides by the auth0-angular documentation to initialize your Auth0 application in the `app.module.ts` file.
2. Create a layout component on a route that is protected by an AuthGuard, and resolves the user.
```js
// route
// ...
path: '',
canActivate: [AuthGuard],
resolve: {
    users: UserResolver
},
component: LayoutComponent,
// ...
```

```js
// user-resolver.ts
import { Injectable } from '@angular/core';
import { Resolve, ActivatedRouteSnapshot, Router } from '@angular/router';
import { AuthService } from '@auth0/auth0-angular';
import { UserPermissionService } from '@myServices';
import { Observable, of } from 'rxjs';
import { mergeMap, tap } from 'rxjs/operators';

@Injectable({ providedIn: 'root' })
export class UserResolver implements Resolve<User[]> {
    private user;
    constructor(
        private service: UserPermissionService,
        private auth: AuthService,
        private router: Router,
    ) {}
    public resolve(route: ActivatedRouteSnapshot): Observable<User[]> {
        // Old method w/ auth0-spa-js (this worked)
        // ---
        // const auth0Client$ = (from(
        //     createAuth0Client({
        //         domain: this.environment.auth0_domain,
        //         client_id: this.environment.auth0_clientId,
        //         redirect_uri: this.environment.callbackUrl,
        //         response_type: 'token',
        //         audience: this.environment.auth0_audience,
        //         cacheLocation: 'localstorage',
        //     })
        // ) as Observable<Auth0Client>).pipe(
        //     shareReplay(1),
        //     catchError((err) => throwError(err))
        // );
        // ---
        // return auth0Client$.pipe(
        //     concatMap((client: Auth0Client) => from(client.getUser()))
        // ).pipe(
        //     mergeMap((user) => {
        //         return this.userPermission.getUserWithUserId(user.sub).pipe(
        //             tap((users) => {
        //                 console.log('old', users);
        //             })
        //         );
        //     })
        // );

        return this.auth.idTokenClaims$.pipe(
            mergeMap((res) => {
                // Alternatively, return of([]); also does not work here
                return this.service.getUser(res.sub).pipe(
                    tap((users) => {
                        // This fires and I see the correct data
                        console.log('new', users);
                    })
                );
            })
        );
    }
}
```
3. Navigate to the layout component. The resolver should complete and the default `<p>Layout component works!</p>`, but instead fails and is left with blank screen.
No logs are produced other than the expected `console.log('new', users)`

### Environment

> Please provide the following:

- **Version of `auth0-angular` used:*^1.2.0*
- **Which browsers have you tested in?*Chrome*
- **Which version of Angular have you tested with?*^10.1.0*
- **Other modules/plugins/libraries that might be involved:*Rxjs, Nx*

**Comment by AustinMcPhail** [comment]
Also wanted to add that, as a work around, I added another "canActivate" that gets the Id and sets it in a service, which the resolver then uses to successfully get the user. This is what led me to believing it is a specific interaction between the AuthService and Resolvers.

**Comment by frederikprijck** [comment]
Hey @AustinMcPhail ,

When using Angular Resolvers, it is important to return an Observable that **completes**, as the resolver will keep waiting it it never completes. The `AuthService.idTokenClaims$` never completes, so returning that will result in a Resolver that wil never resolve.

Adding `take(1)` should solve your problem:

```
@Injectable({ providedIn: 'root' })
export class UserResolver implements Resolve<User[]> {
    private user;
    constructor(
        private service: UserPermissionService,
        private auth: AuthService,
        private router: Router,
    ) {}
    public resolve(route: ActivatedRouteSnapshot): Observable<User[]> {
        return this.auth.idTokenClaims$.pipe(
            mergeMap((res) => {
                return this.service.getUser(res.sub).pipe(
                    tap((users) => {
                        console.log('new', users);
                    })
                );
            }),
            take(1)
        );
    }
}
```

Closing this, but feel free to continue conversation is this did not solve your problem.
