### ISSUE TITLE
Get new token only once in interceptor when multiple API requests are made before token request completes

### ISSUE THREAD

**Issue by 7opf** [auth0/auth0-angular#81]
### Describe the problem you'd like to have solved

Currently when there is no or expired token and making multiple API requests in parallel or quick succession there is a call to `/token` on auth0 for each request. This is inefficient and calls to `/token` are rate limited which could result in unnecessary errors.

### Describe the ideal solution

The interceptor should request a new token for the first matching API request and subsequent requests should await the new token.

## Alternatives and current work-arounds

Current workaround is to await a single API request prior to any parallel API requests such that the token is already present and valid for the parallel requests.

**Comment by frederikprijck** [comment]
Could you describe the situation in which you are seeing multiple calls to the /token endpoint? We should have a mechanism in place in SPAJS SDK that should prevent this. So it should not be expected to see multiple calls to the /token endpoint.

**Comment by 7opf** [comment]
I'm sorry, I can't reproduce it again in my application. Looks like there was something else going on in my application.
