### ISSUE TITLE
Allow customized token endpoint

### ISSUE THREAD

**Issue by amiram** [auth0/auth0-angular#89]
### Describe the problem you'd like to have solved

> I used this great lib to connect with cognito instead of auth0. Everything works great, but the token endpoint has CORS error. This lib is using /oauth/token as the url. It it hardcoded in the code. If I could change that to /token it would have worked (I tested that with other lib).

**Comment by frederikprijck** [comment]
Currently, this SDK is intended to be used with Auth0 only. There are more internal parts in the code that assume you use Auth0, so making the URL configurable to be used with other OAuth providers is currently not on our roadmap as it will introduce other, protentional, issues for those that use it with another provider.
