### ISSUE TITLE
isAuthenticated$ and user$ are not updated after loginWithPopup()

### ISSUE THREAD

**Issue by rikuiki** [auth0/auth0-angular#92]
### Describe the problem

I have code which logins user using Auth0 Universal Login window by calling loginWithPopup().

### What was the expected behavior?

After successful login, I expect isAuthenticated$ and user$ observables to emit new values, but they don't.

### Reproduction

I can try to provide simple amp, if you have existing sandbox template/workflow for this.

**Comment by frederikprijck** [comment]
Thanks for reporting this, would you be able to reproduce this in Stackblitz or fork our repository and reproduce it inside the playground? https://github.com/auth0/auth0-angular/tree/master/projects/playground. This would help us investigate this more easily, thanks!

I tried reproducing this, but for me both `isAuthenicated$` and `user$` emits as expected.

**Comment by rikuiki** [comment]
HI Frederik, thank you for feeback, I couldn't reproduce the problem on Playground template, and later found problem with my code. Looks like this works as intended. Thank you again!
