### ISSUE TITLE
The call to Authorize include httpInterceptor in the queryParams

### ISSUE THREAD

**Issue by Boomwav** [auth0/auth0-angular#96]
### Describe the problem you'd like to have solved

My identity provider is complaining that the query params I call Authorize with contains the httpInterceptor.

In fact, after looking at the networking tab, it seems I really redirect with httpInterceptor in the params.
[...]**&httpInterceptor=%5Bobject%20Object%5D**&ui_locales=fr&response_type=code&response_mode=query
If I remove the httpInterceptor from the AuthConfig, it is then not sent in the URL.

### Describe the ideal solution

httpInterceptor shouldn't be included in the queryParams call to Authorize.

## Alternatives and current work-arounds

Not use the official HttpInterceptor. 

### Additional context

Since right now, I use multiple Auth Providers, I'm cornered because on one side, there's #86 that force me to use the default interceptor and on the other, there's this queryParams that breaks my Auth0 if I don't use a custom interceptor.

**Comment by stevehobbsdev** [comment]
We have just merged https://github.com/auth0/auth0-angular/pull/91 and expect a release shortly, which should solve this issue. Stay tuned!

**Comment by frederikprijck** [comment]
@Boomwav Could you elaborate a bit more on your concern ?

> I'm cornered because on one side, there's #86 that force me to use the default interceptor and on the other, there's this queryParams that breaks my Auth0 if I don't use a custom interceptor.

Does this concern still exist once #86 and #91 get released?

**Comment by Boomwav** [comment]
No. Thanks for asking. If any of those two fix are released, I'll be golden. I'll close it since it's a duplicate.
Duplicate of #91.

**Comment by frederikprijck** [comment]
Great, I am working on finalizing things for a release!

**Comment by frederikprijck** [comment]
@Boomwav This has been released so it should work fine now.
