### ISSUE TITLE
angular-jwt minification problem ?

### ISSUE THREAD

**Issue by jensoleg** [auth0/auth0-angular#96]
Hi
I have investigated problems with minification and have noticed there might be a problem with angular-jwt. Minification of auth0-angular is ok but for now i have to leave angular-jwt out of minification together with app config part. I am not sure but there might be a problem here in angular-jwt because the tokenGetter is minimized.

          var tokenPromise = $q.when($injector.invoke(config.tokenGetter, this, {
            config: request
          }));

As a workaround i put app config out of minification and use the minified version of angular-jwt. However the biggest problem is to drill down the problem and a solution could help others running into the same issue. At least it took me some hours ;-)

Best !

**Comment by mgonto** [comment]
Hi @johnstontrav @jensoleg,

We're working on tackling this issue now.

Could you please provide us with a sample project where the error is happening to make it easier to debug?

Thanks!

**Comment by mgonto** [comment]
Please read the response from https://github.com/auth0/lock/issues/94#issuecomment-68895137.

We're working on a solution

**Comment by mgonto** [comment]
it has been fixed with version `4.0.1` of `auth0-angular` :).
