### ISSUE TITLE
user$ not updated after changing claims and renewing tokens silently

### ISSUE THREAD

**Issue by appie2go** [auth0/auth0-angular#98]
Hi!

First of all: Thank you guys for building an awesome library! It saved us a lot of work. Hopefully, this bug report helps to make it even more awesome. Here's what I'm running into. 

I'm using the auth0-angular library in our Angular 9 spa and I ran into this issue: In our application, we show the name of the logged-in person. We use the id_token to get the name. We have a way the user can change his name, we use the auth0 API to update his claims in Auth0. In the SPA we use the `authService.getAccessTokenSilently({ignoreCache: true})` to renew the access_token and the id_token and we expect it to contain the new name. And it does! When I inspect the localstorage, and copy the id_token from it, and inspect it at jwt.io, I can see that the name has been updated in the id_token correctly, as I expected. But the `authService.user$` is not being updated, so the spa does not show the new name.

To be brief, this is my test-case:

Scenario: Renewing tokens after the claims have been changed
Given somebody has logged into my SPA
   And the access_token and the id_token have been retrieved and are stored in localstorage/sessionstorage
   And the claims of the id_token have changed in Auth0 after the access_token and id_token have been retrieved in the SPA
When the tokens are renewed using `authService.getAccessTokenSilently({ignoreCache: true})`
 Then the authService.user$ observable should be showing values of the changed claims!

Steps to reproduce:
- Create a spa, and subscribe to the authService.user$ to display the user claims
- Log into the spa
- Change the user's claims in manage.auth0.com
- Call the authService.getAccessTokenSilently({ignoreCache: true})
- Expected: The claims should display the expected value

Please let me know if this bug report provides enough information to get it fixed. Also, please let me know if it's appreciated if  I try to fix it myself and make pull request.

Thanks in advance,

**Comment by frederikprijck** [comment]
Thanks for reporting this. I see what is going wrong.

> Also, please let me know if it's appreciated if I try to fix it myself and make pull request.

In general, we welcome any contribution! However, we see some refactoring opportunities here and would love to take this one ourselves.

**Comment by appie2go** [comment]
Hi Frederik, 

Thank you for your reply. Good to hear it will be fixed. If you are able to share any information about the planning that would be greatly appreciated. Then we can adjust ours accordingly. 

Thanks again. And if there's anything we can do to help, let me know!

Cheers,

Albert

**Comment by appie2go** [comment]
Hi Frederik. On behalf of myself and my team, I'd like to say thanks for fixing this (so soon)!

**Comment by frederikprijck** [comment]
You are welcome. We will release this fix soon so you can update to the latest version.

**Comment by frederikprijck** [comment]
We have cut a release, so you should be able to use this as of 1.3.1, available on npm.
